### ISSUE TITLE
Updating mapbox to 10.2.0 to use View annotations feature got me error inflate of com.mapbox.maps.MapView

### ISSUE THREAD

**Issue by fadwafb** [mapbox/mapbox-maps-android#1013]
## Environment

- Android OS version: 10.0, 11.0 
- Devices affected: Huawei p30, pixel 2
- Maps SDK Version: 10.2.0

## Observed behavior and steps to reproduce

 when i migrated from Maps SDK version 10.0.0 to 10.2.0, The app crashes

 

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.victorapp/com.example.victorapp.ui.main.views.activities.SearchDestinationClientActivity}: android.view.InflateException: Binary XML file line #10 in com.example.victorapp:layout/activity_search_destination_client: Binary XML file line #10 in com.example.victorapp:layout/activity_search_destination_client: Error inflating class com.mapbox.maps.MapView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)`

**Comment by Chaoba** [comment]
@fadwafb Can you provide more details on how you are using the View annotations and a step-by-step process to reproduce this issue?

**Comment by fadwafb** [comment]
I used it as the example provided on the documentations. I tried to remove the View annotations feature to localize the problem and even the map didn't show, i got a runtime error inflating the mapview element on the layout. the version of the sdk is the only thing i changed in my code

**Comment by yunikkk** [comment]
@fadwafb why have you added this line to your manifest? Does it work without it? 
We rely on the startup provider to load native libraries via `MapboxMapsInitializer.java`

**Comment by fadwafb** [comment]
@yunikkk no it doesn't work without it !

**Comment by yunikkk** [comment]
> @yunikkk I added that line because the app doesn't start without it ! and when i added it i got that problem ! when i go back to 10.0.0 sdk version the app works well but i cannot use `View annotations feature`

Could you please share the full crash log without this line and with it?

**Comment by fadwafb** [comment]
@yunikkk 

- Without that line and just updating the SDK to 10.2.0 : 
`2021-12-23 11:56:52.599 6472-6472/com.example.victorapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.victorapp, PID: 6472
    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common9Scheduler15CreateSequencedEv" referenced by "/data/app/com.example.victorapp-1viF_o9V1q2sja6RuQS_Yg==/lib/arm64/libnavigator-android.so"...
        at android.app.ActivityThread.installProvider(ActivityThread.java:7755)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7291)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7187)
        at android.app.ActivityThread.access$2200(ActivityThread.java:296)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common9Scheduler15CreateSequencedEv" referenced by "/data/app/com.example.victorapp-1viF_o9V1q2sja6RuQS_Yg==/lib/arm64/libnavigator-android.so"...
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:162)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:38)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2121)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2094)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7750)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7291) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7187) 
        at android.app.ActivityThread.access$2200(ActivityThread.java:296) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8178) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common9Scheduler15CreateSequencedEv" referenced by "/data/app/com.example.victorapp-1viF_o9V1q2sja6RuQS_Yg==/lib/arm64/libnavigator-android.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at com.mapbox.common.loader.MapboxLibraryLoader.load(MapboxLibraryLoader.kt:19)
        at com.mapbox.navigator.MapboxNavigationNativeInitializer.create(MapboxNavigationNativeInitializer.kt:16)
        at com.mapbox.navigator.MapboxNavigationNativeInitializer.create(MapboxNavigationNativeInitializer.kt:10)
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198) 
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:38) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2121) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2094) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7750) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7291) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7187) 
        at android.app.ActivityThread.access$2200(ActivityThread.java:296) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8178) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at `com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)`


- With that line :
 `2021-12-23 12:14:11.660 5050-5050/com.example.victorapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.victorapp, PID: 5050
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.victorapp/com.example.victorapp.ui.main.views.activities.SearchDestinationClientActivity}: android.view.InflateException: Binary XML file line #10 in com.example.victorapp:layout/activity_search_destination_client: Binary XML file line #10 in com.example.victorapp:layout/activity_search_destination_client: Error inflating class com.mapbox.maps.MapView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.view.InflateException: Binary XML file line #10 in com.example.victorapp:layout/activity_search_destination_client: Binary XML file line #10 in com.example.victorapp:layout/activity_search_destination_client: Error inflating class com.mapbox.maps.MapView
     Caused by: android.view.InflateException: Binary XML file line #10 in com.example.victorapp:layout/activity_search_destination_client: Error inflating class com.mapbox.maps.MapView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at com.example.victorapp.databinding.ActivitySearchDestinationClientBinding.inflate(ActivitySearchDestinationClientBinding.java:66)
        at com.example.victorapp.databinding.ActivitySearchDestinationClientBinding.inflate(ActivitySearchDestinationClientBinding.java:60)
        at com.example.victorapp.ui.main.views.activities.SearchDestinationClientActivity.onCreate(SearchDestinationClientActivity.kt:182)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-12-23 12:14:11.660 5050-5050/com.example.victorapp E/AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.maps.assets.AssetManagerProvider.initialize(android.content.res.AssetManager) (tried Java_com_mapbox_maps_assets_AssetManagerProvider_initialize and Java_com_mapbox_maps_assets_AssetManagerProvider_initialize__Landroid_content_res_AssetManager_2)
        at com.mapbox.maps.assets.AssetManagerProvider.initialize(Native Method)
        at com.mapbox.maps.MapController.<init>(MapController.kt:60)
        at com.mapbox.maps.MapView.<init>(MapView.kt:101)
        at com.mapbox.maps.MapView.<init>(MapView.kt:69)
        at com.mapbox.maps.MapView.<init>(MapView.kt:63)
        	... 27 more`

**Comment by yunikkk** [comment]
The issue should with navigation/common dependencies incompatibilities, error message :
`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common9Scheduler15CreateSequencedEv" referenced by "/data/app/com.example.victorapp-1viF_o9V1q2sja6RuQS_Yg==/lib/arm64/libnavigator-android.so"` 
Which versions of mapbox navigation (and mapbox common if you have it as explicit dependency as well) do you use?

**Comment by fadwafb** [comment]
I'm using mapbox navigation `2.0.1`

**Comment by yunikkk** [comment]
@fadwafb could you try [beta 2.2.0](v2.2.0-beta.1), this one contains common of the same version that is used in Maps 10.2

**Comment by fadwafb** [comment]
Thanks @yunikkk  it's working with this version of Mapbox navigation
