### ISSUE TITLE
No implementation found for void com.mapbox.maps.OfflineManager

### ISSUE THREAD

**Issue by badoualy** [mapbox/mapbox-maps-android#1057]
## Environment

- Android OS version: Android 9 (api 28)
- Devices affected: Samsung Galaxy S8
- Maps SDK Version: 10.2.0 (already tried 10.3.0 beta)

## Observed behavior and steps to reproduce

Calling 
```
OfflineManager(MapInitOptions.getDefaultResourceOptions(context))
```

crashes with the following stacktrace:
```
No implementation found for void com.mapbox.maps.OfflineManager.initialize(com.mapbox.maps.OfflineManager, com.mapbox.maps.ResourceOptions) (tried Java_com_mapbox_maps_OfflineManager_initialize and Java_com_mapbox_maps_OfflineManager_initialize__Lcom_mapbox_maps_OfflineManager_2Lcom_mapbox_maps_ResourceOptions_2)
        at com.mapbox.maps.OfflineManager.initialize(Native Method)
        at com.mapbox.maps.OfflineManager.<init>(OfflineManager.java:22)
```

Everything else seems to be working fine. This is a debug build.

Added as:
```
implementation "com.mapbox.maps:android:10.3.0-beta.1"
```

**Comment by badoualy** [comment]
Found the issue, for anyone passing here with the same issue (and other managers:)

````
       <provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="${applicationId}.androidx-startup"
            tools:node="remove" />
```

This code in the manifest was the case. 
Maybe a note in the setup documentation would be nice.

**Comment by yunikkk** [comment]
@badoualy hi, what was the reason to add this provider removal code in the manifest before?
