### ISSUE TITLE
dynamic traveled path - GeoJsonSource causes crash when accessed.

### ISSUE THREAD

**Issue by pcutting** [mapbox/mapbox-maps-android#1232]
Hi guys,

I'm working on an app that tracks where the user has traveled.  I might be using the wrong process, but as there is no destination, I'm not using the navigation api.  

Using geoJson I'm trying to add a layer, and remove it and then add it back as it gets updated.  Links to the PR and repo are at the end.  

I'm trying to use geoJson and the lineString Feature.  

Working on Android in Kotlin.

I'm getting the following error: (Logcat screenshot)
![image](https://user-images.githubusercontent.com/10826/148292812-e5de638c-5e90-480d-8213-a0be0433ea78.png)

LogCat Error log:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.philipcutting.letswalkabout, PID: 30279
    java.lang.RuntimeException: Couldn't get data: source is not added to style yet.
        at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.getData(GeoJsonSource.kt:810)
        at com.philipcutting.letswalkabout.MainActivity.onCreate$lambda-5$lambda-4(MainActivity.kt:137)
        at com.philipcutting.letswalkabout.MainActivity.$r8$lambda$MkQquGLs1CQUPER59ULPWVQhxDo(Unknown Source:0)
        at com.philipcutting.letswalkabout.MainActivity$$ExternalSyntheticLambda3.onStyleLoaded(Unknown Source:2)
        at com.mapbox.maps.MapboxMap.getStyle(MapboxMap.kt:231)
        at com.philipcutting.letswalkabout.MainActivity.onCreate$lambda-5(MainActivity.kt:117)
        at com.philipcutting.letswalkabout.MainActivity.$r8$lambda$1eUcu3Rey6X6AJWoH8p0eV4xSds(Unknown Source:0)
        at com.philipcutting.letswalkabout.MainActivity$$ExternalSyntheticLambda2.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.philipcutting.letswalkabout.viewModels.MainViewModel.setPointOnChangedLocation(MainViewModel.kt:60)
        at com.philipcutting.letswalkabout.MainActivity.onIndicatorPositionChangedListener$lambda-1(MainActivity.kt:66)
        at com.philipcutting.letswalkabout.MainActivity.$r8$lambda$-xv8bBe9NsxLqmRQ1Xt3VEulPK8(Unknown Source:0)
        at com.philipcutting.letswalkabout.MainActivity$$ExternalSyntheticLambda6.onIndicatorPositionChanged(Unknown Source:2)
        at com.mapbox.maps.plugin.locationcomponent.LocationComponentPluginImpl$indicatorPositionChangedListener$1.onIndicatorPositionChanged(LocationComponentPluginImpl.kt:67)
        at com.mapbox.maps.plugin.locationcomponent.animators.PuckPositionAnimator.updateLayer(PuckPositionAnimator.kt:10)
        at com.mapbox.maps.plugin.locationcomponent.animators.PuckPositionAnimator.updateLayer(PuckPositionAnimator.kt:6)
```

When I step into the part that I think should make the path as location gets updated I get the following.  For testing, I've made it so there are at least 5 points that it should be using to make the lineString.
(Debugger screenshot - LineString being defined)
![image](https://user-images.githubusercontent.com/10826/148293987-fb215871-8ce2-4c15-b274-a81177101103.png)

(Feature being defined)
![image](https://user-images.githubusercontent.com/10826/148294688-c8fcf128-ab13-4bed-891e-e1248f62d8e1.png)

The data field isn't getting set even though the LineString feature appears to be set.
(GeoJsonSource created, data ends up being `null`, is this the issue?)
![image](https://user-images.githubusercontent.com/10826/148295110-40f4fdba-95f1-4506-850e-d21526fa0096.png)

(MapView activity screenshot)
![image](https://user-images.githubusercontent.com/10826/148294128-adaad4df-576d-4690-a1e4-9ba1c6dca3e8.png)

Trying to avoid the crash issue I checked for null in the geoJsonSource, but that's where it all crashes on me (line 137)
```
               if (geoJsonSourceItem.data == null) {
                    Log.e(TAG, "data is null")
                } else {
                    style.addSource(geoJsonSourceItem)
                }
```
(image) 
![image](https://user-images.githubusercontent.com/10826/148295691-f1ae8fa3-9567-4b9d-8503-60e7ffe01c1b.png)

OnCreate: Where the magic doesn't seem to happen: 
```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        mapView = binding.mapView
        setContentView(binding.root)
        annotationApi = mapView.annotations
        polylineAnnotationManager = annotationApi.createPolylineAnnotationManager(mapView)
        val polylineAnnotationOptions: PolylineAnnotationOptions = PolylineAnnotationOptions()
            .withPoints(emptyList())
            .withLineColor("#FF1122")
            .withLineWidth(5.0)
        polylineAnnotationManager.create(polylineAnnotationOptions)

        binding.fabCurrentLocation.setOnClickListener {
            fabCurrentLocationOnClick()
        }

        binding.fabBarringOption.setOnClickListener {
            fabBearingOptionOnClick()
        }

        locationPermissionHelper = LocationPermissionHelper(WeakReference(this))
        locationPermissionHelper.checkPermissions(onMapReady)

        viewModel.pathList.observe(this){
            if (viewModel.mapsPath().size < 5) return@observe

            mapView.getMapboxMap().getStyle { style ->
                val lineString = LineString.fromLngLats(viewModel.mapsPath())
                val feature = Feature.fromGeometry(lineString)

                // Also tried the following, but still didn't have success.
                /*val source = style.getSourceAs<GeoJsonSource>(GEOJSON_SOURCE_ID)
                if (source != null && feature.geometry() != null) {
                    source.feature(feature)
                    source.data("some data")
                }*/

                val geoJsonSourceItem = GeoJsonSource.Builder(GEOJSON_SOURCE_ID)
                    .data("path")
                    .feature(feature)
                    .build()

                if(style.styleSourceExists(GEOJSON_SOURCE_ID)) {
                    style.removeStyleSource(GEOJSON_SOURCE_ID)
                }

                if (geoJsonSourceItem.data == null) {
                    Log.e(TAG, "data is null")
                } else {
                    style.addSource(geoJsonSourceItem)
                }
            }
        }
    }
```

----------------

(Full code - https://github.com/pcutting/LetsWalkabout/blob/cb4bb78ca64933bc86ad6b2ff6f28589dff670da/app/src/main/java/com/philipcutting/letswalkabout/MainActivity.kt)
```
package com.philipcutting.letswalkabout

import android.content.res.ColorStateList
import android.os.Bundle
import android.util.Log
import android.widget.Toast
import androidx.activity.viewModels
import androidx.appcompat.app.AppCompatActivity
import com.mapbox.android.gestures.Constants
import com.mapbox.android.gestures.MoveGestureDetector
import com.mapbox.core.constants.Constants.PRECISION_6
import com.mapbox.geojson.Feature
import com.mapbox.geojson.LineString
import com.mapbox.maps.CameraOptions
import com.mapbox.maps.MapEvents
import com.mapbox.maps.MapView
import com.mapbox.maps.Style
import com.mapbox.maps.extension.observable.eventdata.StyleDataLoadedEventData
import com.mapbox.maps.extension.style.sources.addSource
import com.mapbox.maps.extension.style.sources.generated.GeoJsonSource
import com.mapbox.maps.extension.style.sources.generated.geoJsonSource
import com.mapbox.maps.extension.style.sources.getSourceAs
import com.mapbox.maps.plugin.annotation.AnnotationPlugin
import com.mapbox.maps.plugin.annotation.annotations
import com.mapbox.maps.plugin.annotation.generated.PolylineAnnotationManager
import com.mapbox.maps.plugin.annotation.generated.PolylineAnnotationOptions
import com.mapbox.maps.plugin.annotation.generated.createPolylineAnnotationManager
import com.mapbox.maps.plugin.delegates.listeners.OnStyleDataLoadedListener
import com.mapbox.maps.plugin.gestures.OnMoveListener
import com.mapbox.maps.plugin.gestures.gestures
import com.mapbox.maps.plugin.locationcomponent.OnIndicatorBearingChangedListener
import com.mapbox.maps.plugin.locationcomponent.OnIndicatorPositionChangedListener
import com.mapbox.maps.plugin.locationcomponent.location
import com.philipcutting.letswalkabout.databinding.ActivityMainBinding
import com.philipcutting.letswalkabout.models.PathPointAndOrBearing
import com.philipcutting.letswalkabout.viewModels.MainViewModel
import java.lang.ref.WeakReference

class MainActivity : AppCompatActivity() {
    private lateinit var mapView: MapView
    private lateinit var binding: ActivityMainBinding
    private lateinit var locationPermissionHelper: LocationPermissionHelper

    lateinit var annotationApi: AnnotationPlugin
    lateinit var polylineAnnotationManager: PolylineAnnotationManager

    private val viewModel : MainViewModel by viewModels()

    companion object {
        private const val TAG = "MainActivity"
        private const val GEOJSON_SOURCE_ID = "geojson_source_id"
    }

    private val onIndicatorBearingChangedListener = OnIndicatorBearingChangedListener {
        viewModel.setBearingOnChanged(it)
        if(viewModel.hasChangedBearing.value == true) {
            mapView.getMapboxMap().setCamera(CameraOptions.Builder().bearing(it).build())
        }
    }

    private val onIndicatorPositionChangedListener = OnIndicatorPositionChangedListener {
        if(it.latitude() == 0.0 ||  it.longitude() == 0.0) {
            return@OnIndicatorPositionChangedListener
        }

        viewModel.setPointOnChangedLocation(it)
        viewModel.lastPointOrBearing.value = PathPointAndOrBearing(it)
        if(viewModel.isTrackingLocationOnMap.value == true) {
            mapView.getMapboxMap().setCamera(CameraOptions.Builder().center(it).build())
            mapView.gestures.focalPoint = mapView.getMapboxMap().pixelForCoordinate(it)
        }
    }

    private val onMapReady: () -> Unit = {
        mapView.getMapboxMap().setCamera(
            CameraOptions.Builder()
                .zoom(16.0)
                .build()
        )
        mapView.getMapboxMap().loadStyleUri(
            Style.MAPBOX_STREETS
        ) {
            Log.i(TAG, "onMapReady: .loadStyleUri")
            initLocationComponent()
            setupGesturesListener()
            setupDataEventListener()
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        mapView = binding.mapView
        setContentView(binding.root)
        annotationApi = mapView.annotations
        polylineAnnotationManager = annotationApi.createPolylineAnnotationManager(mapView)
        val polylineAnnotationOptions: PolylineAnnotationOptions = PolylineAnnotationOptions()
            .withPoints(emptyList())
            .withLineColor("#FF1122")
            .withLineWidth(5.0)
        polylineAnnotationManager.create(polylineAnnotationOptions)

        binding.fabCurrentLocation.setOnClickListener {
            fabCurrentLocationOnClick()
        }

        binding.fabBarringOption.setOnClickListener {
            fabBearingOptionOnClick()
        }

        locationPermissionHelper = LocationPermissionHelper(WeakReference(this))
        locationPermissionHelper.checkPermissions(onMapReady)

        viewModel.pathList.observe(this){
            if (viewModel.mapsPath().size < 5) return@observe

            mapView.getMapboxMap().getStyle { style ->
                val lineString = LineString.fromLngLats(viewModel.mapsPath())
                val feature = Feature.fromGeometry(lineString)

                // Also tried the following, but still didn't have success.
                /*val source = style.getSourceAs<GeoJsonSource>(GEOJSON_SOURCE_ID)
                if (source != null && feature.geometry() != null) {
                    source.feature(feature)
                    source.data("some data")
                }*/

                val geoJsonSourceItem = GeoJsonSource.Builder(GEOJSON_SOURCE_ID)
                    .data("path")
                    .feature(feature)
                    .build()

                if(style.styleSourceExists(GEOJSON_SOURCE_ID)) {
                    style.removeStyleSource(GEOJSON_SOURCE_ID)
                }

                if (geoJsonSourceItem.data == null) {
                    Log.e(TAG, "data is null")
                } else {
                    style.addSource(geoJsonSourceItem)
                }
            }
        }
    }

    private fun fabBearingOptionOnClick() {
        viewModel.hasChangedBearing.value = viewModel.hasChangedBearing.value == false

        if (viewModel.hasChangedBearing.value == true) {
            //TODO change color of button when pressed
            binding.fabBarringOption.backgroundTintList =
                ColorStateList.valueOf(getColor(R.color.fab_primary))
        } else {
            binding.fabBarringOption.backgroundTintList =
                ColorStateList.valueOf(getColor(R.color.fab_alt))
        }
    }

    private fun fabCurrentLocationOnClick() {
        viewModel.isTrackingLocationOnMap.value = viewModel.isTrackingLocationOnMap.value == false

        if (viewModel.isTrackingLocationOnMap.value == true) {
            binding.fabCurrentLocation.backgroundTintList =
                ColorStateList.valueOf(getColor(R.color.fab_primary))
        } else {
            binding.fabCurrentLocation.backgroundTintList =
                ColorStateList.valueOf(getColor(R.color.fab_alt))
        }
    }

    private fun setupGesturesListener() {
        Log.i(TAG, "setupGesturesListener")
        mapView.gestures.addOnMoveListener(onMoveListener)
    }

    private fun initLocationComponent() {
        Log.i(TAG, "init Location Components")
        val locationComponentPlugin = mapView.location
        locationComponentPlugin.updateSettings {
            this.enabled = true
        }
        locationComponentPlugin.addOnIndicatorPositionChangedListener(onIndicatorPositionChangedListener)
        locationComponentPlugin.addOnIndicatorBearingChangedListener(onIndicatorBearingChangedListener)
    }

    private fun removeListeners() {
        mapView.location.removeOnIndicatorPositionChangedListener(onIndicatorPositionChangedListener)
        mapView.location.removeOnIndicatorBearingChangedListener(onIndicatorBearingChangedListener)
        mapView.gestures.removeOnMoveListener(onMoveListener)
    }

    private fun onCameraTrackingDismissed() {
        Toast.makeText(
            this,
            "onCameraTrackingDismissed",
            Toast.LENGTH_SHORT).show()
        viewModel.isTrackingLocationOnMap.value = false
        viewModel.hasChangedBearing.value = false
    }

    private fun setupDataEventListener() {
        Log.i(TAG, "setupDataEventListener()")
        mapView.getMapboxMap().addOnStyleDataLoadedListener(onMapEventsStyleDataLoaded)
    }

    private val onMapEventsStyleDataLoaded = OnStyleDataLoadedListener{ eventData ->
        Log.e(TAG, "onStyleDataLoaded: $eventData")
        if (eventData == null) {
            Log.e(TAG, "data is null")
        } else {
            Log.e(TAG, "data is not null")
        }
    }

    private val onMoveListener = object : OnMoveListener {
        override fun onMove(detector: MoveGestureDetector): Boolean {

            return false
        }

        override fun onMoveBegin(detector: MoveGestureDetector) {
            onCameraTrackingDismissed()
        }

        override fun onMoveEnd(detector: MoveGestureDetector) {
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        removeListeners()
    }

    override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<out String>,
        grantResults: IntArray
    ) {
        Log.i(TAG, "onRequestPermissionsResult")
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        locationPermissionHelper.onRequestPermissionsResult(requestCode, permissions,grantResults)
    }
}
```

Dependencies: 
```
    //Mapbox
    implementation 'com.mapbox.maps:android:10.1.0'
    implementation 'com.mapbox.navigation:android:2.1.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.1.0'
    //Turf: Runtime geospatial calculations.
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:6.1.0'
    //Core: Color, text, and networking utility classes
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-core:6.1.0'
    implementation 'androidx.annotation:annotation:1.3.0'
```
Targetting api 30.   

Source code: https://github.com/pcutting/Letswalkabout
PR: https://github.com/pcutting/LetsWalkabout/pull/7

**Comment by yunikkk** [comment]
Hey @pcutting have you been able to resolve this? 
From what I can see - do you need to access `data` field at all? Data property is defined as  
```
  /**
   * A URL to a GeoJSON file, or inline GeoJSON.
   *
   * Note: Getter for plain Geojson string data is not supported due to performance consideration.
   */
  val data: String?
```
Why do you need it at all? Should be enough to just create geojson with DSL:
```
geoJsonSource(GEOJSON_SOURCE_ID) {
      feature(lineStringFeature)
    }
```

**Comment by ZiZasaurus** [comment]
@pcutting did the comment above help you resolve your issue?

**Comment by ZiZasaurus** [comment]
Closing this ticket but please feel free to reopen if you have additional questions.
