### ISSUE TITLE
Map.jumpTo std::exception

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-maps-android#145]
Vague crash caught by crashlytics on `10.0.0-beta.13`.
Device: Huawei Mate 20 lite
Android: 10

```
Fatal Exception: java.lang.Error: std::exception
       at com.mapbox.maps.Map.jumpTo(Map.java)
       at com.mapbox.maps.NativeMapImpl.jumpTo(NativeMapImpl.java:34)
       at com.mapbox.maps.MapboxMap$jumpTo$1.invoke(MapboxMap.java:263)
       at com.mapbox.maps.MapboxMap$jumpTo$1.invoke(MapboxMap.java:32)
       at com.mapbox.maps.UtilsKt.call(UtilsKt.java:9)
       at com.mapbox.maps.MapboxMap.jumpTo(MapboxMap.java:263)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.performMapJump(CameraAnimationsPluginImpl.java:147)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.access$getPitchListeners$p(CameraAnimationsPluginImpl.java:30)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl$registerInternalUpdateListener$1.onAnimationUpdate(CameraAnimationsPluginImpl.java:317)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1558)
       at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1349)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1481)
       at android.animation.ValueAnimator.pulseAnimationFrame(ValueAnimator.java:1500)
       at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1170)
       at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1061)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1055)
       at android.view.Choreographer.doCallbacks(Choreographer.java:875)
       at android.view.Choreographer.doFrame(Choreographer.java:772)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

/cc @mapbox/maps-android

**Comment by tobrun** [comment]
Todo: ticket upstream

**Comment by tobrun** [comment]
JumpTo was refactored to setCamera, Please reach out if you are still facing this issue
