### ISSUE TITLE
ANR with mapBox traces in bug report

### ISSUE THREAD

**Issue by zhurbaTT** [mapbox/mapbox-maps-android#1512]
## Environment

- Android OS version: 11, 12
- Devices affected: Xiaomi, OnePlus
- Maps SDK Version: 

## Observed behavior and steps to reproduce

Sometimes we catch an ANR in our app.
It happens when we open a fragment with map inside and then quickly navigating back.
I can see nothing in logcat, but in android bug report (report generated via Android) I see this:

_------ VM TRACES AT LAST ANR (/data/anr/anr_2022-07-14-15-19-31-835: 2022-07-14 15:19:35) ------

….

"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x7985b9d0 self=0x773f414c00
  | sysTid=6274 nice=-10 cgrp=default sched=0/0 handle=0x773fbf2548
  | state=S schedstat=( 15078297369 1031997061 7217 ) utm=1396 stm=111 core=7 HZ=100
  | stack=0x7fedc2d000-0x7fedc2f000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait(Native method)
  - waiting on <0x02600954> (a java.lang.Object)
  at java.lang.Thread.parkFor$(Thread.java:2137)
  - locked <0x02600954> (a java.lang.Object)
  at sun.misc.Unsafe.park(Unsafe.java:358)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
  at com.mapbox.maps.renderer.MapboxRenderThread.onSurfaceDestroyed(MapboxRenderThread.kt:389)
  at com.mapbox.maps.renderer.MapboxTextureViewRenderer.onSurfaceTextureDestroyed(MapboxTextureViewRenderer.kt:47)
  at android.view.TextureView.releaseSurfaceTexture(TextureView.java:-1)
  at android.view.TextureView.onDetachedFromWindowInternal(TextureView.java:-1)
  at android.view.View.dispatchDetachedFromWindow(View.java:-1)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:-1)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:-1)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:-1)
  ... repeated 9 times
  at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:-1)
  at android.view.ViewRootImpl.doDie(ViewRootImpl.java:-1)
  - locked <0x00b3c0fd> (a android.view.ViewRootImpl)
  at android.view.ViewRootImpl.die(ViewRootImpl.java:-1)
  at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:-1)
  at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:-1)
  - locked <0x020471f2> (a java.lang.Object)
  at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:-1)
  at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:-1)
  at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:-1)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:-1)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:-1)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:-1)
  at android.os.Handler.dispatchMessage(Handler.java:-1)
  at android.os.Looper.loop(Looper.java:-1)
  at android.app.ActivityThread.main(ActivityThread.java:-1)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:-1)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:-1)

…_

**Comment by ZiZasaurus** [comment]
@zhurbaTT can you please provide the version of the SDK that you are using?

**Comment by zhurbaTT** [comment]
@ZiZasaurus sorry, forgot to provide it in the title.
Maps SDK Version: 10.3.0

**Comment by kiryldz** [comment]
Can you also share Android SDK versions that were affected?

**Comment by zhurbaTT** [comment]
Hello @kiryldz ,
I catched the bug with following SDK versions: 31, 30, 29, 28.

**Comment by kiryldz** [comment]
Can you by chance reproduce that ANR locally if using latest stable version released (it's 10.6.2) by using setup you mentioned above?
 > It happens when we open a fragment with map inside and then quickly navigating back.
