### ISSUE TITLE
App crashes with "java.lang.IllegalStateException: Camera plugin is not added as the part of MapInitOptions for given MapView."

### ISSUE THREAD

**Issue by zhurbaTT** [mapbox/mapbox-maps-android#1517]
## Environment

- Android OS version: 12, 10
- Devices affected: OnePlus, Xiaomi
- Maps SDK Version: 10.6.2, 10.6.0

## Observed behavior and steps to reproduce

After opening a fragment with map inside and quickly navigating back the app crashes.
The bug happens not very often.

`java.lang.IllegalStateException: Camera plugin is not added as the part of MapInitOptions for given MapView.
        at com.mapbox.maps.MapboxMap.cameraAnimationsPlugin(MapboxMap.kt:1671)
        at com.mapbox.maps.plugin.animation.CameraAnimationsUtils.flyTo(CameraAnimationsExt.kt:58)
        at com.mapbox.maps.plugin.animation.CameraAnimationsUtils.flyTo$default(CameraAnimationsExt.kt:55)
        at ru.trendagent.map.domain.mapService.modehelpers.AllBlocksModeHelper.goToStartCoordinates(AllBlocksModeHelper.kt:382)
        at ru.trendagent.map.domain.mapService.modehelpers.AllBlocksModeHelper.initMap(AllBlocksModeHelper.kt:99)
        at ru.trendagent.map.domain.mapService.MapBoxService.start(MapBoxService.kt:94)
        at ru.trendagent.map.domain.usecase.LoadMapUseCase$loadFullMap$1.invoke(LoadMapUseCase.kt:42)
        at ru.trendagent.map.domain.usecase.LoadMapUseCase$loadFullMap$1.invoke(LoadMapUseCase.kt:40)
        at trendmultiplatform.api.terminal.Terminal$loadMapQuery$2.invoke(Terminal.kt:557)
        at trendmultiplatform.api.terminal.Terminal$loadMapQuery$2.invoke(Terminal.kt:547)
        at multiplatform_rx.SingleReq$subscribe$1$1$2.invokeSuspend(SingleReq.kt:248)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`

**Comment by kiryldz** [comment]
Thanks for reporting!
I do understand why that could happen (because of weak references) - I will cut an internal ticket to fix that. Meanwhile I could suggest using camera / gestures plugin directly (e.g. `mapView.camera.flyTo` instead of `mapView.getMapboxMap().flyTo`), that will fix an issue.

**Comment by zhurbaTT** [comment]
Hello @kiryldz ,
Can I track this internal ticket?

**Comment by yunikkk** [comment]
@zhurbaTT it's in the private tracker, we will post updates here

**Comment by kiryldz** [comment]
Should be fixed by https://github.com/mapbox/mapbox-maps-android/pull/1591. Planning to be released in v10.8.0-rc.1.
