### ISSUE TITLE
[maps-core]: {MapboxRenderThr}[Shader]: Shader failed to compile 4:24: L0002: Function 'texture2D' not supported on target

### ISSUE THREAD

**Issue by oleksandr-riabykh** [mapbox/mapbox-maps-android#1598]
## Environment

- Android OS version: 7.1/Nougat
- Devices affected: Samsung Galaxy S2
- Maps SDK Version: 10.6.0

## Observed behavior and steps to reproduce

Integration 3D ride animations

```
08-15 16:04:15.000  7600  8016 E Mapbox  : [maps-core]: {MapboxRenderThr}[Shader]: Shader failed to compile 4:24: L0002: Function 'texture2D' not supported on target
...
08-15 16:04:16.070  7600  7992 E AndroidRuntime: FATAL EXCEPTION: MapboxRenderThread
08-15 16:04:16.070  7600  7992 E AndroidRuntime: Process: otp.systems.ridelink.stage, PID: 7600
08-15 16:04:16.070  7600  7992 E AndroidRuntime: java.lang.Error: shader failed to compile
08-15 16:04:16.070  7600  7992 E AndroidRuntime: 	at com.mapbox.maps.Map.render(Native Method)
08-15 16:04:16.070  7600  7992 E AndroidRuntime: 	at com.mapbox.maps.NativeMapImpl.render(NativeMapImpl.kt:32)
08-15 16:04:16.070  7600  7992 E AndroidRuntime: 	at com.mapbox.maps.renderer.MapboxRenderer.render(MapboxRenderer.kt:126)
08-15 16:04:16.070  7600  7992 E AndroidRuntime: 	at com.mapbox.maps.renderer.MapboxRenderThread.draw(MapboxRenderThread.kt:257)
08-15 16:04:16.070  7600  7992 E AndroidRuntime: 	at com.mapbox.maps.renderer.MapboxRenderThread.doFrame(MapboxRenderThread.kt:439)
08-15 16:04:16.070  7600  7992 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
08-15 16:04:16.070  7600  7992 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
08-15 16:04:16.070  7600  7992 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:618)
08-15 16:04:16.070  7600  7992 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
08-15 16:04:16.070  7600  7992 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
08-15 16:04:16.070  7600  7992 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-15 16:04:16.070  7600  7992 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-15 16:04:16.070  7600  7992 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)

## Expected behavior

no crashes

## Additional links and references

Might be related to:
https://android-developers.narkive.com/BLeH1GQg/function-texture2d-not-supported-on-target

**Comment by kiryldz** [comment]
@oleksandr-riabykh - could you please specify (just to be sure) if it fails with the very basic map or are you trying to enable terrain / globe functionality?
E.g. will the following code have the same error:
```kotlin
class SimpleMapActivity : AppCompatActivity() {

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    val mapView = MapView(this)
    setContentView(mapView)
  }
}
```

**Comment by oleksandr-riabykh** [comment]
no need anymore. we decided to drop support 7.1/Nougat
@kiryldz
