### ISSUE TITLE
Crash while zooming in  the map

### ISSUE THREAD

**Issue by Chaoba** [mapbox/mapbox-maps-android#168]
## Environment

- Android OS version: 6.0.1
- Devices affected: OPPO A57
- Maps SDK Version: v10.0.0-beta.15

## Observed behavior and steps to reproduce

Open a map and zoom in with two fings and app will crash
## Expected behavior
No crash happens.

## Additional links and references
```
    java.lang.ClassCastException: java.lang.Object cannot be cast to com.mapbox.maps.ScreenCoordinate
        at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl$registerInternalListener$1.finishAnimation(CameraAnimationsPluginImpl.kt:284)
        at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl$registerInternalListener$1.onAnimationCancel(CameraAnimationsPluginImpl.kt:264)
        at android.animation.ValueAnimator.cancel(ValueAnimator.java:1137)
        at android.animation.AnimatorSet.cancel(AnimatorSet.java:336)
        at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.cancelAnimatorSet(CameraAnimationsPluginImpl.kt:356)
        at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.startHighLevelAnimation(CameraAnimationsPluginImpl.kt:768)
        at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.easeTo(CameraAnimationsPluginImpl.kt:565)
        at com.mapbox.maps.plugin.gestures.GesturesPluginImpl.handleMove$plugin_gestures_debug(GesturesPluginImpl.kt:1264)
        at com.mapbox.maps.plugin.gestures.GesturesPluginImpl$MoveGestureListener.onMove(GesturesPluginImpl.kt:427)
        at com.mapbox.android.gestures.MoveGestureDetector.analyzeMovement(MoveGestureDetector.java:158)
        at com.mapbox.android.gestures.MultiFingerGesture.analyzeEvent(MultiFingerGesture.java:106)
        at com.mapbox.android.gestures.ProgressiveGesture.analyzeEvent(ProgressiveGesture.java:55)
        at com.mapbox.android.gestures.MoveGestureDetector.analyzeEvent(MoveGestureDetector.java:141)
        at com.mapbox.android.gestures.BaseGesture.analyze(BaseGesture.java:61)
        at com.mapbox.android.gestures.BaseGesture.onTouchEvent(BaseGesture.java:39)
        at com.mapbox.android.gestures.AndroidGesturesManager.onTouchEvent(AndroidGesturesManager.java:193)
        at com.mapbox.maps.plugin.gestures.GesturesPluginImpl.onTouchEvent(GesturesPluginImpl.kt:217)
        at com.mapbox.maps.plugin.MapPluginRegistry.onTouch(MapPluginRegistry.kt:125)
        at com.mapbox.maps.MapController.onTouchEvent(MapController.kt:131)
        at com.mapbox.maps.MapView.onTouchEvent(MapView.kt:277)
```

**Comment by kiryldz** [comment]
Related to using Android version <= 23.
Should be fixed as well add tests for animation system running on Android version <= 23 to make sure such things not happen in future.

**Comment by kiryldz** [comment]
Gesture plugin needs to be revisited because immediate jump still depends on handler and does not execute right away. It leads to issues on low-end devices because animation seems to work a bit different there resulting in incorrect behavior.
