### ISSUE TITLE
CameraAnimatorsFactory#getFlyTo crashes when padding is a single pixel

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-maps-android#177]
In the Navigation Camera use-case, we need to squish the padding into a single pixel to adjust the vanishing point of the camera. However, when this is done, the `CameraAnimatorsFactory#getFlyTo` crashes:
```
Process: com.mapbox.navigation.test_app, PID: 29587
java.lang.Error: latitude must not be NaN
    at com.mapbox.maps.Projection.unproject(Native Method)
    at com.mapbox.maps.MapboxMap.unproject(MapboxMap.kt:636)
    at com.mapbox.maps.plugin.animation.CameraAnimatorsFactory$getFlyTo$animators$2.evaluate(CameraAnimatorsFactory.kt:395)
    at com.mapbox.maps.plugin.animation.CameraAnimatorsFactory$getFlyTo$animators$2.evaluate(CameraAnimatorsFactory.kt:27)
    at android.animation.KeyframeSet.getValue(KeyframeSet.java:202)
    at android.animation.PropertyValuesHolder.calculateValue(PropertyValuesHolder.java:1017)
    at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1561)
    at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:692)
    at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:655)
    at android.animation.ValueAnimator.start(ValueAnimator.java:1087)
    at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
    at com.mapbox.maps.plugin.animation.animator.CameraAnimator.start(CameraAnimator.kt:88)
    at android.animation.ValueAnimator.startWithoutPulsing(ValueAnimator.java:1099)
    at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1149)
    at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1234)
    at android.animation.AnimatorSet.start(AnimatorSet.java:729)
    at android.animation.AnimatorSet.start(AnimatorSet.java:684)
    at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.startAnimatorSet(CameraAnimationsPluginImpl.kt:338)
    at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.flyTo(CameraAnimationsPluginImpl.kt:699)
```

To reproduce, run:
```kotlin
mapView.getCameraAnimationsPlugin().flyTo(
    CameraOptions.Builder()
        .center(Point.fromLngLat(1.0, 1.0))
        .padding(getSinglePixelEdgeInsets(mapboxMap.getSize()))
        .bearing(0.0)
        .zoom(14.0)
        .pitch(0.0)
        .build(),
    MapAnimationOptions.mapAnimationOptions {
        duration = 1500
    }
)
```
where `getSinglePixelEdgeInsets` is:
```kotlin
fun getSinglePixelEdgeInsets(mapSize: Size): EdgeInsets {
    val point = ScreenCoordinate(
        mapSize.width.toDouble() / 2.0,
        mapSize.height.toDouble() / 2.0
    )
    return EdgeInsets(point.y, point.x, mapSize.height - point.y, mapSize.width - point.x)
}
```

/cc @mapbox/maps-android

**Comment by kiryldz** [comment]
@LukasPaczos thanks for reporting and for code leading to a crash, it will be very helpful.
What's the priority from your side and is there some workaround you may use?

**Comment by LukasPaczos** [comment]
@kiryldz this shouldn't be a blocker for now, workarounds are:
- explicitly provide new padding value:
```kotlin
mapView.getCameraAnimationsPlugin().flyTo(
    CameraOptions.Builder()
        .padding(EdgeInsets(0.0, 0.0, 0.0, 0.0))
        .center(center)
        .bearing(0.0)
        .zoom(14.0)
        .pitch(0.0)
        .build(),
    MapAnimationOptions.mapAnimationOptions {
        duration(1500)
    }
)
```
- use `easeTo` instead
