### ISSUE TITLE
java.lang.UnsatisfiedLinkError: 'void com.mapbox.maps.assets.AssetManagerProvider.initialize(android.content.res.AssetManager)'

### ISSUE THREAD

**Issue by johnnyzen** [mapbox/mapbox-maps-android#1788]
Android Studio: 2021.3.1 Patch 1
Mapbox: implementation 'com.mapbox.maps:android:10.9.0'

Getting error in preview layout window of android studio:

`java.lang.UnsatisfiedLinkError: 'void com.mapbox.maps.assets.AssetManagerProvider.initialize(android.content.res.AssetManager)'
	at com.mapbox.maps.assets.AssetManagerProvider.initialize(Native Method)
	at com.mapbox.maps.MapController.<init>(MapController.kt:62)
	at com.mapbox.maps.MapView.<init>(MapView.kt:101)
	at com.mapbox.maps.MapView.<init>(MapView.kt:70)
	at com.mapbox.maps.MapView.<init>(MapView.kt:64)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:351)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:200)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:161)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:359)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

Cant seem to resolve, anyone else having same issue?

**Comment by ZiZasaurus** [comment]
@johnnyzen thank you for reporting. To better assist you, can you please let us know what's happening in the app or what actions you're taking, if any, before the error is thrown?

**Comment by johnnyzen** [comment]
Hi @ZiZasaurus 

Sure, everything is working in the app when built, its just the preview layout in Android Studio not rendering with the error posted previously.

If I remove the layout:

`<com.mapbox.maps.MapView
        android:id="@+id/map_view"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginTop="8dp"
        app:layout_constraintTop_toBottomOf="@+id/map_view_button"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        mapbox:mapbox_cameraZoom="13.448986053466797" />`

Android studio displays the layout.

I have created a new layout with just the mapview within a ConstraintLayout with same issue.

Hope this helps.

**Comment by ZiZasaurus** [comment]
@johnnyzen thank you for reaching out, It seems like there may be a mismatch between (or inability to load) the native libraries. 

To better assist you, can you provide your android manifest?

**Comment by johnnyzen** [comment]
Here is my manifest:

`
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

    <uses-permission
        android:name="android.permission.BLUETOOTH"
        android:maxSdkVersion="30" />
    <uses-permission
        android:name="android.permission.BLUETOOTH_ADMIN"
        android:maxSdkVersion="30" />

    
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT"
        tools:targetApi="s" />
    <uses-permission
        android:name="android.permission.BLUETOOTH_SCAN"
        android:usesPermissionFlags="neverForLocation"
        tools:targetApi="s" />

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

    
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

    <uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
    <uses-feature android:name="android.hardware.bluetooth" android:required="true"/>

    <application
        android:name=".MainApplication"
        android:allowBackup="true"
        android:dataExtractionRules="@xml/data_extraction_rules"
        android:fullBackupContent="@xml/backup_rules"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.Green"
        android:hardwareAccelerated="true"
        tools:targetApi="31">

        <activity
            android:name=".ui.login.LoginActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity
            android:name=".MainActivity"
            android:exported="true"/>

        <provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="${applicationId}.androidx-startup"
            android:exported="false"
            tools:node="merge">
            <meta-data
                android:name="com.initializer.to.be.removed"
                android:value="androidx.startup"
                tools:node="remove" />
        </provider>

    </application>

</manifest>
`

**Comment by hotellinawebmaster** [comment]
Hello, I have the same error.
![image](https://user-images.githubusercontent.com/73776127/202359961-293a3468-6b73-41db-946f-6214cea116e5.png)

java.lang.UnsatisfiedLinkError: 'void com.mapbox.maps.assets.AssetManagerProvider.initialize(android.content.res.AssetManager)'
	at com.mapbox.maps.assets.AssetManagerProvider.initialize(Native Method)
	at com.mapbox.maps.MapController.<init>(MapController.kt:62)
	at com.mapbox.maps.MapView.<init>(MapView.kt:101)
	at com.mapbox.maps.MapView.<init>(MapView.kt:70)
	at com.mapbox.maps.MapView.<init>(MapView.kt:64)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:351)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:200)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:161)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:359)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Julius-Babies** [comment]
I am havin the exakt same issue with a fresh application. Whenever I add a MapView the preview goes blank and I'm getting this error. Is there an older version we can use until this error is fixed?

**Comment by hotellinawebmaster** [comment]
I believe this has never been fixed, as I never saw on Internet examples showing a preview in Android Studio.

**Comment by Julius-Babies** [comment]
But that's not very handy because you must remove the view whenever you want to edit the layout file. [This solution](https://stackoverflow.com/a/27568606/16682019) sadly doesn't work.

**Comment by Julius-Babies** [comment]
Maybe useful for the developers: 
![View.isInEditMode()](https://user-images.githubusercontent.com/66371497/204107163-883a104b-be77-48e2-a051-18749d5e3d2d.png)

**Comment by kiryldz** [comment]
Thanks for heads up, will be fixed in `v10.10.0` version available next week.

**Comment by johnnyzen** [comment]
@kiryldz Thank you Sir. Much respect.
