### ISSUE TITLE
Robo crash: terminating with uncaught exception of type jni::PendingJavaException

### ISSUE THREAD

**Issue by kiryldz** [mapbox/mapbox-maps-android#186]
## Environment

- Android OS version: 28
- Devices affected: Pixel
- Maps SDK Version: v10.0.0-beta.15

## Observed behavior and steps to reproduce

https://console.firebase.google.com/u/0/project/mapbox-maps-android/testlab/histories/bh.2bfab35e2b9f8cf5/matrices/8989864525422661528/executions/bs.6891195bb7d3ac7b/issues

## Expected behavior

No crash

**Comment by SamuelBrucksch** [comment]
Some additional information: This seems to happen when app comes back from background. And it's an AA app that uses MapSurface.

**Comment by kiryldz** [comment]
@SamuelBrucksch I've symbolicated your trace, crash happens somewhere in [Observer](https://docs.mapbox.com/android/maps/api/10.0.0/mapbox-maps-android/com.mapbox.maps/-observer(android-jvm)/). It means that `notify` is called, some Java exception happens in function body, then gets re-throwed and is followed by actually native crash you reported. 
Do you have your own observers in code?
Something similar to [this](https://github.com/mapbox/mapbox-maps-android/blob/fcf311159c2a54f3d162ca99738b1420fbce0272/app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt#L55).

**Comment by SamuelBrucksch** [comment]
No i do not use `subscribe`. But i use `addOnCameraChangeListener`, `addOnStyleImageMissingListener` and `addOnStyleLoadedListener` if that is somehow related.

**Comment by kiryldz** [comment]
@SamuelBrucksch I indeed do not see Java exception before actual crash so hard to say what did happen. However I did verify that if some exception does happen - it should be in logs, e.g. I've explicitly accessed array element that is out of bounds inside `MapboxMap.addOnMapIdleListener { ... }`and got following logs on crash:
```
2021-10-13 11:36:58.227 13033-13033/com.mapbox.studio E/KIRYLDD: CRASH
2021-10-13 11:36:58.228 13033-13033/com.mapbox.studio W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=1; index=2
2021-10-13 11:36:58.228 13033-13033/com.mapbox.studio W/System.err:     at com.mapbox.studio.singlemap.SingleMapActivity.d0(:156)
2021-10-13 11:36:58.228 13033-13033/com.mapbox.studio W/System.err:     at com.mapbox.studio.singlemap.c.onMapIdle(Unknown Source:0)
2021-10-13 11:36:58.228 13033-13033/com.mapbox.studio W/System.err:     at com.mapbox.maps.NativeObserver.notify(:47)
2021-10-13 11:36:58.229 13033-13033/com.mapbox.studio W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2021-10-13 11:36:58.229 13033-13033/com.mapbox.studio W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:335)
2021-10-13 11:36:58.229 13033-13033/com.mapbox.studio W/System.err:     at android.os.Looper.loop(Looper.java:206)
2021-10-13 11:36:58.229 13033-13033/com.mapbox.studio W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8595)
2021-10-13 11:36:58.229 13033-13033/com.mapbox.studio W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-10-13 11:36:58.229 13033-13033/com.mapbox.studio W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
2021-10-13 11:36:58.229 13033-13033/com.mapbox.studio W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-10-13 11:36:58.250 13033-13033/com.mapbox.studio E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException
    
    --------- beginning of crash
2021-10-13 11:36:58.250 13033-13033/com.mapbox.studio A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 13033 (m.mapbox.studio), pid 13033 (m.mapbox.studio)
2021-10-13 11:36:58.359 19248-19248/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2021-10-13 11:36:58.359 19248-19248/? A/DEBUG: Build fingerprint: 'samsung/z3sxeea/z3s:11/RP1A.200720.012/G988BXXSADUH5:user/release-keys'
2021-10-13 11:36:58.359 19248-19248/? A/DEBUG: Revision: '23'
2021-10-13 11:36:58.359 19248-19248/? A/DEBUG: ABI: 'arm64'
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG: Timestamp: 2021-10-13 11:36:58+0300
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG: pid: 13033, tid: 13033, name: m.mapbox.studio  >>> com.mapbox.studio <<<
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG: uid: 10430
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG: Abort message: 'terminating with uncaught exception of type jni::PendingJavaException'
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG:     x0  0000000000000000  x1  00000000000032e9  x2  0000000000000006  x3  0000007fe833f8a0
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG:     x4  fefeff6d6e68736f  x5  fefeff6d6e68736f  x6  fefeff6d6e68736f  x7  7f7f7f7f7f7f7f7f
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG:     x8  00000000000000f0  x9  ca8f016ad01f1b20  x10 0000000000000000  x11 ffffffc0fffffbdf
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG:     x12 0000000000000001  x13 0000000061669aaa  x14 000e9fa5af92fc10  x15 00004e92ef12bfda
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG:     x16 000000770da52c80  x17 000000770da34d50  x18 0000007712ec2000  x19 00000000000032e9
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG:     x20 00000000000032e9  x21 00000000ffffffff  x22 ffffff80ffffffc8  x23 0000007fe833faf0
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG:     x24 0000007fe833f9d0  x25 0000007fe833fa10  x26 000000af08631c03  x27 00000000000003e8
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG:     x28 00000074cbc82ef0  x29 0000007fe833f920
2021-10-13 11:36:58.360 19248-19248/? A/DEBUG:     lr  000000770d9e8724  sp  0000007fe833f880  pc  000000770d9e8750  pst 0000000000000000
```

Another thing that comes to my mind is that if I understand correctly you're using our SDK with AA, I'm not that familiar with lifecycle there, perhaps you may want to exclude our Mapbox lifecycle plugin and call `MapView.onStart`, `MapView.onStop`, `MapView.onDestroy` and `MapView.onLowMemory` manually when needed (if that makes any sense).

**Comment by SamuelBrucksch** [comment]
Hi,

yes i use it on AA. How do i exclude the Mapbox Lifecycle Plugin? I actually call onStart and the others already.

We use the map surface and initialize it like this:
```
private final SurfaceCallback mSurfaceCallback = new SurfaceCallback() {

        @Override
        public void onSurfaceAvailable(@NonNull SurfaceContainer surfaceContainer) {
            synchronized (MapRenderer.this) {
                if (surfaceContainer.getSurface() == null)
                    return;

                MapInitOptions options = new MapInitOptions(mCarContext,
                        resourceOptions,
                        new MapOptions.Builder().build(),
                        Arrays.asList(new Plugin.Mapbox(Plugin.MAPBOX_CAMERA_PLUGIN_ID)),
                        currentCamera.build(),
                        false,
                        savedStyle,
                        null);

                Surface s = surfaceContainer.getSurface();
                mapSurface = new MapSurface(mCarContext, s, options);
                mapSurface.setMaximumFps(30);
                mapboxMap = mapSurface.getMapboxMap();
                RenderCacheOptions renderCacheOptions = new RenderCacheOptions.Builder().size(64).build();
                mapboxMap.setRenderCacheOptions(renderCacheOptions);

                cameraAnimations = CameraAnimationsUtils.getCamera(mapSurface);

                mapSurface.surfaceCreated();
                mapSurface.surfaceChanged(width, height);
               
                mapboxMap.addOnCameraChangeListener((eventData) -> {
                    onCameraChanged();
                });
        }

        @Override
        public void onVisibleAreaChanged(@NonNull Rect visibleArea) {
        }

        @Override
        public void onStableAreaChanged(@NonNull Rect stableArea) {
        }

        @Override
        public void onSurfaceDestroyed(@NonNull SurfaceContainer surfaceContainer) {
            synchronized (MapRenderer.this) {
                mapboxMap.removeOnCameraChangeListener(this::onCameraChanged);
                mapSurface.surfaceDestroyed();
            }
        }
}
```
So every time the surface is recreated (for example when going into background and coming back) a new MapSurface and so on is generated and filled again with the previous data.

**Comment by SamuelBrucksch** [comment]
Yes it is the same.

**Comment by kiryldz** [comment]
> So do you think it could be an Exception somewhere in `addOnCameraChangeListener`, `addOnStyleImageMissingListener ` or `addOnStyleLoadedListener`? Should i wrap those with a try/catch with additional logging and see if that error still comes?

You could try it. Guess it should help however it would be very useful if you could also somehow report actual exception text when you catch it.

**Comment by pengdev** [comment]
Hi @SamuelBrucksch you could reference to the Android Auto integration in our navigation example app in https://github.com/mapbox/mapbox-navigation-android-examples/blob/main/android-auto/src/main/java/com/mapbox/androidauto/car/map/CarMapSurfaceLifecycle.kt. We were iterating Android Auto solution together with our navigation team, so the latest Android Auto example are updated there, and eventually the changes there will be ported back to the Maps SDK later when it's matured.

As for the lifecycle of the Android Auto, the MapSurface's lifecycle should purely dependent on the SurfaceCallback. The lifecycle of Session is different from MapSurface and shouldn't be tied together.

```
override fun onSurfaceAvailable(surfaceContainer: SurfaceContainer) {
    val mapSurface = MapSurface(carContext, it, mapInitOptions)
    mapSurface.onStart()
    mapSurface.surfaceCreated()
}
override fun onSurfaceDestroyed(surfaceContainer: SurfaceContainer) {
    mapSurface?.onStop()
    mapSurface?.surfaceDestroyed()
    mapSurface?.onDestroy()
}
```

**Comment by kmadsen** [comment]
Is this issue still happening or can it be closed?

**Comment by SamuelBrucksch** [comment]
The lifetime issue is fixed by google and I think i did not see the other issue anymore.

**Comment by SamuelBrucksch** [comment]
Thanks @tobrun , guess this makes finding problems in listener code much easier now.
