### ISSUE TITLE
Moving Exception

### ISSUE THREAD

**Issue by lantah-1** [mapbox/mapbox-maps-android#1992]
## Environment

- Android OS version: Android 12, HarmonyOS
- Devices affected: Huawei mate 30 5G
- Maps SDK Version: 10.10.1

## Observed behavior and steps to reproduce

`
crash_message -> PlatformException(error, Attempt to invoke virtual method 'void com.mapbox.android.gestures.MoveDistancesObject.addNewPosition(float, float)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.android.gestures.MoveDistancesObject.addNewPosition(float, float)' on a null object reference
	at com.mapbox.android.gestures.MoveGestureDetector.updateMoveDistancesObjects(MoveGestureDetector.java:172)
	at com.mapbox.android.gestures.MoveGestureDetector.analyzeMovement(MoveGestureDetector.java:147)
	at com.mapbox.android.gestures.MultiFingerGesture.analyzeEvent(MultiFingerGesture.java:106)
	at com.mapbox.android.gestures.ProgressiveGesture.analyzeEvent(ProgressiveGesture.java:55)
	at com.mapbox.android.gestures.MoveGestureDetector.analyzeEvent(MoveGestureDetector.java:141)
	at com.mapbox.android.gestures.BaseGesture.analyze(BaseGesture.java:61)
	at com.mapbox.android.gestures.BaseGesture.onTouchEvent(BaseGesture.java:39)
	at com.mapbox.
`

**Comment by ank27** [comment]
@lantah-1 Does this crash a recurring one or happen sporadically?

**Comment by kiryldz** [comment]
Closing due to inactivity.
