### ISSUE TITLE
SDK incompatible with Android 14

### ISSUE THREAD

**Issue by seventhmoon** [mapbox/mapbox-maps-android#2059]
App using mapboxsdk will crash on Android 14 as an Exception was thrown.

```
java.lang.IllegalArgumentException: latitude must not be NaN
        at com.mapbox.mapboxsdk.geometry.LatLng.f(SourceFile:5)
        at com.mapbox.mapboxsdk.location.e.a(SourceFile:3)
        at com.mapbox.mapboxsdk.location.e.evaluate(SourceFile:1)
        at android.animation.KeyframeSet.getValue(KeyframeSet.java:202)
        at android.animation.PropertyValuesHolder.calculateValue(PropertyValuesHolder.java:1017)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1698)
        at android.animation.ValueAnimator.animateValuesInRange(ValueAnimator.java:1512)
        at android.animation.AnimatorSet.animateValuesInRange(AnimatorSet.java:1025)
        at android.animation.AnimatorSet.animateBasedOnPlayTime(AnimatorSet.java:883)
        at android.animation.AnimatorSet.initChildren(AnimatorSet.java:1164)
        at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1384)
        at android.animation.AnimatorSet.start(AnimatorSet.java:741)
        at android.animation.AnimatorSet.start(AnimatorSet.java:696)
        at com.mapbox.mapboxsdk.location.t.b(SourceFile:5)
        at com.mapbox.mapboxsdk.location.i.t(SourceFile:5)
        at com.mapbox.mapboxsdk.location.i.m(SourceFile:25)
        at com.mapbox.mapboxsdk.location.k.d0(SourceFile:13)
        at com.mapbox.mapboxsdk.location.k.c0(SourceFile:4)
        at com.mapbox.mapboxsdk.location.k.b(SourceFile:1)
        at com.mapbox.mapboxsdk.location.k$o.a(SourceFile:2)
        at com.mapbox.mapboxsdk.location.k$o.onSuccess(SourceFile:1)
        at k9.b$a.a(SourceFile:3)
        at k9.b$a.onSuccess(SourceFile:1)
        at com.google.android.gms.tasks.zzm.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:958)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:205)
        at android.os.Looper.loop(Looper.java:294)
        at android.app.ActivityThread.main(ActivityThread.java:8180)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
```

**Comment by jush** [comment]
Thanks for your report. 

A couple of comments:
1. What Mapbox version are you using?
2. Please try to reproduce with the latest release available
3. The issue doesn't seem to relate to only Android 14. Are you seeing it only in Android 14 but not on other Android releases?
4. Do you have some steps to reproduce it?

**Comment by seventhmoon** [comment]
I am not using Mapbox directly, so I don't know which version is affected.

There are apps using Mapbox crashing, e.g. [Toyota](https://play.google.com/store/apps/details?id=com.toyota.oneapp),[Aimo Share](https://play.google.com/store/apps/details?id=com.vulog.carshare.aimo), [SiteSeeker Campsite Finder](https://play.google.com/store/apps/details?id=com.sixvoices.siteseeker), [Revel](https://play.google.com/store/apps/details?id=com.reveltransit), [Bonjour RATP](https://play.google.com/store/apps/details?id=com.fabernovel.ratp) which the crash logs are similar. And it is only reproducible on Android 14 by opening the app.

**Comment by kiryldz** [comment]
Package `com.mapbox.mapboxsdk` indicates that it relates to [Maps v9](https://github.com/mapbox/mapbox-gl-native-android) while this repo is for Maps v10.

**Comment by seventhmoon** [comment]
> I tried our test application in an Android 14 and it works properly.
May I have the test APK to test on my side also?

> Package `com.mapbox.mapboxsdk` indicates that it relates to [Maps v9](https://github.com/mapbox/mapbox-gl-native-android) while this repo is for Maps v10.
Is there a test APK with v9 to test?

**Comment by zenyagami** [comment]
Seems that is happening in Mapbox map sdk 9.6.x to 9.7.1, It crash in Android 13 TQ2A (Pixel phone) or Android 14.
the problem is onStart call this is the whole stack trace
```
  java.lang.IllegalArgumentException: latitude must not be NaN
                                                                                                    	at com.mapbox.mapboxsdk.geometry.LatLng.setLatitude(LatLng.java:129)
                                                                                                    	at com.mapbox.mapboxsdk.location.LatLngEvaluator.evaluate(LatLngEvaluator.java:15)
                                                                                                    	at com.mapbox.mapboxsdk.location.LatLngEvaluator.evaluate(LatLngEvaluator.java:8)
                                                                                                    	at android.animation.KeyframeSet.getValue(KeyframeSet.java:202)
                                                                                                    	at android.animation.PropertyValuesHolder.calculateValue(PropertyValuesHolder.java:1017)
                                                                                                    	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1698)
                                                                                                    	at android.animation.ValueAnimator.animateValuesInRange(ValueAnimator.java:1512)
                                                                                                    	at android.animation.AnimatorSet.animateValuesInRange(AnimatorSet.java:1025)
                                                                                                    	at android.animation.AnimatorSet.animateBasedOnPlayTime(AnimatorSet.java:883)
                                                                                                    	at android.animation.AnimatorSet.initChildren(AnimatorSet.java:1164)
                                                                                                    	at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1384)
                                                                                                    	at android.animation.AnimatorSet.start(AnimatorSet.java:741)
                                                                                                    	at android.animation.AnimatorSet.start(AnimatorSet.java:696)
                                                                                                    	at com.mapbox.mapboxsdk.location.MapboxAnimatorSetProvider.startAnimation(MapboxAnimatorSetProvider.java:31)
                                                                                                    	at com.mapbox.mapboxsdk.location.LocationAnimatorCoordinator.playAnimators(LocationAnimatorCoordinator.java:383)
                                                                                                    	at com.mapbox.mapboxsdk.location.LocationAnimatorCoordinator.feedNewLocation(LocationAnimatorCoordinator.java:140)
                                                                                                    	at com.mapbox.mapboxsdk.location.LocationComponent.updateLocation(LocationComponent.java:1622)
                                                                                                    	at com.mapbox.mapboxsdk.location.LocationComponent.updateLocation(LocationComponent.java:1593)
                                                                                                    	at com.mapbox.mapboxsdk.location.LocationComponent.setLastLocation(LocationComponent.java:1663)
                                                                                                    	at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1451)
                                                                                                    	at com.mapbox.mapboxsdk.location.LocationComponent.onStart(LocationComponent.java:1377)
                                                                                                    	at com.mapbox.mapboxsdk.maps.MapboxMap.onStart(MapboxMap.java:149)
                                                                                                    	at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:397)
                                                                                                    	at app.ui.main.maps.mapsv3.MapboxMapFragment.onStart(MapboxMapFragment.kt:224)
                                                                                                    	at androidx.fragment.app.Fragment.performStart(Fragment.java:3162)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:588)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1435)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2979)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2904)
                                                                                                    	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:274)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:359)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
                                                                                                    	at app.ui.main.MainActivity.onStart(MainActivity.kt:273)
                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1581)
                                                                                                    	at android.app.Activity.performStart(Activity.java:8628)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3798)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2436)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8180)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
2023-04-14 21:04:16.173 15810-15810 AndroidRuntime          com.mytestapp.debug            E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
```

it happens after the app is in background and comes to the foreground, since is skd 9.x I'm not sure if mapbox will solve this :/

**Comment by zenyagami** [comment]
I found the issue, the problem is that in the `LatLngEvaluator` class the fraction is NaN (I'm not sure why) my suggestion to fix this I would suggest from

```java
@NonNull
  @Override
  public LatLng evaluate(float fraction, @NonNull LatLng startValue, @NonNull LatLng endValue) {
    latLng.setLatitude(startValue.getLatitude()
      + ((endValue.getLatitude() - startValue.getLatitude()) * fraction));
    latLng.setLongitude(startValue.getLongitude()
      + ((endValue.getLongitude() - startValue.getLongitude()) * fraction));
    return latLng;
  }

```
to

```java
@NonNull
  @Override
  public LatLng evaluate(float fraction, @NonNull LatLng startValue, @NonNull LatLng endValue) {
fraction = Double.isNaN(fraction) ? 0f : fraction;
    latLng.setLatitude(startValue.getLatitude()
      + ((endValue.getLatitude() - startValue.getLatitude()) * fraction));
    latLng.setLongitude(startValue.getLongitude()
      + ((endValue.getLongitude() - startValue.getLongitude()) * fraction));
    return latLng;
  }

```
so basically I'm adding `fraction = Double.isNaN(fraction) ? 0f : fraction;` is possible to be implemented? or if I create a PR can be merged? or any other suggestion?  @kiryldz @jush 
Thanks

**Comment by zenyagami** [comment]
I Created a PR [https://github.com/mapbox/mapbox-gl-native-android/pull/747](url) , would be great if we can merge this and create a new release.

**Comment by JDM8** [comment]
> Package `com.mapbox.mapboxsdk` indicates that it relates to [Maps v9](https://github.com/mapbox/mapbox-gl-native-android) while this repo is for Maps v10.

A fix for v9 would be greatly appreciated, as currently anything built with v9 will crash on Android 14.

**Comment by hanis0** [comment]
I've run into this issue today. It really seems to be Android 14 related. I've managed to create a small demo app that shows the difference and [reported it to Google](https://issuetracker.google.com/issues/280660517). Let's see if they consider it a bug or a feature.
