### ISSUE TITLE
IllegalArgumentException kotlin.math.MathKt__MathJVMKt in roundToInt

### ISSUE THREAD

**Issue by pizzacoffeecode** [mapbox/mapbox-maps-android#2074]
## Environment

- Android OS version: 11
- Devices affected: OnePlusPro8
- Maps SDK Version: 10.11.2

## Observed behavior and steps to reproduce

Unknown

## Expected behavior

App not to crash

## Notes / preliminary analysis

There are no references to custom code in error logs, all looks related to mapbox.

## Additional links and references

`kotlin.math.MathKt__MathJVMKt in roundToInt at line 619

com.mapbox.maps.plugin.viewport.transition.TransitionUtilsKt in roundTo at line 46

com.mapbox.maps.plugin.viewport.transition.TransitionUtilsKt in normalizeBearing at line 37

com.mapbox.maps.plugin.viewport.transition.MapboxViewportTransitionFactory in transitionFromLowZoomToHighZoom at line 72

com.mapbox.maps.plugin.viewport.transition.DefaultViewportTransitionImpl in createAnimatorSet at line 137

com.mapbox.maps.plugin.viewport.transition.DefaultViewportTransitionImpl in run$lambda-3 at line 68

com.mapbox.maps.plugin.viewport.transition.DefaultViewportTransitionImpl in $r8$lambda$Dm5KN4W8ZFs-jPnk6TvM6D2XbLA

com.mapbox.maps.plugin.viewport.transition.DefaultViewportTransitionImpl$$ExternalSyntheticLambda1 in onNewData at line 15

com.mapbox.maps.plugin.viewport.state.FollowPuckViewportStateImpl in notifyViewportStateDataObserver at line 81

com.mapbox.maps.plugin.viewport.state.FollowPuckViewportStateImpl in notifyLatestViewportData at line 69

com.mapbox.maps.plugin.viewport.state.FollowPuckViewportStateImpl in indicatorPositionChangedListener$lambda-0 at line 51

com.mapbox.maps.plugin.viewport.state.FollowPuckViewportStateImpl in $r8$lambda$1FFQMeE76PqUckIDkzhBjeBUQTc

com.mapbox.maps.plugin.viewport.state.FollowPuckViewportStateImpl$$ExternalSyntheticLambda2 in onIndicatorPositionChanged at line 2

com.mapbox.maps.plugin.locationcomponent.LocationComponentPluginImpl in indicatorPositionChangedListener$lambda-1 at line 81

com.mapbox.maps.plugin.locationcomponent.LocationComponentPluginImpl in $r8$lambda$tH84PKxP_CGg6Eh9PozddvGFbNI

com.mapbox.maps.plugin.locationcomponent.LocationComponentPluginImpl$$ExternalSyntheticLambda3 in onIndicatorPositionChanged at line 2

com.mapbox.maps.plugin.locationcomponent.animators.PuckPositionAnimator in updateLayer at line 10

com.mapbox.maps.plugin.locationcomponent.animators.PuckPositionAnimator in updateLayer at line 6

com.mapbox.maps.plugin.locationcomponent.animators.PuckAnimator$1$1 in invoke at line 36

com.mapbox.maps.plugin.locationcomponent.animators.PuckAnimator$1$1 in invoke at line 33

com.mapbox.maps.threading.AnimationThreadController in postOnMainThread at line 67

com.mapbox.maps.plugin.locationcomponent.animators.PuckAnimator in _init_$lambda-0 at line 33

com.mapbox.maps.plugin.locationcomponent.animators.PuckAnimator in $r8$lambda$DKuRutUBCyf6yKd5UEMf-U8meWw

com.mapbox.maps.plugin.locationcomponent.animators.PuckAnimator$$ExternalSyntheticLambda0 in onAnimationUpdate at line 2

android.animation.ValueAnimator in animateValue at line 1566

android.animation.ValueAnimator in animateBasedOnTime at line 1357

android.animation.ValueAnimator in doAnimationFrame at line 1489

android.animation.AnimationHandler in doAnimationFrame at line 146

android.animation.AnimationHandler in access$100 at line 37

android.animation.AnimationHandler$1 in doFrame at line 54

android.view.Choreographer$CallbackRecord in run at line 970

android.view.Choreographer in doCallbacks at line 796

android.view.Choreographer in doFrame at line 727

android.view.Choreographer$FrameDisplayEventReceiver in run at line 957

android.os.Handler in handleCallback at line 938

android.os.Handler in dispatchMessage at line 99

android.os.Looper in loop at line 223

android.app.ActivityThread in main at line 7680

java.lang.reflect.Method in invoke

com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 592

com.android.internal.os.ZygoteInit in main at line 947`

**Comment by ignaciotcrespo** [comment]
hi, I still have this issue in my app, reported in firebase, it is causing some crashes. Any news about it?

**Comment by anisart** [comment]
Same on OnePlus8Pro with Android 11 in first minutes after submit app update in Google Play console. Seems like it's auto-testing device.
```
          Fatal Exception: java.lang.IllegalArgumentException: Cannot round NaN value.
       at kotlin.math.MathKt__MathJVMKt.roundToInt(MathKt__MathJVM.kt:619)
       at com.mapbox.maps.plugin.viewport.transition.TransitionUtilsKt.roundTo(TransitionUtils.kt:46)
       at com.mapbox.maps.plugin.viewport.transition.TransitionUtilsKt.normalizeBearing(TransitionUtils.kt:37)
       at com.mapbox.maps.plugin.viewport.transition.MapboxViewportTransitionFactory.transitionFromLowZoomToHighZoom(MapboxViewportTransitionFactory.java:74)
       at com.mapbox.maps.plugin.viewport.transition.DefaultViewportTransitionImpl.createAnimatorSet(DefaultViewportTransitionImpl.java:140)
       at com.mapbox.maps.plugin.viewport.transition.DefaultViewportTransitionImpl.run$lambda$3(DefaultViewportTransitionImpl.java:71)
       at com.mapbox.maps.plugin.viewport.state.FollowPuckViewportStateImpl.notifyViewportStateDataObserver(FollowPuckViewportStateImpl.kt:94)
       at com.mapbox.maps.plugin.viewport.state.FollowPuckViewportStateImpl.observeDataSource(FollowPuckViewportStateImpl.kt:152)
       at com.mapbox.maps.plugin.viewport.transition.DefaultViewportTransitionImpl.run(DefaultViewportTransitionImpl.kt:65)
       at com.mapbox.maps.plugin.viewport.ViewportPluginImpl.transitionTo(ViewportPluginImpl.kt:154)
       at com.mapbox.maps.extension.compose.animation.viewport.MapViewportState$transitionToFollowPuckState$1.invoke(MapViewportState.java:335)
       at com.mapbox.maps.extension.compose.animation.viewport.MapViewportState$transitionToFollowPuckState$1.invoke(MapViewportState.java:333)
       at com.mapbox.maps.extension.compose.animation.viewport.MapViewportState$DrainActionQueue$1.invokeSuspend(MapViewportState.kt:117)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:79)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by yterletskyi** [comment]
any updates on this please?
