### ISSUE TITLE
Help : Execution failed for task ':sdk-base:compilePrivateReleaseKotlin'.

### ISSUE THREAD

**Issue by hanjn1987** [mapbox/mapbox-maps-android#2094]
When I checkout this project, then follow the DEVELOPING.md to do make:
```
$ make sdk-build
```
I see the error message:

```
> Task :module-telemetry:kaptGenerateStubsPublicReleaseKotlin FAILED
e: java.lang.IllegalAccessError: class org.jetbrains.kotlin.kapt3.base.KaptContext (in unnamed module @0x544becf8) cannot access class com.sun.tools.javac.util.Context (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x544becf8
        at org.jetbrains.kotlin.kapt3.base.KaptContext.<init>(KaptContext.kt:28)
        at org.jetbrains.kotlin.kapt3.KaptContextForStubGeneration.<init>(KaptContextForStubGeneration.kt:40)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.contextForStubGeneration(Kapt3Extension.kt:287)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:171)
        at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:102)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$invokeExtensionsOnAnalysisComplete(TopDownAnalyzerFacadeForJVM.kt:112)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:122)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:86)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:252)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:243)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:243)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:90)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:56)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:412)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:112)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:358)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:300)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl$rebuild(IncrementalCompilerRunner.kt:119)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:170)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:81)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:607)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:96)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1658)
        at jdk.internal.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)






<======-------> 50% EXECUTING [4s]> :plugin-overlay:mergePrivateReleaseResources> :plugin-logo:mergePrivateReleaseResources> :sdk-base:compilePrivateReleaseKotlin> :plugin-animation:mergePublicReleaseResources<======-------> 50% EXECUTING [5s]
> Task :sdk-base:compilePrivateReleaseKotlin FAILED
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/attribution/AttributionPlugin.kt: (5, 43): Unresolved reference: generated
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/attribution/AttributionPlugin.kt: (11, 60): Unresolved reference: AttributionSettingsInterface
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/compass/CompassPlugin.kt: (6, 39): Unresolved reference: generated
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/compass/CompassPlugin.kt: (11, 73): Unresolved reference: CompassSettingsInterface
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPlugin.kt: (10, 40): Unresolved reference: generated
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPlugin.kt: (15, 69): Unresolved reference: GesturesSettingsInterface
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPlugin.kt: (5, 49): Unresolved reference: generated
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPlugin.kt: (15, 3): Unresolved reference: LocationComponentSettingsInterface
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPlugin2.kt: (3, 49): Unresolved reference: generated
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPlugin2.kt: (8, 63): Unresolved reference: LocationComponentSettingsInterface2
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/logo/LogoPlugin.kt: (4, 36): Unresolved reference: generated
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/logo/LogoPlugin.kt: (9, 36): Unresolved reference: LogoSettingsInterface
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBar.kt: (3, 40): Unresolved reference: generated
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBar.kt: (22, 17): Unresolved reference: ScaleBarSettings
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPlugin.kt: (5, 40): Unresolved reference: generated
e: /Users/hanjn/Dev/learnspace/mapbox-maps-android/sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPlugin.kt: (10, 55): Unresolved reference: ScaleBarSettingsInterface





<======-------> 50% EXECUTING [5s]> :plugin-overlay:mergePrivateReleaseResources> :plugin-logo:mergePrivateReleaseResources> :extension-localization:verifyPublicReleaseResources> :plugin-animation:mergePublicReleaseResources<======-------> 50% EXECUTING [6s]> IDLE> IDLE<======-------> 51% EXECUTING [6s]> IDLE<======-------> 51% EXECUTING [7s]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':module-telemetry:kaptGenerateStubsPublicReleaseKotlin'.
> Internal compiler error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':sdk-base:compilePrivateReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
405 actionable tasks: 68 executed, 337 up-to-date
```

Thanks for your help!

**Comment by okcoker** [comment]
@hanjn1987 how did you fix this?
