### ISSUE TITLE
Sporadic Crashlytics crash: java.lang.ClassNotFoundException: com.mapbox.maps.loader.MapboxMapsInitializer

### ISSUE THREAD

**Issue by hanna-h** [mapbox/mapbox-maps-android#2171]
## Environment

- Android OS version: 10
- Devices affected: 60% Samsung, 20% Motorola, 20% Xiaomi
- Maps SDK Version: 10.15.1

## Observed behavior and steps to reproduce

Sporadic background crash reported in crashlytics.

## Expected behavior
No crash.

## Notes / preliminary analysis
According to crashlytics the app is always in the background when this crash happens.

## Additional links and references

Stacktrace:

```
Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.ClassNotFoundException: com.mapbox.maps.loader.MapboxMapsInitializer
       at android.app.ActivityThread.installProvider(ActivityThread.java:7769)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7309)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7166)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
       at android.app.ActivityThread.access$1600(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

Caused by androidx.startup.StartupException: java.lang.ClassNotFoundException: com.mapbox.maps.loader.MapboxMapsInitializer
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:242)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2113)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2087)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7764)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7309)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7166)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
       at android.app.ActivityThread.access$1600(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

Caused by java.lang.ClassNotFoundException: com.mapbox.maps.loader.MapboxMapsInitializer
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:454)
       at java.lang.Class.forName(Class.java:379)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:224)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2113)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2087)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7764)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7309)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7166)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
       at android.app.ActivityThread.access$1600(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

Caused by java.lang.ClassNotFoundException: com.mapbox.maps.loader.MapboxMapsInitializer
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:454)
       at java.lang.Class.forName(Class.java:379)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:224)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2113)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2087)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7764)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7309)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7166)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
       at android.app.ActivityThread.access$1600(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by baleboy** [comment]
Same issue as https://github.com/mapbox/mapbox-maps-android/issues/1109
