### ISSUE TITLE
Style.addLayerAt crashes when layer index is not adjacent to an existing layer

### ISSUE THREAD

**Issue by matiasholst** [mapbox/mapbox-maps-android#2175]
## Environment

- Android OS version: API 33
- Devices affected: Tested on Pixel 7 Pro
- Maps SDK Version: 11.0.0-beta.3

## Observed behavior and steps to reproduce

When a layer is added with addLayerAt and no other layers have been added yet, an Error is thrown:

```
java.lang.Error: unknown native exception
   at com.mapbox.maps.StyleManager.addStyleLayer(Native Method)
   at com.mapbox.maps.Style.addStyleLayer(Style.kt:267)
   at com.mapbox.maps.extension.style.layers.Layer.bindTo(Layer.kt:148)
   at com.mapbox.maps.extension.style.layers.LayerUtils.addLayerAt(LayerExt.kt:88)
   at com.example.mapbox3dissue.MainActivity$case2$1.onStyleLoaded(MainActivity.kt:65)
   at com.mapbox.maps.StyleObserver.run(StyleObserver.kt:98)
   at android.os.MessageQueue.nativePollOnce(Native Method)
   at android.os.MessageQueue.next(MessageQueue.java:335)
   at android.os.Looper.loopOnce(Looper.java:161)
   at android.os.Looper.loop(Looper.java:288)
   at android.app.ActivityThread.main(ActivityThread.java:7918)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Example code**
```kotlin
map.getStyle {style ->
    try {
        style.addLayerAt(RasterLayer("raster", "raster"), 0)
    } catch (e: Error) {
        Log.e("layer_crash", "index: 0, crash: ${e.message}")
        throw e
    }
}
```

If there exists a layer on the style already, then a layer can be added at index 0, but futher layers added at increasing indexes will throw an exception:

```
com.mapbox.maps.MapboxStyleException: Add layer failed: Index is out of range
   at com.mapbox.maps.extension.style.layers.Layer.bindTo(Layer.kt:150)
   at com.mapbox.maps.extension.style.layers.LayerUtils.addLayerAt(LayerExt.kt:88)
   at com.example.mapbox3dissue.MainActivity$case1$1.onStyleLoaded(MainActivity.kt:53)
   at com.mapbox.maps.StyleObserver.run(StyleObserver.kt:98)
   at android.os.MessageQueue.nativePollOnce(Native Method)
   at android.os.MessageQueue.next(MessageQueue.java:335)
   at android.os.Looper.loopOnce(Looper.java:161)
   at android.os.Looper.loop(Looper.java:288)
   at android.app.ActivityThread.main(ActivityThread.java:7918)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Example code**

```kotlin
map.getStyle {style ->

    style.addLayer(ModelLayer("model", "model"))

    for (i in 0..100 step 2) {
        try {
            val id = UUID.randomUUID().toString()
            style.addLayerAt(RasterLayer(id, id), i)
        } catch (e: Exception) {
            Log.e("layer_crash", "index: $i, crash: ${e.message}")
            throw e
        }
    }
}
```

## Expected behavior

The layer be added to the map at the given index

## Notes / preliminary analysis

- If the step is changed to 1 in the second example, all layers are added with no issue.
- In my own app I have a few number of layers, and the point where addLayerAt crashes happens at a higher index than 2

**Comment by baleboy** [comment]
@matiasholst thanks for the report. Could you kindly confirm whether the same issue is present on 11.0.0?

**Comment by pengdev** [comment]
> When a layer is added with addLayerAt and no other layers have been added yet, an Error is thrown:
```
java.lang.Error: unknown native exception
   at com.mapbox.maps.StyleManager.addStyleLayer(Native Method)
   at com.mapbox.maps.Style.addStyleLayer(Style.kt:267)
   at com.mapbox.maps.extension.style.layers.Layer.bindTo(Layer.kt:148)
   at com.mapbox.maps.extension.style.layers.LayerUtils.addLayerAt(LayerExt.kt:88)
   at com.example.mapbox3dissue.MainActivity$case2$1.onStyleLoaded(MainActivity.kt:65)
   at com.mapbox.maps.StyleObserver.run(StyleObserver.kt:98)
   at android.os.MessageQueue.nativePollOnce(Native Method)
   at android.os.MessageQueue.next(MessageQueue.java:335)
   at android.os.Looper.loopOnce(Looper.java:161)
   at android.os.Looper.loop(Looper.java:288)
   at android.app.ActivityThread.main(ActivityThread.java:7918)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

@matiasholst I just validated the issue, this is not happening any more with the latest release, layer can be added successfully when position is set to 0.

> If there exists a layer on the style already, then a layer can be added at index 0, but futher layers added at increasing indexes will throw an exception:

```
com.mapbox.maps.MapboxStyleException: Add layer failed: Index is out of range
   at com.mapbox.maps.extension.style.layers.Layer.bindTo(Layer.kt:150)
   at com.mapbox.maps.extension.style.layers.LayerUtils.addLayerAt(LayerExt.kt:88)
   at com.example.mapbox3dissue.MainActivity$case1$1.onStyleLoaded(MainActivity.kt:53)
   at com.mapbox.maps.StyleObserver.run(StyleObserver.kt:98)
   at android.os.MessageQueue.nativePollOnce(Native Method)
   at android.os.MessageQueue.next(MessageQueue.java:335)
   at android.os.Looper.loopOnce(Looper.java:161)
   at android.os.Looper.loop(Looper.java:288)
   at android.app.ActivityThread.main(ActivityThread.java:7918)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

This is expected, as the layer position should be within the number of current available layers.
