### ISSUE TITLE
java.lang.ClassCastException: androidx.compose.ui.node.LayoutNode cannot be cast to com.mapbox.maps.extension.compose.internal.MapNode

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox-maps-android#2196]
## Environment

- Android OS version:
- Devices affected:
- Maps SDK Version: com.mapbox.extension:maps-compose:0.1.0

The error appears, the problem is when you put two composable MapboxMap on the same screen.
For example, if you have an if, which shows you a map with a style and in the else another style

`FATAL EXCEPTION: main
                                                                                                    Process: es.devinet.teleseguidor, PID: 8511
                                                                                                    java.lang.ClassCastException: androidx.compose.ui.node.LayoutNode cannot be cast to com.mapbox.maps.extension.compose.internal.MapNode
                                                                                                    	at com.mapbox.maps.extension.compose.internal.MapApplier.insertTopDown(MapApplier.kt:49)
                                                                                                    	at androidx.compose.runtime.changelist.Operation$InsertNodeFixup.execute(Operation.kt:480)
                                                                                                    	at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:307)
                                                                                                    	at androidx.compose.runtime.changelist.FixupList.executeAndFlushAllPendingFixups(FixupList.kt:50)
                                                                                                    	at androidx.compose.runtime.changelist.Operation$InsertSlotsWithFixups.execute(Operation.kt:441)
                                                                                                    	at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:307)
                                                                                                    	at androidx.compose.runtime.changelist.ChangeList.executeAndFlushAllPendingChanges(ChangeList.kt:77)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:900)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:929)
                                                                                                    	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1069)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3539)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3539)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:562)
                                                                                                    	at com.mapbox.maps.extension.compose.MapboxMapKt$MapboxMap$4.invokeSuspend(MapboxMap.kt:102)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8410)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@69b8b83, androidx.compose.runtime.BroadcastFrameClock@f0e8100, StandaloneCoroutine{Cancelling}@a7b1d39, AndroidUiDispatcher@c68ff7e]`

**Comment by pengdev** [comment]
@DavidMunozDevinet could you share some code snippets to reproduce the exception?
Looks like you are inserting an Android UI node to inside the MapNode tree.
