### ISSUE TITLE
Crash during animation when useBackgroundThread is set

### ISSUE THREAD

**Issue by SamuelBrucksch** [mapbox/mapbox-maps-android#2212]
## Environment

- Android OS version: 13
- Devices affected: Xiaomi Poco F5
- Maps SDK Version: 10.16.1

A user reported an app crash. This is what we got via bugsnag:
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object android.animation.TypeEvaluator.evaluate(float, java.lang.Object, java.lang.Object)' on a null object reference
        at android.animation.KeyframeSet.getValue(KeyframeSet.java:202)
        at android.animation.PropertyValuesHolder.calculateValue(PropertyValuesHolder.java:1017)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1648)
        at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1440)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1572)
        at android.animation.ValueAnimator.pulseAnimationFrame(ValueAnimator.java:1591)
        at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1170)
        at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1061)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
        at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1457)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1467)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
        at android.view.Choreographer.doFrame(Choreographer.java:998)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1435)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:211)
        at android.os.Looper.loop(Looper.java:300)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

And then in Threads we got this:
```
Thread 19401 - MapboxAnimThread - (RUNNABLE)
        at android.animation.KeyframeSet.getValue(KeyframeSet.java:202)
        at android.animation.PropertyValuesHolder.calculateValue(PropertyValuesHolder.java:1017)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1648)
        at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1440)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1572)
        at android.animation.ValueAnimator.pulseAnimationFrame(ValueAnimator.java:1591)
        at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1170)
        at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1061)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
        at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1457)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1467)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
        at android.view.Choreographer.doFrame(Choreographer.java:998)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1435)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:211)
        at android.os.Looper.loop(Looper.java:300)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

Which makes me believe, that the error comes from Mapbox SDK. 

I still remember, that we opened an issue earlier, where Xiaomi devices had issues with rendering in AA, when the phone screen was off:
https://github.com/mapbox/mapbox-maps-android/issues/1413

The solution was to toggle an option, that uses a different render thread. However there seems to be an issue with that in rare cases. @kiryldz you worked on that previously, could you please check, if the error is somehow related to that?

**Comment by ankiimation** [comment]
following

**Comment by ankiimation** [comment]
any updates?

**Comment by zickone999** [comment]
any news ?

**Comment by ankiimation** [comment]
Any updates? This issue makes our production app's Android Auto feature unstable on Xiaomi and Samsung devices!
