### ISSUE TITLE
Android Auto cluster display

### ISSUE THREAD

**Issue by mj09** [mapbox/mapbox-maps-android#2245]
## Environment

- Android OS version: 12, 13, 14
- Devices affected:
- Maps SDK Version: 10.16.3

## Observed behavior and steps to reproduce

Trying to use the new cluster display option which is included in the latest release candidate of  car app library 1.4.0-rc02 and following the guide from https://developer.android.com/training/cars/apps/navigation#declare_cluster_support. However I am getting this error right after the "main" display is trying to load

`Error: [type: null, cause: java.lang.SecurityException: Binder invocation to an incorrect interface, debug msg: Remote call GET_APP_VERSION failed.]
                                                                                                    java.lang.SecurityException: Binder invocation to an incorrect interface
                                                                                                    	at android.os.Parcel.nativeEnforceInterface(Native Method)
                                                                                                    	at android.os.Parcel.enforceInterface(Parcel.java:698)
                                                                                                    	at fzy.onTransact(SourceFile:2)
                                                                                                    	at android.os.Binder.transact(Binder.java:1064)
                                                                                                    	at androidx.car.app.ICarApp$Stub$Proxy.getAppInfo(SourceFile:4)
                                                                                                    	at feh.a(SourceFile:1)
                                                                                                    	at fel.a(SourceFile:1)
                                                                                                    	at fee.a(SourceFile:2)
                                                                                                    	at mut.c(SourceFile:2)
                                                                                                    	at ffc.onServiceConnected(SourceFile:8)
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

What I have done to supposedly support cluster display is :

`override fun onCreateSession(sessionInfo: SessionInfo): Session {
        return  if (sessionInfo.displayType == SessionInfo.DISPLAY_TYPE_CLUSTER) {
            CarSession(logger)
        } else {
            CarSession(logger)
        }`

Which replaces the old onCreateSession()

Next I added androidx.car.app.category.FEATURE_CLUSTER to 
`        <service
            android:name="com.saphe.auto.AndroidAutoService"
            android:exported="true"
            android:foregroundServiceType="location">
            <intent-filter>
                <action android:name="androidx.car.app.CarAppService" />
                <category android:name="androidx.car.app.category.NAVIGATION" />
                <category android:name="androidx.car.app.category.FEATURE_CLUSTER"/>
            </intent-filter>
        </service>`

![image](https://github.com/mapbox/mapbox-maps-android/assets/5688962/2d249d65-dcaa-438d-8933-86cae76f8b1a)

## Expected behavior

The mapbox map should be shown in the main display & cluster display as well

## Notes / preliminary analysis

I am unsure if this is a problem with Mapbox or if its a problem at Google. I have also created a ticket at Google about this issue as well. But perhaps Mapbox does not support cluster display yet?

**Comment by mj09** [comment]
Seems like Google has accepted the bug, so i suppose this can be closed ;)
