### ISSUE TITLE
Crash with `flyTo` with camera position set with `cameraForCoordinateBounds`

### ISSUE THREAD

**Issue by boiler23** [mapbox/mapbox-maps-android#2289]
## Environment

- Android OS version: 12, 14
- Devices affected: Lenovo Tab P11 Plus, Samsung Galaxy S23 Ultra
- Maps SDK Version: 11.1.0

## Observed behavior and steps to reproduce

Sometimes, in my app, I want to focus the map on a specific region, so I'm setting the map via the `flyTo` method to the camera options, defined by a `cameraForCoordinateBounds` method. The code looks roughly like this:

```
val update = mbMap.cameraForCoordinateBounds(
      coordinateBounds,
      bearing = 0.0,
      pitch = 0.0,
      boundsPadding = EdgeInsets(...),
)
mbMap.flyTo(cameraOptions, mapAnimationOptions { })
```

Sometimes, this leads to the following crash:
```
Fatal Exception: java.lang.Error: latitude must not be NaN
       at com.mapbox.maps.Projection.unproject(Projection.java)
       at com.mapbox.maps.MapboxMap.unproject(MapboxMap.kt:1148)
```

I don't have specific steps to reproduce, but I observe those crashes in Firebase, specifically on the Lenovo device mentioned above. I noticed this once on my device as well. However, the crash dissolved on my device after some time without changing the coordinate bounds. It may depend on the initial camera position. The coordinate bounds, in that case, were 100% valid.
My initial assumption was that the coordinate region was invalid, so I added a few checks: `coordinateBounds.isValid && coordinateBounds.isBounded && !coordinateBounds.isEmpty`. Unfortunately, that didn't help; the crash is still there.
Note: With Mapbox 10, everything worked well.

**Comment by eddiecrawford** [comment]
Also experiencing this crash once we updated to SDK Version `11.0.0`

**Comment by kiryldz** [comment]
@eddiecrawford thanks for the detailed description, we'll take a look. Also noting that it would help if you could somehow share the output of `cameraForCoordinateBounds` that breaks the `flyTo` e.g. use `try / catch` block for `flyTo` method and re-throw another exception with additional data when `java.lang.Error: latitude must not be NaN` happens.

**Comment by boiler23** [comment]
Good point - I will add the coordinate bounds logging and try to share some examples with you.
However, sometimes the crash happens in the code I don't have control over, so there is no way to put a try/catch - see the example below.

```
Fatal Exception: java.lang.Error: latitude must not be NaN
       at com.mapbox.maps.Projection.unproject(Projection.java)
       at com.mapbox.maps.MapboxMap.unproject(MapboxMap.kt:1150)
       at com.mapbox.maps.plugin.animation.CameraAnimatorsFactory.getFlyTo$lambda$41(CameraAnimatorsFactory.kt:423)
       at android.animation.KeyframeSet.getValue(KeyframeSet.java:202)
       at android.animation.PropertyValuesHolder.calculateValue(PropertyValuesHolder.java:1017)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1561)
       at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1357)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1489)
       at android.animation.ValueAnimator.pulseAnimationFrame(ValueAnimator.java:1508)
       at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1170)
       at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1150)
       at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1053)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1103)
       at android.view.Choreographer.doCallbacks(Choreographer.java:896)
       at android.view.Choreographer.doFrame(Choreographer.java:810)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1090)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7884)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by boiler23** [comment]
Ok, here is an example of problematic bounds:
southwest lat,lon: 45.72758296,15.98882057, northeast lat,lon: 45.7805104,16.04037257
There may be an issue with math implementation on this Lenovo Tab. If you have it in your test stand, it should greatly simplify the process. I unfortunately do not have it :(
I hope this will help to investigate!

**Comment by kiryldz** [comment]
@boiler23 thanks for the example. Is it possible you also share the `boundsPadding = EdgeInsets(...),` as it seems that precisely padding may be an issue? Additionally it would be also great to get the current viewport size for that device (taken from `mapView.mapboxMap.getSize()`) but if it's not possible I'll assume that the map was rendered full-screen and I can take it from Lenovo Tab specs (however ideally I need the precise Lenovo Tab device model).

**Comment by boiler23** [comment]
About the paddings, would `dp` values work for you?
top = 149dp
left = 49dp
bottom padding = 89dp
right = 49dp

The precise model is [Lenovo Tab P11 Plus](https://www.gsmarena.com/lenovo_tab_p11_plus-10990.php); at least, this is how Firebase shows it :)
The map is fullscreen, so you can assume the viewport size is 2000x1200 pixels, according to the specs.

**Comment by kiryldz** [comment]
@boiler23 thanks for additional data. Sadly I still can't reproduce it. I guess it may be connected with the fact you mentioned in the issue description:

 > It may depend on the initial camera position.

Can you also log and share the initial camera state before you do `flyTo` that causes a crash on Lenovo Tab? You can obtain it via `mapboxMap.cameraState`.

**Comment by boiler23** [comment]
Okay, I will do my best to collect this data for you, but it may take some time. I hope to have it ready by next week.
Have you considered logging an error and completing the animation instead of raising an exception? It could be a reasonable and easy workaround.

**Comment by kiryldz** [comment]
> Okay, I will do my best to collect this data for you, but it may take some time. I hope to have it ready by next week. Have you considered logging an error and completing the animation instead of raising an exception? It could be a reasonable and easy workaround.

Sounds like more of hiding the actual issue and we're interested in trying to fix it 😄 However if we'll get stuck - we can go with it, we already use that approach a bit later in animations, when we actually call native `setCamera`, see [this](https://github.com/mapbox/mapbox-maps-android/blob/7fb578c1eff912fa8e9b93de8542b1726b34048e/plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt#L239-L247) code.

**Comment by schmecs** [comment]
Here are the camera options we've collected right before the `flyTo` crash:

```
[center: Point{type=Point, bbox=null, coordinates=[-80.4313600046345, 27.826857397269716]}, padding: , anchor: , zoom: NaN, bearing: 1.2706762782183643, pitch: 0.0]
```

Coordinates / pitch / bearing vary, but the other options are always as shown above before crashing.

**Comment by boiler23** [comment]
Hey @kiryldz, here is another example from the Samsung S21 FE 5G:

Bounds to fly to:
southwest lat, lon: 16.750444937444684, 46.95869028358888
northeast lat, lon: 39.98385025578435, 107.36193674974396

Start position:
lat, lon: 16.075125493969686, 108.08854009955576
padding (in pixels): top=-677.9921264648438, left=252.6684112548828, bottom=0.0, right=0.0
start zoom: 16.994972229003906
start bearing: -0.0
start pitch: 0.0

Map view dimensions (in pixels): 1080x2153

I hope this helps!

**Comment by kiryldz** [comment]
@boiler23 thanks for an example! It seems that we have identified the issue and hopefully it should be fixed in upcoming release.

**Comment by boiler23** [comment]
Amazing, thank you! Looking forward to it!

**Comment by kiryldz** [comment]
The fix is available in https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.3.0-rc.1.

**Comment by boiler23** [comment]
Thank you!
