### ISSUE TITLE
NPE crash on Samsung devices upon network change notification processing

### ISSUE THREAD

**Issue by vova-ppl-ai** [mapbox/mapbox-maps-android#2296]
## Environment

- Android OS version: 12
- Devices affected: Galaxy A32 5G
- Maps SDK Version: 11.2.0-beta.1

## Observed behavior and steps to reproduce

Crashes in background

## Expected behavior

To not crash in background

## Additional links and references

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.samsung.android.feature.SemCscFeature.getString(java.lang.String)' on a null object reference
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2444)
       at android.os.Parcel.createException(Parcel.java:2422)
       at android.os.Parcel.readException(Parcel.java:2405)
       at android.os.Parcel.readException(Parcel.java:2347)
       at android.net.IConnectivityManager$Stub$Proxy.getActiveNetwork(IConnectivityManager.java:1619)
       at android.net.ConnectivityManager.getActiveNetwork(ConnectivityManager.java:1348)
       at com.mapbox.common.Reachability.onNetworkChanged(Reachability.java:214)
       at com.mapbox.common.ConnectionChangeCallback.lambda$notifyReachability$0(Reachability.java:48)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.net.NetworkPolicyManagerService.isUidNetworkingBlockedInternal(NetworkPolicyManagerService.java:6362)
	at com.android.server.net.NetworkPolicyManagerService.isUidNetworkingBlocked(NetworkPolicyManagerService.java:6329)
	at android.net.NetworkPolicyManager.isUidNetworkingBlocked(NetworkPolicyManager.java:570)
	at com.android.server.ConnectivityService.isNetworkWithCapabilitiesBlocked(ConnectivityService.java:1810)
	at com.android.server.ConnectivityService.getActiveNetworkForUidInternal(ConnectivityService.java:1918)

**Comment by kiryldz** [comment]
@vova-ppl-ai thanks for reporting, we'll take a look.

**Comment by kiryldz** [comment]
@vova-ppl-ai the issue should be fixed in upcoming (next week) v11.3.0-beta.1 release. Closing this, feel free to re-open if the issue will persist.
