### ISSUE TITLE
Why do I see obtaining backend services

### ISSUE THREAD

**Issue by zhzhzhzzhzhz** [mapbox/mapbox-maps-android#2333]
I encountered this problem while putting the app on the shelves and don't know how to solve it. Can anyone help me
The following is the error issue stack information：
at android.app.ActivityManager.getRunningServices()
      at com.mapbox.common.LifecycleUtils.hasServiceRunningInForeground(LifecycleUtils.kt:96)
      at com.mapbox.common.LifecycleUtils.getLifecycleState(LifecycleUtils.kt:102)
      at com.mapbox.common.LifecycleService.onCreate(LifecycleService.kt:106)
      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3392)
      at android.app.ActivityThread.-wrap4(Unknown Source:0)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1730)
      at android.os.Handler.dispatchMessage(Handler.java:106)
      at android.os.Looper.loop(Looper.java:164)
      at android.app.ActivityThread.main(ActivityThread.java:6554)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by zhzhzhzzhzhz** [comment]
APP 以个人信息处理规则弹窗等形式向用户明示个人信息处理的目的、方式和范围，未经用户同意，存在收集 IMEI、IMSI、设备 MAC 地址、SUPI、SUCI、软件安装列表、位置、联系人、通话记录、日历、短信、本机 电话号码、图片、音视频等个人信息
检测详情:
(1)APP未经同意，存在收集个人信息的行为，读取当前运行服务
改进建议:
建议在用户同意隐私政策之后，APP开始收集用户个人信息。

堆栈详情如下：
at android.app.ActivityManager.getRunningServices()
      at com.mapbox.common.LifecycleUtils.hasServiceRunningInForeground(LifecycleUtils.kt:96)
      at com.mapbox.common.LifecycleUtils.getLifecycleState(LifecycleUtils.kt:102)
      at com.mapbox.common.LifecycleService.onCreate(LifecycleService.kt:106)
      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3392)
      at android.app.ActivityThread.-wrap4(Unknown Source:0)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1730)
      at android.os.Handler.dispatchMessage(Handler.java:106)
      at android.os.Looper.loop(Looper.java:164)
      at android.app.ActivityThread.main(ActivityThread.java:6554)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by kiryldz** [comment]
This should be fixed in latest version. Please re-open if the issue persists.
