### ISSUE TITLE
java.lang.IllegalArgumentException: Parse error at offset 165: Missing a colon after a name of object member.

### ISSUE THREAD

**Issue by robertlevonyan** [mapbox/mapbox-maps-android#2340]
## Environment

- Android OS version: 11
- Devices affected: OnePlus8Pro
- Maps SDK Version: 11.2.2

## Observed behavior and steps to reproduce

The crash is reported via Crashlytics

## Expected behavior

Do not have crash

## Additional links and references

```
Fatal Exception: java.lang.IllegalArgumentException: Parse error at offset 165: Missing a colon after a name of object member.
       at com.mapbox.maps.StyleManager.addPersistentStyleLayer(StyleManager.java)
       at com.mapbox.maps.MapboxStyleManager.addPersistentStyleLayer(MapboxStyleManager.kt:12)
       at com.mapbox.maps.Style.addPersistentStyleLayer(Style.kt:10)
       at com.mapbox.maps.plugin.locationcomponent.LocationLayerWrapper.bindTo(LocationLayerWrapper.kt:11)
       at com.mapbox.maps.plugin.locationcomponent.LocationComponentPositionManager.addLayerToMap(LocationComponentPositionManager.kt:39)
       at com.mapbox.maps.plugin.locationcomponent.LocationIndicatorLayerRenderer.addLayers(LocationIndicatorLayerRenderer.kt:7)
       at com.mapbox.maps.plugin.locationcomponent.LocationPuckManager.initialize(LocationPuckManager.kt:71)
       at com.mapbox.maps.plugin.locationcomponent.LocationPuckManager$updateSettings$1.invoke(LocationPuckManager.kt:2)
       at com.mapbox.maps.plugin.locationcomponent.LocationPuckManager$updateSettings$1.invoke(LocationPuckManager.kt:1)
       at com.mapbox.maps.plugin.MapDelegateProviderImpl.getStyle$lambda$0(MapDelegateProviderImpl.kt:11)
       at com.mapbox.maps.MapboxMap.getStyle(MapboxMap.kt:2)
       at com.mapbox.maps.plugin.MapDelegateProviderImpl.getStyle(MapDelegateProviderImpl.kt:14)
       at com.mapbox.maps.plugin.locationcomponent.LocationPuckManager.updateSettings(LocationPuckManager.kt:48)
       at com.mapbox.maps.plugin.locationcomponent.LocationComponentPluginImpl.applySettings(LocationComponentPluginImpl.kt:66)
       at com.mapbox.maps.plugin.locationcomponent.generated.LocationComponentSettingsBase.updateSettings(LocationComponentSettingsBase.kt:24)
       at com.mapbox.maps.extension.compose.internal.SettingsUtilsKt.applySettings(SettingsUtils.kt:4)
       at com.mapbox.maps.extension.compose.internal.MapboxMapNodeKt$MapboxMapComposeNode$2$5.invoke(MapboxMapNode.kt:2)
       at com.mapbox.maps.extension.compose.internal.MapboxMapNodeKt$MapboxMapComposeNode$2$5.invoke(MapboxMapNode.kt:1)
       at androidx.compose.runtime.changelist.Operation$UpdateNode.execute(Operation.kt:17)
       at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:23)
       at androidx.compose.runtime.changelist.ChangeList.executeAndFlushAllPendingChanges(ChangeList.kt:3)
       at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:50)
       at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:182)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:182)
       at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:7)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.java:48)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.java:48)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:48)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
       at android.view.Choreographer.doCallbacks(Choreographer.java:796)
       at android.view.Choreographer.doFrame(Choreographer.java:727)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by tymen-schiphol** [comment]
We're experiencing the exact same issue.

**Comment by steurt** [comment]
Seeing the exact same issue.

**Comment by marcel-dd** [comment]
Any leads?

**Comment by Copatych** [comment]
Mapbox version "11.2.1". Device Redmi Note 11, Android 11. The same error is observed.

**Comment by slipdef** [comment]
Is it going to be fixed ever? We experience dozenz of such crashes every day.

**Comment by hassanad94** [comment]
Every time when google check the app... its crashing...

**Comment by abbas427** [comment]
Is anyone able to solve it?

**Comment by yterletskyi** [comment]
still experiencing this

**Comment by Mbes9** [comment]
Still seeing the same crash with the same `Parse error at offset 165` on **Maps SDK 11.23.1 and 11.29.0**.

The trigger is a non-finite bearing reaching the location puck through `LocationConsumer.onBearingUpdated`. With `puckBearing = HEADING`, `LocationCompassEngine` is the likely source, although we couldn't capture the raw sensor sample on the affected device.

The crash itself is reproducible in `com.mapbox.bindgen.Value.toJson()`: Gson throws `Numeric values must be finite`, but `Value.toJson()` still returns the partially written JSON, which is then rejected by the native parser at offset 165.

There is also a recovery issue: once `LocationPuckManager` receives the non-finite bearing, later valid headings don't recover the puck. It only comes back after recreating the `MapView`.

We can reproduce this consistently by injecting a single `NaN` bearing.
