### ISSUE TITLE
Fatal exception: java.lang.Error - failed to resize: size is empty.

### ISSUE THREAD

**Issue by Krzysztof-Daniluk** [mapbox/mapbox-maps-android#2399]
## Environment

- Android OS version:
multiple versions from Android 12 to 14
- Devices affected:
multiple devices - mostly Samsung S10, Samsung GalaxyA14 5G, Google Pixel 4
- Maps SDK Version:
Happens with multiple SDK Versions: v11.3.1, v11.3.0, v11.2.2, v11.1.0

## Observed behavior and steps to reproduce

The issue started to show on Crashlytics when we implemented the search view in compose above the map view created with XML. When a user clicks the search view it opens full screen and the map probably shrinks. 

It is not happening often - we have 300 crashes during 90 days. 

`     Fatal Exception: java.lang.Error: failed to resize: size is empty
       at com.mapbox.maps.Map.setSize(Map.java)
       at com.mapbox.maps.NativeMapImpl.setSize(NativeMapImpl.kt:16)
       at com.mapbox.maps.renderer.MapboxRenderer.onSurfaceChanged(MapboxRenderer.kt:93)
       at com.mapbox.maps.MapController.onSizeChanged$lambda$9(MapController.kt:220)
       at com.mapbox.maps.renderer.MapboxRenderThread.drainQueue(MapboxRenderThread.kt:718)
       at com.mapbox.maps.renderer.MapboxRenderThread.draw(MapboxRenderThread.kt:362)
       at com.mapbox.maps.renderer.MapboxRenderThread.doFrame(MapboxRenderThread.kt:586)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
       at android.view.Choreographer.doCallbacks(Choreographer.java:866)
       at android.view.Choreographer.doFrame(Choreographer.java:792)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)`

Any thoughts on that? 🤔  The stack trace comes from the MapBox internals. 

## Expected behavior

No crashing

**Comment by kiryldz** [comment]
@Krzysztof-Daniluk well, this happens because indeed you're resizing the map view so that it has either height or width equal to 0. I assume you have to change this logic somehow and for example remove the `MapView` completely from the layout if width or height is small enough.

**Comment by Krzysztof-Daniluk** [comment]
Well.. You are most probably right. Thank you very much for fast respond!
