### ISSUE TITLE
mapbox 初始化读取行动轨迹

### ISSUE THREAD

**Issue by zhzhzhzzhzhz** [mapbox/mapbox-maps-android#2406]
java.lang.Exception
	at android.location.LocationManager.requestLocationUpdates(Native Method)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:590)
	at android.location.LocationManager.requestLocationUpdates(Native Method)
	at com.mapbox.common.location.AndroidDeviceLocationProvider.doStart(AndroidDeviceLocationProvider.kt:82)
	at com.mapbox.common.location.BaseDeviceLocationProvider.start(BaseDeviceLocationProvider.kt:66)
	at com.mapbox.common.location.BaseDeviceLocationProvider.addLocationObserver(BaseDeviceLocationProvider.kt:95)

**Comment by kiryldz** [comment]
Please re-open and provide more details. Closing for now as non-actionable.

**Comment by zhzhzhzzhzhz** [comment]
> 请重新打开并提供更多详细信息。由于不可操作，因此暂时关闭。

应用启动 就在后台读取行动轨迹 java.lang.Exception
	at android.location.LocationManager.requestLocationUpdates(Native Method)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:590)
	at android.location.LocationManager.requestLocationUpdates(Native Method)
	at com.mapbox.common.location.AndroidDeviceLocationProvider.doStart(Unknown Source:134)
	at com.mapbox.common.location.BaseDeviceLocationProvider.start(Unknown Source:31)
	at com.mapbox.common.location.BaseDeviceLocationProvider.addLocationObserver(SourceFile:2)

**Comment by zhzhzhzzhzhz** [comment]
![Uploading 321718938692_.pic.jpg…]()

**Comment by zhzhzhzzhzhz** [comment]
如何禁止读取用户行动轨迹

**Comment by zhzhzhzzhzhz** [comment]
还未同意隐私政策  就执行更新轨迹的方法

**Comment by zhzhzhzzhzhz** [comment]
我只是添加了mapbox SDK 就出现了读取行动轨迹的问题 还未申请任何位置权限

**Comment by zhzhzhzzhzhz** [comment]
我应该如何做 才能禁止mapbox 读取行动轨迹  有没有隐私政策方法  类似其他地图服务商
![Uploading 331718939416_.pic.jpg…]()

**Comment by zhzhzhzzhzhz** [comment]
有没有像其他厂商一样的隐私政策方法 在未同意协议之前 不要进行任何方法操作 
![321718938692_ pic](https://github.com/mapbox/mapbox-maps-android/assets/163098899/0e7dfa47-c704-43b0-acfa-14785414b4af)
![331718939416_ pic](https://github.com/mapbox/mapbox-maps-android/assets/163098899/1d1a7db0-0263-45ef-aac8-96c765204bbd)
