### ISSUE TITLE
应用启动 还未申请定位权限 

### ISSUE THREAD

**Issue by zhzhzhzzhzhz** [mapbox/mapbox-maps-android#2411]
java.lang.Exception
	at android.location.LocationManager.requestLocationUpdates(Native Method)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:590)
	at android.location.LocationManager.requestLocationUpdates(Native Method)
	at com.mapbox.common.location.AndroidDeviceLocationProvider.doStart(Unknown Source:134)
	at com.mapbox.common.location.BaseDeviceLocationProvider.start(Unknown Source:31)
	at com.mapbox.common.location.BaseDeviceLocationProvider.addLocationObserver(SourceFile:2)

**Comment by zhzhzhzzhzhz** [comment]
![321718938692_ pic](https://github.com/mapbox/mapbox-maps-android/assets/163098899/8360a1c4-eafd-4a47-836a-f4a82b437479)
应该如何做才能禁止读取用户行动轨迹 还未申请定位权限 就能够读取位置信息吗? 侵权行为

**Comment by natiginfo** [comment]
This trace is already mentioned in https://github.com/mapbox/mapbox-maps-android/issues/2410. Since this is duplicate, closing this one. Moreover, if you could provide description of the issue you are facing in English, we'd appreciate it.
