### ISSUE TITLE
应用启动未申请定位权限 就获取行动轨迹  错误的获取

### ISSUE THREAD

**Issue by zhzhzhzzhzhz** [mapbox/mapbox-maps-android#2412]
java.lang.Exception
	at android.location.LocationManager.requestLocationUpdates(Native Method)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:590)
	at android.location.LocationManager.requestLocationUpdates(Native Method)
	at com.mapbox.common.location.AndroidDeviceLocationProvider.doStart(Unknown Source:134)
	at com.mapbox.common.location.BaseDeviceLocationProvider.start(Unknown Source:31)
	at com.mapbox.common.location.BaseDeviceLocationProvider.addLocationObserver(SourceFile:2)

**Comment by natiginfo** [comment]
This trace is already mentioned in https://github.com/mapbox/mapbox-maps-android/issues/2410. Since this is duplicate, closing this one. Moreover, if you could provide description of the issue you are facing in English, we'd appreciate it.
