### ISSUE TITLE
Call location before the user does not agree to the privacy policy

### ISSUE THREAD

**Issue by wingkingbobo** [mapbox/mapbox-maps-android#2442]
## Environment
- Maps SDK Version: v11.1.0

## Observed behavior and steps to reproduce

My app enters from `SplashActivity`, and after the user agrees to the privacy policy, it redirects to `MainActivity` to load MapView. 
In theory, `SplashActivity` does not call any mapbox code, and mapbox should not obtain location information at this time. 
However, the application market detected that the `AndroidDeviceLocationProvider. doStart()` method of mapbox was called, resulting in the app being unable to pass the review for listing.

The privacy check report for the vivo app market is as follows:
```
"java.lang.Exception
	at android.location.LocationManager.requestLocationUpdates(Native Method)
	at com.mapbox.common.location.AndroidDeviceLocationProvider.doStart(AndroidDeviceLocationProvider.kt:102)
	at com.mapbox.common.location.BaseDeviceLocationProvider.start(BaseDeviceLocationProvider.kt:66)
	at com.mapbox.common.location.BaseDeviceLocationProvider.addLocationObserver(BaseDeviceLocationProvider.kt:95)"
"java.lang.Exception
	at android.location.LocationManager.requestLocationUpdates(Native Method)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:651)
	at android.location.LocationManager.requestLocationUpdates(Native Method)
	at com.mapbox.common.location.AndroidDeviceLocationProvider.doStart(AndroidDeviceLocationProvider.kt:102)
	at com.mapbox.common.location.BaseDeviceLocationProvider.start(BaseDeviceLocationProvider.kt:66)
	at com.mapbox.common.location.BaseDeviceLocationProvider.addLocationObserver(BaseDeviceLocationProvider.kt:95)"

```

## Expected behavior
1. Fixed the issue of automatic calling of `AndroidDeviceLocationProvider.doStart()`. 
2. Alternatively, provide a method similar to `void setAgreePrivacyPolicy(boolean agree)` that does not access any privacy permission interfaces until it is set to true.

**Comment by jush** [comment]
Make sure that the user has not granted location permission to the app before the user agrees to the privacy policy.

**Comment by lct8712** [comment]
Same here, @wingkingbobo How did you solve this?

**Comment by lct8712** [comment]
@wingkingbobo 太强了！感谢感谢！
