### ISSUE TITLE
State must be at least CREATED to move to DESTROYED, but was INITIALIZED

### ISSUE THREAD

**Issue by SamYStudiO** [mapbox/mapbox-maps-android#2445]
## Environment

- Android OS version: Any
- Devices affected: Any
- Maps SDK Version: 11.4.0, androidx lyfecycle 2.8.3

## Observed behavior and steps to reproduce

I see a lot of crashes from firebase crashlytics but i can't reproduce it.

```
Fatal Exception: java.lang.IllegalStateException: State must be at least CREATED to move to DESTROYED, but was INITIALIZED in component com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner@180f36c
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.jvm.kt:131)
       at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.jvm.kt:107)
       at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.doOnAttached(ViewLifecycleOwner.kt:73)
       at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.<init>(ViewLifecycleOwner.kt:60)
       at com.mapbox.maps.plugin.lifecycle.MapboxLifecyclePluginImpl.registerLifecycleObserver(MapboxLifecyclePluginImpl.kt:30)
       at com.mapbox.maps.plugin.MapPluginRegistry.onAttachedToWindow(MapPluginRegistry.kt:192)
       at com.mapbox.maps.MapController.onAttachedToWindow$sdk_release(MapController.kt:373)
       at com.mapbox.maps.MapView.onAttachedToWindow(MapView.kt:135)
       at android.view.View.dispatchAttachedToWindow(View.java:21308)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4239)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:6001)
       at android.view.ViewGroup.addView(ViewGroup.java:5777)
       at android.view.ViewGroup.addView(ViewGroup.java:5717)
       at android.view.ViewGroup.addView(ViewGroup.java:5690)
       at android.view.ViewOverlay$OverlayViewGroup.add(ViewOverlay.java:208)
       at android.view.ViewGroupOverlay.add(ViewGroupOverlay.java:72)
       at androidx.transition.Visibility.onDisappear(Visibility.java:429)
       at androidx.transition.Visibility.createAnimator(Visibility.java:254)
       at androidx.transition.Transition.createAnimators(Transition.java:798)
       at androidx.transition.TransitionSet.createAnimators(TransitionSet.java:476)
       at androidx.transition.TransitionSet.createAnimators(TransitionSet.java:476)
       at androidx.transition.Transition.playTransition(Transition.java:1934)
       at androidx.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:300)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1102)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3311)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2201)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9000)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
       at android.view.Choreographer.doCallbacks(Choreographer.java:794)
       at android.view.Choreographer.doFrame(Choreographer.java:729)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by flasher297** [comment]
I've raised an internal ticket to investigate this crash.
We'll return as soon as we have any feedback.

**Comment by pengdev** [comment]
@SamYStudiO could you clarify the environment? Did you use compose in your app?

**Comment by Levidamales** [comment]
@pengdev I faced the same problem and I am using compose in my app.

**Comment by pengdev** [comment]
Hey @Levidamales @MatheusAraujoPro please update to the latest compose extension release, we have disabled the lifecycle plugin in the latest compose extension release, now all the lifecycle is handled within the compose extension and the above problematic code path wouldn't be executed.

**Comment by Levidamales** [comment]
I updated the compose extension version, but still have another case of the issue. Do you think they can be of the same reason?
`FATAL EXCEPTION: main
                                                                                                    Process: ru.mugs.ccs, PID: 17063
                                                                                                    java.lang.IllegalStateException: State must be at least CREATED to move to DESTROYED, but was INITIALIZED in component NavBackStackEntry(2d8f0727-c13b-4635-ac94-f279608c3cfc) destination=Destination(0x67884f5a) route=Editor
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.jvm.kt:131)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.jvm.kt:107)
                                                                                                    	at androidx.navigation.NavBackStackEntry.updateState(NavBackStackEntry.kt:186)
                                                                                                    	at androidx.navigation.NavBackStackEntry.setMaxLifecycle(NavBackStackEntry.kt:159)
                                                                                                    	at androidx.navigation.NavController.updateBackStackLifecycle$navigation_runtime_release(NavController.kt:1100)
                                                                                                    	at androidx.navigation.NavController.dispatchOnDestinationChanged(NavController.kt:996)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1882)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1817)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:2225)
                                                                                                    	at androidx.navigation.NavController.navigate$default(NavController.kt:2220)
                                                                                                    	at ru.mugs.ccs.domain.uiState.AppState.openEditor(AppState.kt:40)
                                                                                                    	at ru.mugs.ccs.presentation.composable.screen.CharacterListKt$CharacterList$1$1$3.invoke$lambda$1$lambda$0(CharacterList.kt:73)
                                                                                                    	at ru.mugs.ccs.presentation.composable.screen.CharacterListKt$CharacterList$1$1$3.$r8$lambda$EfsjE29um5lU6z9AIcLJrl6tRTE(Unknown Source:0)
                                                                                                    	at ru.mugs.ccs.presentation.composable.screen.CharacterListKt$CharacterList$1$1$3$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
                                                                                                    	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:987)
                                                                                                    	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:981)
                                                                                                    	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:665)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:544)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:566)
                                                                                                    	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Clickable.kt:947)
                                                                                                    	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:795)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:317)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
                                                                                                    	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:185)
                                                                                                    	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:104)
                                                                                                    	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:113)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1576)
2024-08-12 19:19:31.725 17063-17063 AndroidRuntime          ru.mugs.ccs                          E  	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1527)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1466)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:15130)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6659)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6447)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5888)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6076)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6133)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8918)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8869)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8837)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9051)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:280)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:337)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:168)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8250)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@e6b136f, androidx.compose.runtime.BroadcastFrameClock@a5d487c, StandaloneCoroutine{Cancelling}@1b5d505, AndroidUiDispatcher@831695a]
2024-08-12 19:19:31.736 17063-17063 MQSEventManagerDelegate ru.mugs.ccs                          E  failed to get MQSService.`

**Comment by pengdev** [comment]
@Levidamales from the stack trace, I didn't see anything mapbox-specific code path. There might be some other issues in your code relates to `NavBackStackEntry`.

**Comment by SamYStudiO** [comment]
> @SamYStudiO could you clarify the environment? Did you use compose in your app?

I'm not using compose and this issue happens a lot in my production app

![image](https://github.com/user-attachments/assets/f5c39236-2e99-4d41-83b3-49f39a0b230d)

**Comment by SamYStudiO** [comment]
@pengdev Can this be reopened or should i create new?

**Comment by Galkin-Palkin** [comment]
@pengdev I posted an answer to StackOverflow. It's about Jetpack Compose, but you may find something useful for you:
https://stackoverflow.com/questions/78927851/jetpack-compose-navigation-crashes-app-after-orientation-change

**Comment by pengdev** [comment]
> @pengdev Can this be reopened or should i create new?

@SamYStudiO please create new ticket with detailed information, would be good if you have a minimum reproduce example.

**Comment by SamYStudiO** [comment]
@Galkin-Palkin I'm not using compose
@pengdev i'll make another ticket, problem is i can't reproduce it but as shown from firebase it happens a lot in production
