### ISSUE TITLE
com.mapbox.common.battery.AndroidBatteryMonitor

### ISSUE THREAD

**Issue by thefaisalurrehman** [mapbox/mapbox-maps-android#2497]
We are facing ANR (Application Not Responding) issues related to the Mapbox.
Here is full stack trace. I can't produce manually. and I'm using this version ->
    implementation("com.mapbox.maps:android:11.7.0")
    implementation("com.mapbox.navigationcore:navigation:3.4.0")
    implementation("com.mapbox.navigationcore:ui-components:3.4.0")
    
     at java.lang.String.intern(String.java)
       at com.pairip.VMRunner.executeVM(VMRunner.java)
       at com.pairip.VMRunner.invoke(VMRunner.java:66)
       at com.mapbox.common.battery.AndroidBatteryMonitor$broadcastReceiver$1.onReceive(:23)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52851(LoadedApk.java:1322)
       at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(:4)
       at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(:39)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6647)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
       
       
       

1. # Crashlytics - Stack trace
2. # Application: com.gpsearth.maphd.view3d.livesatellite.route.finderfree.navigation
3. # Platform: android
4. # Version: 2.2.40 (58)
5. # Issue: acf9969e0f399ec0244384619059ddf0
6. # Session: 67107D3F03E2000122E21206BE65C740_DNE_0_v2
7. # Date: Thu Oct 17 2024 14:42:13 GMT+0500 (Pakistan Standard Time)

```
main (native):tid=1 systid=8930 
#00 pc 0x99000 libc.so (syscall + 32) (BuildId: d1a98b526f2f94260a53c3055979a4f6)
#01 pc 0x22a220 libart.so (art::ConditionVariable::WaitHoldingLocks + 136) (BuildId: 1ee2c234829500686eefa384068e67c8)
#02 pc 0x737a28 libart.so (art::JNI<false>::FindClass + 1580) (BuildId: 1ee2c234829500686eefa384068e67c8)
#03 pc 0x62bc0 split_config.arm64_v8a.apk + 42795008
       at com.pairip.VMRunner.executeVM(Native method)
       at com.pairip.VMRunner.invoke(VMRunner.java:66)
       at com.mapbox.common.battery.AndroidBatteryMonitor$broadcastReceiver$1.onReceive(unavailable:23)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1943)
       at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(unavailable)
       at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(unavailable:2)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8839)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

ReferenceQueueDaemon (waiting):tid=6 systid=8940 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:405)
       at java.lang.Object.wait(Object.java:543)
       at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:251)
       at java.lang.Daemons$Daemon.run(Daemons.java:131)
       at java.lang.Thread.run(Thread.java:1012)

FinalizerWatchdogDaemon (timed waiting):tid=7 systid=8942 
       at java.lang.Thread.sleep(Native method)
       at java.lang.Thread.sleep(Thread.java:450)
       at java.lang.Thread.sleep(Thread.java:355)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepForNanos(Daemons.java:517)
       at java.lang.Daemons$FinalizerWatchdogDaemon.waitForProgress(Daemons.java:580)
       at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:448)
       at java.lang.Daemons$Daemon.run(Daemons.java:131)
       at java.lang.Thread.run(Thread.java:1012)

FinalizerDaemon (waiting):tid=9 systid=8941 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:405)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:207)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:228)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:331)
       at java.lang.Daemons$Daemon.run(Daemons.java:131)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by softAxes** [comment]
facing same ANR

**Comment by flasher297** [comment]
Thank you for reaching out.
We've created an internal ticket (CORESDK-3229) and will post an update here.
