### ISSUE TITLE
GoogleActivityRecognition.start

### ISSUE THREAD

**Issue by cawanlei** [mapbox/mapbox-maps-android#2500]
## Environment

- Android OS version: android12（90%） and android 14（10%）
- Maps SDK Version: 11.6.0

 Fatal Exception: java.lang.NoSuchMethodError: No static method registerReceiver(Landroid/content/Context;Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;I)Landroid/content/Intent; in class Lf0/a; or its super classes (declaration of 'f0.a' appears in /data/internal_app/com.package.x-WNe7heuw-kkRJw3S-MZuDQ==/base.apk)
       at com.mapbox.common.movement.GoogleActivityRecognition.start(GoogleActivityRecognition.kt:111)
       at com.mapbox.common.movement.AndroidMovementMonitor.registerObserver(AndroidMovementMonitor.kt:60)

**Comment by kiryldz** [comment]
@cawanlei thanks for reporting. Are you using Proguard in your app?

**Comment by cawanlei** [comment]
yes

**Comment by cawanlei** [comment]
@kiryldz  yes. but I can't add the mapbox.

**Comment by cawanlei** [comment]
> [@cawanlei](https://github.com/cawanlei) thanks for reporting. Are you using Proguard in your app?

Yes, but it's useless.

**Comment by cawanlei** [comment]
This issue only occurs on Hisense phones; other devices are not affected.
