### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: can't call double com.mapbox.geojson.Point.longitude() on null object

### ISSUE THREAD

**Issue by xingzhongyi** [mapbox/mapbox-maps-android#2538]
java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: can't call double com.mapbox.geojson.Point.longitude() on null object
java_vm_ext.cc:570]     in call to CallDoubleMethodV
 java_vm_ext.cc:570]     from com.mapbox.bindgen.Expected com.mapbox.maps.StyleManager.updateGeoJSONSourceFeatures(java.lang.String, java.lang.String, java.util.List)

**Comment by xingzhongyi** [comment]
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630] Runtime aborting...
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630] Dumping all threads without mutator lock held
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630] All threads:
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630] DALVIK THREADS (121):
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630] "GEOJSON_PARSER" prio=5 tid=127 Runnable
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   | group="" sCount=0 dsCount=0 flags=0 obj=0x14a818e8 self=0x7bab8a00
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   | sysTid=13924 nice=0 cgrp=default sched=0/0 handle=0x6e762230
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   | state=R schedstat=( 29151725994 84476808506 79016 ) utm=2558 stm=357 core=1 HZ=100
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   | stack=0x6e65f000-0x6e661000 stackSize=1040KB
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   | held mutexes= "abort lock" "mutator lock"(shared held)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #00 pc 0030342f  /apex/com.android.runtime/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+78)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #01 pc 003ae0df  /apex/com.android.runtime/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+362)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #02 pc 003aa893  /apex/com.android.runtime/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+34)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #03 pc 003c3439  /apex/com.android.runtime/lib/libart.so (art::DumpCheckpoint::Run(art::Thread*)+588)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #04 pc 003bdbbd  /apex/com.android.runtime/lib/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+296)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #05 pc 003bd2e9  /apex/com.android.runtime/lib/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool)+1408)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #06 pc 0037d46b  /apex/com.android.runtime/lib/libart.so (art::Runtime::Abort(char const*)+1054)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #07 pc 000084c7  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+390)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #08 pc 0028c15d  /apex/com.android.runtime/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1212)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #09 pc 0028c2f9  /apex/com.android.runtime/lib/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+64)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #10 pc 00281a81  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+40)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #11 pc 00284265  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::ScopedCheck::CheckMethodAndSig(art::ScopedObjectAccess&, _jobject*, _jclass*, _jmethodID*, art::Primitive::Type, art::InvokeType)+916)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #12 pc 002831df  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::__va_list, art::Primitive::Type, art::InvokeType)+570)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #13 pc 0027523d  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallDoubleMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+44)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #14 pc 004e9aa3  /data/app/com.huanguo.autopilot1-lRQ0dEAvvKa2RVsv9lD9wQ==/lib/arm/libmapbox-maps.so (???)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #15 pc 004e9a23  /data/app/com.huanguo.autopilot1-lRQ0dEAvvKa2RVsv9lD9wQ==/lib/arm/libmapbox-maps.so (???)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #16 pc 004e8e51  /data/app/com.huanguo.autopilot1-lRQ0dEAvvKa2RVsv9lD9wQ==/lib/arm/libmapbox-maps.so (???)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #17 pc 004e9bcb  /data/app/com.huanguo.autopilot1-lRQ0dEAvvKa2RVsv9lD9wQ==/lib/arm/libmapbox-maps.so (???)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #18 pc 004e909b  /data/app/com.huanguo.autopilot1-lRQ0dEAvvKa2RVsv9lD9wQ==/lib/arm/libmapbox-maps.so (???)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #19 pc 004e64eb  /data/app/com.huanguo.autopilot1-lRQ0dEAvvKa2RVsv9lD9wQ==/lib/arm/libmapbox-maps.so (???)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #20 pc 00502383  /data/app/com.huanguo.autopilot1-lRQ0dEAvvKa2RVsv9lD9wQ==/lib/arm/libmapbox-maps.so (???)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #21 pc 00502185  /data/app/com.huanguo.autopilot1-lRQ0dEAvvKa2RVsv9lD9wQ==/lib/arm/libmapbox-maps.so (???)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #22 pc 005062ff  /data/app/com.huanguo.autopilot1-lRQ0dEAvvKa2RVsv9lD9wQ==/lib/arm/libmapbox-maps.so (???)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #23 pc 0053e50b  /data/app/com.huanguo.autopilot1-lRQ0dEAvvKa2RVsv9lD9wQ==/lib/arm/libmapbox-maps.so (???)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #24 pc 021972cb  /memfd:/jit-cache (deleted) (art_jni_trampoline+138)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #25 pc 020de6a5  /memfd:/jit-cache (deleted) (com.mapbox.maps.MapboxStyleManager.setStyleGeoJSONSourceData+164)
2024-12-06 16:15:26.436 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #26 pc 02049c17  /memfd:/jit-cache (deleted) (com.mapbox.maps.Style.setStyleGeoJSONSourceData+214)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #27 pc 020e221d  /memfd:/jit-cache (deleted) (com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.setDataAsync$lambda$3$lambda$2+220)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #28 pc 02145733  /memfd:/jit-cache (deleted) (com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.$r8$lambda$qPu7LtasLBqQGfXFmlkE0vcwtUY+50)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #29 pc 02125e69  /memfd:/jit-cache (deleted) (com.mapbox.maps.extension.style.sources.generated.GeoJsonSource$$ExternalSyntheticLambda0.run+104)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #30 pc 0200e179  /memfd:/jit-cache (deleted) (org.json.JSONStringer.string+184)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #31 pc 020b197f  /memfd:/jit-cache (deleted) (android.os.Handler.dispatchMessage+62)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #32 pc 02042b1b  /memfd:/jit-cache (deleted) (android.widget.RelativeLayout.onMeasure+3930)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #33 pc 000d7c0f  /apex/com.android.runtime/lib/libart.so (art_quick_osr_stub+46)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #34 pc 0025af9d  /apex/com.android.runtime/lib/libart.so (art::jit::Jit::MaybeDoOnStackReplacement(art::Thread*, art::ArtMethod*, unsigned int, int, art::JValue*)+1164)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #35 pc 00433f97  /apex/com.android.runtime/lib/libart.so (MterpMaybeDoOnStackReplacement+134)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #36 pc 000d73f4  /apex/com.android.runtime/lib/libart.so (MterpHelpers+244)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #37 pc 00322dc0  /system/framework/framework.jar (android.os.Looper.loop+1076)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #38 pc 0042d905  /apex/com.android.runtime/lib/libart.so (MterpInvokeStatic+932)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #39 pc 000d2994  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_static+20)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #40 pc 002fd718  /system/framework/framework.jar (android.os.HandlerThread.run+56)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #41 pc 001eea51  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.12892390841156345437+192)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #42 pc 001f3243  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+126)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #43 pc 0041f9cd  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+852)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #44 pc 000dc5a1  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+32)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #45 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #46 pc 00435ee5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+252)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #47 pc 000dffeb  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+178)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #48 pc 00376fcb  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #49 pc 00377d53  /apex/com.android.runtime/lib/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+306)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #50 pc 003a8e8b  /apex/com.android.runtime/lib/libart.so (art::Thread::CreateCallback(void*)+982)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #51 pc 000aa8bb  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   native: #52 pc 00061993  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   at com.mapbox.maps.StyleManager.setStyleGeoJSONSourceData(Native method)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   at com.mapbox.maps.MapboxStyleManager.setStyleGeoJSONSourceData(MapboxStyleManager.kt:1306)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   at com.mapbox.maps.Style.setStyleGeoJSONSourceData(Style.kt:1105)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.setDataAsync$lambda$3$lambda$2(GeoJsonSource.kt:66)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.$r8$lambda$qPu7LtasLBqQGfXFmlkE0vcwtUY(GeoJsonSource.kt:-1)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:-1)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   at android.os.Handler.handleCallback(Handler.java:883)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   at android.os.Handler.dispatchMessage(Handler.java:100)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   at android.os.Looper.loop(Looper.java:214)
2024-12-06 16:15:26.437 13460-13924 nguo.autopilot          com.huanguo.autopilot1               A  runtime.cc:630]   at android.os.HandlerThread.run(HandlerThread.java:67)
