### ISSUE TITLE
App crash on 11.9.0

### ISSUE THREAD

**Issue by ashishp-dev** [mapbox/mapbox-maps-android#2553]
## Environment
Android kotlin

- Android OS version:14
- Devices affected:
- Maps SDK Version:11.9.0

![Screenshot 2024-12-19 at 7 18 30 PM](https://github.com/user-attachments/assets/773167f4-ddc7-414b-92c9-313dba3a5ca2)
![Screenshot 2024-12-19 at 7 18 18 PM](https://github.com/user-attachments/assets/a0ef2d7f-7128-45e0-8939-707cefb33551)

  Process: com.aexdo, PID: 8650
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aexdo/com.aexdo.MapBoxMap.MapBoxMainActivity}: android.view.InflateException: Binary XML file line #18 in com.aexdo:layout/activity_mapbox_main: Binary XML file line #18 in com.aexdo:layout/activity_mapbox_main: Error inflating class com.mapbox.maps.MapView
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4157)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4344)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:222)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2735)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:109)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8828)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #18 in com.aexdo:layout/activity_mapbox_main: Binary XML file line #18 in com.aexdo:layout/activity_mapbox_main: Error inflating class com.mapbox.maps.MapView
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #18 in com.aexdo:layout/activity_mapbox_main: Error inflating class com.mapbox.maps.MapView
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:742)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:894)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:849)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1011)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:972)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1014)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:972)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:570)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:462)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:413)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:751)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
                                                                                                    	at com.aexdo.MapBoxMap.MapBoxMainActivity.onCreate(MapBoxMainActivity.kt:168)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:9019)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8997)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4139)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4344)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:222)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2735)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:109)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8828)
2024-12-19 19:13:14.780  8650-8650  AndroidRuntime          com.aexdo                            E  	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
                                                                                                    Caused by: java.lang.ExceptionInInitializerError
                                                                                                    	at com.mapbox.maps.GlyphsRasterizationOptions$Builder.build(GlyphsRasterizationOptions.java:118)
                                                                                                    	at com.mapbox.maps.MapAttributeParser.parseMapOptions(MapAttributeParser.kt:53)
                                                                                                    	at com.mapbox.maps.MapView.parseTypedArray$maps_sdk_release(MapView.kt:166)
                                                                                                    	at com.mapbox.maps.MapView.<init>(MapView.kt:115)
                                                                                                    	at com.mapbox.maps.MapView.<init>(MapView.kt:94)
                                                                                                    	at com.mapbox.maps.MapView.<init>(MapView.kt:88)
                                                                                                    	... 32 more
                                                                                                    Caused by: com.mapbox.common.MapboxInitializerException: Failed to initialize: Attempt=2, exception=[StartupException], initializer called 107246 ms ago, exception.message=[androidx.startup.StartupException: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~ZD76dqoBnHMwtghuK85PBg==/com.aexdo-ebE1La5alUIIjIRFWOD1yQ==/lib/arm64/libc++_shared.so" program alignment (4096) cannot be smaller than system page size (16384)], exception.cause=[StartupException], exception.cause.message=[androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~ZD76dqoBnHMwtghuK85PBg==/com.aexdo-ebE1La5alUIIjIRFWOD1yQ==/lib/arm64/libc++_shared.so" program alignment (4096) cannot be smaller than system page size (16384)], extractedNativeLibs=[libmapbox-maps.so, libmapbox-common.so, libc++_shared.so, libandroid-tests-support-code.so], isInstantApp=[false], isMainThread=[true]
                                                                                                    	at com.mapbox.common.BaseMapboxInitializer$Companion.init(BaseMapboxInitializer.kt:418)
                                                                                                    	at com.mapbox.common.BaseMapboxInitializer$Companion.init(BaseMapboxInitializer.kt:114)
                                                                                                    	at com.mapbox.common.BaseMapboxInitializer.init(Unknown Source:2)
                                                                                                    	at com.mapbox.maps.GlyphsRasterizationOptions.<clinit>(GlyphsRasterizationOptions.java:135)
                                                                                                    	... 38 more
                                                                                                    Caused by: androidx.startup.StartupException: androidx.startup.StartupException: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~ZD76dqoBnHMwtghuK85PBg==/com.aexdo-ebE1La5alUIIjIRFWOD1yQ==/lib/arm64/libc++_shared.so" program alignment (4096) cannot be smaller than system page size (16384)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:138)
                                                                                                    	at androidx.startup.AppInitializer.initializeComponent(AppInitializer.java:117)
                                                                                                    	at com.mapbox.common.BaseMapboxInitializer$Companion.init(BaseMapboxInitializer.kt:242)
                                                                                                    	... 41 more
                                                                                                    Caused by: androidx.startup.StartupException: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~ZD76dqoBnHMwtghuK85PBg==/com.aexdo-ebE1La5alUIIjIRFWOD1yQ==/lib/arm64/libc++_shared.so" program alignment (4096) cannot be smaller than system page size (16384)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:173)
                                                                                                    	... 44 more
                                                                                                    Caused by: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~ZD76dqoBnHMwtghuK85PBg==/com.aexdo-ebE1La5alUIIjIRFWOD1yQ==/lib/arm64/libc++_shared.so" program alignment (4096) cannot be smaller than system page size (16384)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:173)
                                                                                                    	... 45 more
                                                                                                    Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~ZD76dqoBnHMwtghuK85PBg==/com.aexdo-ebE1La5alUIIjIRFWOD1yQ==/lib/arm64/libc++_shared.so" program alignment (4096) cannot be smaller than system page size (16384)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1110)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1032)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1765)
                                                                                                    	at com.mapbox.common.loader.MapboxLibraryLoader.load(MapboxLibraryLoader.kt:19)
2024-12-19 19:13:14.780  8650-8650  AndroidRuntime          com.aexdo                            E  	at com.mapbox.common.CoreInitializer.create(CoreInitializer.kt:98)
                                                                                                    	at com.mapbox.common.CoreInitializer.create(CoreInitializer.kt:12)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
                                                                                                    	... 46 more

**Comment by ashishp-dev** [comment]
@zugaldia @speps @mourner @sbma44 This is important for me can you please help me??

**Comment by kiryldz** [comment]
If you're running on 16 Kb page [emulator](https://developer.android.com/guide/practices/page-sizes#16kb-emulator) - please use our libraries built with NDK 27 toolchain. The new artifacts are available by appending -ndk27 to the artifact ID (for example, `com.mapbox.maps:android-ndk27:11.7.0`).
