### ISSUE TITLE
Crash when initial camera bearing set programmatically is non-zero

### ISSUE THREAD

**Issue by cramptonism** [mapbox/mapbox-maps-android#282]
## Environment

- Android OS version: API 30
- Devices affected: Emulator and Pixel 5
- Maps SDK Version: 10.0.0-beta.17

## Observed behavior and steps to reproduce

I was unable to reproduce this in the sample app, but looking at the stack trace it's pretty clear there is an undesirable code path triggering this crash.

```
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8804)
        at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:4612)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
        at android.view.View.setFlags(View.java:16122)
        at android.view.View.setVisibility(View.java:11719)
        at android.widget.ImageView.setVisibility(ImageView.java:1685)
        at com.mapbox.maps.plugin.compass.CompassViewImpl.setCompassVisible(CompassViewImpl.kt:66)
        at com.mapbox.maps.plugin.compass.CompassViewPlugin.updateVisibility(CompassViewPlugin.kt:243)
        at com.mapbox.maps.plugin.compass.CompassViewPlugin.updateVisibility$default(CompassViewPlugin.kt:224)
        at com.mapbox.maps.plugin.compass.CompassViewPlugin.update(CompassViewPlugin.kt:221)
        at com.mapbox.maps.plugin.compass.CompassViewPlugin.onCameraMove(CompassViewPlugin.kt:182)
        at com.mapbox.maps.plugin.MapPluginRegistry.onCameraMove(MapPluginRegistry.kt:146)
        at com.mapbox.maps.MapController$1.onCameraChanged(MapController.kt:64)
        at com.mapbox.maps.NativeObserver.notify(NativeObserver.kt:42)
        at com.mapbox.maps.Map.setSize(Native Method)
        at com.mapbox.maps.NativeMapImpl.setSize(NativeMapImpl.kt:14)
        at com.mapbox.maps.renderer.MapboxRenderer.onSurfaceChanged(MapboxRenderer.kt:66)
        at com.mapbox.maps.renderer.MapboxRenderThread.prepareEglSurface(MapboxRenderThread.kt:134)
        at com.mapbox.maps.renderer.MapboxRenderThread.checkSurfaceReady(MapboxRenderThread.kt:94)
        at com.mapbox.maps.renderer.MapboxRenderThread.prepareRenderFrame(MapboxRenderThread.kt:213)
        at com.mapbox.maps.renderer.MapboxRenderThread.access$prepareRenderFrame(MapboxRenderThread.kt:26)
        at com.mapbox.maps.renderer.MapboxRenderThread$onSurfaceCreated$$inlined$withLock$lambda$1.invoke(MapboxRenderThread.kt:277)
        at com.mapbox.maps.renderer.MapboxRenderThread$onSurfaceCreated$$inlined$withLock$lambda$1.invoke(MapboxRenderThread.kt:26)
        at com.mapbox.maps.renderer.WorkerHandlerThread$post$$inlined$let$lambda$1.run(WorkerHandlerThread.kt:17)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

## Expected behavior

No crash on startup

## Notes / preliminary analysis

When I was debugging this, I see a `ViewGroup.setVisibility` call being triggered from the MapboxRenderThread, which causes the crash above since the CompassView is created on the main thread.

When debugging in my app, the `updateVisibility` method in CompassViewPlugin is called a few times. The first couple times the bearing is 0 (my code to change camera position has not run yet) so `shouldHideCompass` returns true. Then when `onSurfaceCreated` is triggered, the camera bearing is non-zero and this code path is executed, setting the compass to be visible on a non-main thread.

**Comment by cramptonism** [comment]
Note: my current workaround is to disable the compass plugin until OnMapLoaded callback is reached.

**Comment by kiryldz** [comment]
Although that seems to be a pretty straight-forward fix but generally I see several issues and they will be fixed so @cramptonism thanks for pointing it out!

**Comment by tobrun** [comment]
This was fixed, thank you for the report
