### ISSUE TITLE
Test app crash while no location permission 

### ISSUE THREAD

**Issue by Chaoba** [mapbox/mapbox-maps-android#284]
## Environment

- Android OS version Android 10:
- Devices affected OPPO PBEM00:
- Maps SDK Version v10.0.0-beta.18:

## Observed behavior and steps to reproduce
Remove the location permission in application permission setting
Open the "location component" example in test app, then it will crash with the following stacks
```
<!--- Please include as much evidence as possible (traces, videos, screenshots etc） --->
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at android.os.Parcel.createException(Parcel.java:2087)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at android.os.Parcel.readException(Parcel.java:2055)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at android.os.Parcel.readException(Parcel.java:2003)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:1263)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1031)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at android.location.LocationManager.requestLocationUpdates(LocationManager.java:592)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.mapbox.android.core.location.AndroidLocationEngineImpl.requestLocationUpdates(AndroidLocationEngineImpl.java:74)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.requestLocationUpdates(MapboxFusedLocationEngineImpl.java:50)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.requestLocationUpdates(MapboxFusedLocationEngineImpl.java:22)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.mapbox.android.core.location.LocationEngineProxy.requestLocationUpdates(LocationEngineProxy.java:34)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.mapbox.maps.plugin.locationcomponent.LocationProviderImpl.requestLocationUpdates(LocationProviderImpl.kt:31)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.mapbox.maps.plugin.locationcomponent.LocationProviderImpl.registerLocationConsumer(LocationProviderImpl.kt:76)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.mapbox.maps.plugin.locationcomponent.LocationComponentPluginImpl$activateLocationComponent$1.invoke(LocationComponentPluginImpl.kt:193)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.mapbox.maps.plugin.locationcomponent.LocationComponentPluginImpl$activateLocationComponent$1.invoke(LocationComponentPluginImpl.kt:26)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.mapbox.maps.plugin.MapDelegateProviderImpl$getStyle$1.onStyleLoaded(MapDelegateProviderImpl.kt:21)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.mapbox.maps.MapboxMap.onFinishLoadingStyle$sdk_debug(MapboxMap.kt:213)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.mapbox.maps.MapboxMap$initializeStyleLoad$3.onStyleDataLoaded(MapboxMap.kt:191)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.mapbox.maps.NativeObserver.notify(NativeObserver.kt:56)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:336)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at android.os.Looper.loop(Looper.java:184)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7798)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err: Caused by: android.os.RemoteException: Remote stack trace:
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.android.server.LocationManagerService.checkResolutionLevelIsSufficientForProviderUseLocked(LocationManagerService.java:2250)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at com.android.server.LocationManagerService.requestLocationUpdates(LocationManagerService.java:2942)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:521)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at android.os.Binder.execTransactInternal(Binder.java:1021)
2021-04-23 11:13:21.536 19618-19618/com.mapbox.maps.testapp W/System.err:     at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by Chaoba** [comment]
Fixed in https://github.com/mapbox/mapbox-maps-android/pull/333
