### ISSUE TITLE
Disabled plugins should not be invoked in callbacks.

### ISSUE THREAD

**Issue by Chaoba** [mapbox/mapbox-maps-android#289]
Currently when there is a callback being invoked like `onSizeChanged`，`onCameraMove`,`onStyleChanged` etc. all the callbacks in related plugins will be invoked. However it make no sense for disabled plugins and could cause potential bugs. For example, while disable location plugin the following crash may happen
```
2021-04-26 15:29:35.507 21726-21726/com.mapbox.maps.metrics W/LocationUpdateReceiver: LocationEngineResult == null
2021-04-26 15:29:35.517 21726-21855/com.mapbox.maps.metrics I/maps: {MapboxRenderThr}[General]: GPU Identifier: Adreno (TM) 615
2021-04-26 15:29:35.895 21726-21726/com.mapbox.maps.metrics W/System.err: java.lang.AbstractMethodError: abstract method "void com.mapbox.maps.plugin.MapStyleObserverPlugin.onStyleChanged(com.mapbox.maps.extension.style.StyleInterface)"
2021-04-26 15:29:35.896 21726-21726/com.mapbox.maps.metrics W/System.err:     at com.mapbox.maps.plugin.MapPluginRegistry.onStyleChanged(MapPluginRegistry.kt:167)
2021-04-26 15:29:35.896 21726-21726/com.mapbox.maps.metrics W/System.err:     at com.mapbox.maps.MapController$2$1.onStyleLoaded(MapController.kt:70)
2021-04-26 15:29:35.896 21726-21726/com.mapbox.maps.metrics W/System.err:     at com.mapbox.maps.MapboxMap.onFinishLoadingStyle$sdk_release(MapboxMap.kt:213)
2021-04-26 15:29:35.896 21726-21726/com.mapbox.maps.metrics W/System.err:     at com.mapbox.maps.MapboxMap$initializeStyleLoad$3.onStyleDataLoaded(MapboxMap.kt:191)
2021-04-26 15:29:35.896 21726-21726/com.mapbox.maps.metrics W/System.err:     at com.mapbox.maps.NativeObserver.notify(NativeObserver.kt:56)
2021-04-26 15:29:35.896 21726-21726/com.mapbox.maps.metrics W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2021-04-26 15:29:35.896 21726-21726/com.mapbox.maps.metrics W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:336)
2021-04-26 15:29:35.896 21726-21726/com.mapbox.maps.metrics W/System.err:     at android.os.Looper.loop(Looper.java:184)
2021-04-26 15:29:35.896 21726-21726/com.mapbox.maps.metrics W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7798)
2021-04-26 15:29:35.896 21726-21726/com.mapbox.maps.metrics W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-04-26 15:29:35.896 21726-21726/com.mapbox.maps.metrics W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2021-04-26 15:29:35.896 21726-21726/com.mapbox.maps.metrics W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
2021-04-26 15:29:35.897 21726-21726/com.mapbox.maps.metrics E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException
2021-04-26 15:29:35.897 21726-21726/com.mapbox.maps.metrics A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 21726 (ox.maps.metrics), pid 21726 (ox.maps.metrics)

```

**Comment by tobrun** [comment]
Can we reproduce with a test? so we can regressions when anything changes?

**Comment by Chaoba** [comment]
We can't reproduce this with CI in https://github.com/mapbox/mobile-metrics/pull/637. Guess maybe it's related with google location because there is no google service on my device. Will dig into it further.

**Comment by Chaoba** [comment]
The root cause for the crash is that there is plugin-location.aar locally and we still have the [codes](https://github.com/mapbox/mapbox-maps-android/blob/0729bbad1ff9994c62507a261b51c1f2aa312361/sdk/src/main/java/com/mapbox/maps/MapController.kt#L319) to load this plugin .
Create another [ticket](https://github.com/mapbox/mapbox-maps-android/issues/294) to track removing plugin location completely.
