### ISSUE TITLE
Mapbox SDK corrupting SQLite database

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-maps-android#309]
@dlmcauslan We’ve moved your original issue into a private repo. However, since you can’t comment/follow there, I’m reproducing your original issue here. Apologies for the confusion.

---

## Environment

- Android OS version: 10
- Devices affected: Samsung Galaxy Tab Active Pro (SM-T545), Samsung Galaxy Tab Active 3 (SM-T575)
- Maps SDK Version: 10.0.0-beta.15 and newer

## Observed behavior and steps to reproduce

Using a version of the Mapbox SDK that is newer than 10.0.0-beta.15 can cause the local SQLite database of our app to become corrupted. This is not an issue on versions 10.0.0-beta.14 and older.

To repoduce:
- Do a complete uninstall, and fresh install of our app.
- Rapidly zoom in and out on the map to cause a large number of tile requests.
- Eventually (usually within one minute - although it depends on how often the app is accessing it's local database) the app will completely crash with the following stack trace:

```
W/SQLiteLog: (28) lockBtree: nPageHeader 1284780726, nPageFile 74, dbFileVers: 1016617649 235012096
E/SQLiteLog: (11) Invalid MagicHeader!
E/SQLiteLog: (11) Corrupt in lockBtree: rc 26, nPageHeader 1284780726, nPageFile 74
D/SQLiteConnection: Corruption detected - isPrimary: true, address: @fa8b610
E/DefaultDatabaseErrorHandler: Corruption reported by sqlite on database: /data/user/0/com.tracmap.myapp/databases/my_app_database.db
E/SQLiteDatabase: DB wipe detected: package=com.tracmap.myapp reason=corruption file=/data/user/0/com.tracmap.myapp/databases/my_app_database.db ctime=2021-05-03T22:22:09Z mtime=2021-05-03T22:22:09Z atime=2021-05-03T22:13:33Z checkfile [unable to obtain timestamp]
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 28779 (al.myapp), pid 28779 (al.myapp)
```

## Expected behavior

Mapbox should not be able to corrupt the app's local database.

The Magic Header should be ```53 51 4c 69 74 65 20 66 6f 72 6d 61 74 20 33 00```. This byte sequence corresponds to the UTF-8 string "SQLite format 3" including the nul terminator character at the end.
[https://www.sqlite.org/fileformat.html](https://www.sqlite.org/fileformat.html)
## Notes / preliminary analysis

Analysing the header bytes of the datbase file after corruption we get ```53 51 4C 69 74 14 03 03 00 01 01 17 03 03 00 13``` which corresponds to the UTF-8 string "SQLit".

So it appears that somehow making lots of tile requests is corrupting the actual database file itself, or overwriting some of its bytes.

**Comment by kkaefer** [comment]
@dlmcauslan Thanks for taking the time to post this issue. There could be a few things that are going on. Is my understanding correct that use of the Mapbox SDK corrupts _another_ database in your app?

> Using a version of the Mapbox SDK that is newer than 10.0.0-beta.15

Which version are you using _exactly_? Do you mean newer than `10.0.0-beta.15`, or newer or equal than `10.0.0-beta.15`? 

Does this behavior also occur with the current `10.0.0-beta.18`?  Starting with `10.0.0-beta.17`, we’ve changed the way we link the various components to sidestep issues with differing libc++ versions on various Android NDKs. This is also affecting our internal copy of SQLite3.

If this _does_ occur with with `10.0.0-beta.17` and later, could you please describe how you’re accessing the SQLite database? Do you link a copy of SQLite C library into your app or are you using the Android/Java interface? From the log you posted, it seems like the latter is the case.

**Comment by dlmcauslan** [comment]
@kkaefer thanks for your quick reply. Yes you are correct, using the Mapbox SDK is corrupting another database in our app (not the mapbox database).

I have tested on a number of different versions, both `10.0.0-beta.12` and `10.0.0-beta.14` are fine. Using `10.0.0-beta.15` and `10.0.0-beta.18` both have resulted in our app database being corrupted.

We are accessing the database using the Android/Java interface using the Anko SQLite library, which is basically just a simple kotlin wrapper around the Android SQLiteDatabase class:
[https://github.com/Kotlin/anko/wiki/Anko-SQLite](https://github.com/Kotlin/anko/wiki/Anko-SQLite)

As far as I can tell the database corruption seems to occur when we are accessing our database, at the same time as Mapbox is making a large number of requests (~10 per second).

**Comment by kiryldz** [comment]
> @kkaefer thanks for your quick reply. Yes you are correct, using the Mapbox SDK is corrupting another database in our app (not the mapbox database).
> 
> I have tested on a number of different versions, both `10.0.0-beta.12` and `10.0.0-beta.14` are fine. Using `10.0.0-beta.15` and `10.0.0-beta.18` both have resulted in our app database being corrupted.
> 
> We are accessing the database using the Android/Java interface using the Anko SQLite library, which is basically just a simple kotlin wrapper around the Android SQLiteDatabase class:
> https://github.com/Kotlin/anko/wiki/Anko-SQLite
> 
> As far as I can tell the database corruption seems to occur when we are accessing our database, at the same time as Mapbox is making a large number of requests (~10 per second).

@dlmcauslan is it possible for you to create a very-very simple sample app as you described (using same basic config, Mapbox Maps version, Anko etc) and see if this issue with corrupting DB is reproducible there. If it is - I would be grateful if you could share that sample code so that we could move things faster from our side. Thanks!

**Comment by kkaefer** [comment]
@dlmcauslan I’ve tried to replicate this issue by creating a sample app with `com.mapbox.maps:android:10.0.0-beta.18`, and `org.jetbrains.anko:anko-sqlite:0.10.8`. The app creates a map view, and opens a database where it inserts a new row every second. I’ve tested this both in regular mode, and with `ResourceOptions.loadTilePacksFromNetwork` set to `true`. Even after panning around (which causes more database operations as we load more data and store it in the cache), I couldn’t trigger a corruption event.

I’ve tested this with the emulator, and a physical Google Pixel XL, both running Android 10.

**Comment by kkaefer** [comment]
- Are you using `ResourceOptions.loadTilePacksFromNetwork`? This option used to default to true in earlier versions, but defaults to false in the current beta.18.
  - `SEGV_MAPERR` points to an issue with memory mapping, which we’re using when this option is enabled.
  - Do you use any other code in your app that uses memory mapping?
- Did you trying uninstalling + reinstalling the app, thereby clearing the data? Does the error still occur with a fresh install?

> at the same time as Mapbox is making a large number of requests (~10 per second).

How are you assessing that Mapbox is making a large number of requests?

**Comment by dlmcauslan** [comment]
@kiryldz @kkaefer thanks for your help so far.
I have created a sample app that reproduces this issue on a Samsung Galaxy Tab Active running Android 10.
[https://github.com/tracmap/mapbox_test_app](https://github.com/tracmap/mapbox_test_app)

The easiest way to reproduce the corruption is to pan the map rapidly. Here is a link to a video that I have recorded showing this behaviour:
[https://drive.google.com/file/d/1EmV8PfVBuv_Nau_ShmdJ0HqcxLFfKYgd/view?usp=sharing](https://drive.google.com/file/d/1EmV8PfVBuv_Nau_ShmdJ0HqcxLFfKYgd/view?usp=sharing)

- I expect that the difference between the sample app you created and the one that I created is that you were inserting a new row into the database every second, whilst in my test app I am inserting a row into the database every 20ms (I can increase this up to 100ms and still reliably recreate the issue). 

- I am not using `ResourceOptions.loadTilePacksFromNetwork`. In the sample app I have created I can reproduce the issue using all the default Mapbox Settings. I don't have any code in my app which uses memory mapping.

- I have uninstalled and reinstalled the app many times, and I can reliably reproduce the corruption each time.

- I have assessed that Mapbox is making a large number of requests by setting Logcat to Verbose. I then get a large number of messages like this:
```
2021-05-07 13:35:50.183 1346-1458/com.tracmap.mapboxtestapp V/MapboxHttpCallback: [HTTP] Request was successful (code = 200).
2021-05-07 13:35:50.203 1346-1475/com.tracmap.mapboxtestapp V/MapboxHttpCallback: [HTTP] Request was successful (code = 200).
2021-05-07 13:35:50.210 1346-1450/com.tracmap.mapboxtestapp V/MapboxHttpCallback: [HTTP] Request was successful (code = 200).
2021-05-07 13:35:50.216 1346-1446/com.tracmap.mapboxtestapp V/MapboxHttpCallback: [HTTP] Request was successful (code = 200).
2021-05-07 13:35:50.216 1346-1459/com.tracmap.mapboxtestapp V/MapboxHttpCallback: [HTTP] Request was successful (code = 200).
2021-05-07 13:35:50.518 1346-1474/com.tracmap.mapboxtestapp V/MapboxHttpCallback: [HTTP] Request was successful (code = 200).
2021-05-07 13:35:50.522 1346-1475/com.tracmap.mapboxtestapp V/MapboxHttpCallback: [HTTP] Request was successful (code = 200).
2021-05-07 13:35:50.529 1346-1458/com.tracmap.mapboxtestapp V/MapboxHttpCallback: [HTTP] Request was successful (code = 200).
2021-05-07 13:35:50.557 1346-1459/com.tracmap.mapboxtestapp V/MapboxHttpCallback: [HTTP] Request was successful (code = 200).
2021-05-07 13:35:50.579 1346-1450/com.tracmap.mapboxtestapp V/MapboxHttpCallback: [HTTP] Request was successful (code = 200).
2021-05-07 13:35:50.872 1346-1446/com.tracmap.mapboxtestapp V/MapboxHttpCallback: [HTTP] Request was successful (code = 200).
2021-05-07 13:35:50.931 1346-1475/com.tracmap.mapboxtestapp V/MapboxHttpCallback: [HTTP] Request was successful (code = 200).
2021-05-07 13:35:50.960 1346-1474/com.tracmap.mapboxtestapp V/MapboxHttpCallback: [HTTP] Request was successful (code = 200).

```

**Comment by dlmcauslan** [comment]
I have done further testing with my sample app to see what devices I can reproduce the issue on:

**Have been able to reproduce database corruption**
- Samsung Galaxy Tab Active Pro - Android 10
- Samsung Galaxy Tab Active 3 - Android 10
- Huawei Nova 5T - Android 10
- Emulator - Android 10 

**Have NOT been able to reproduce database corruption**
- Samsung Galaxy Tab A (2016) - Android 8.1
- Emulator - Android 9
- Emulator - Android 8.1

**Comment by kiryldz** [comment]
@dlmcauslan thanks for that huge effort, that is very helpful!

I've replicated your example to sample activity in this repo https://github.com/mapbox/mapbox-maps-android/compare/kdz-corrupt-db-issue?expand=1 (cc @pozdnyakov @kkaefer) and followed your instructions precisely but I can't get a crash 😞 

I was testing on following devices:

 - Xiaomi Mi 9 - Android 10
 - Samsung S20 Ultra 5G - Android 11

Could you please check check the activity from branch ☝️ on your devices and see if you will see a crash?

**Comment by kkaefer** [comment]
@dlmcauslan thanks for creating this example. I’ve used your sample project on these devices:

- Google Pixel C, Android 8.1.0, API 27
- Google Pixel XL, Android 10, API 29
- Emulator (Pixel 2), Android 10, API 29
- Samsung Galaxy S7, Android 8.0.0, API 26
- Motorola Moto G (2nd gen), Android 6.0, API 23

but couldn't provoke a crash; logcat also doesn’t show anything suspicious, just many `Inserting into database` log messages.

**Comment by kkaefer** [comment]
@dlmcauslan which Android SDK + NDK are you using?

**Comment by dlmcauslan** [comment]
@kkaefer @kiryldz it is very strange that you are both unable to reproduce the issue. I can consistently reproduce it on a range of Android 10 devices, building the app from several different computers (they are all running Ubuntu). If it helps, I do find it easier to reproduce the issue when the device is in Landscape mode - although this isn't required.

To make it easier to diagnose I have pushed a new commit to
[https://github.com/tracmap/mapbox_test_app](https://github.com/tracmap/mapbox_test_app)
which simulates panning the map rapidly making it easier to reproduce the database corruption errors. You should be able to build that on an Android 10 device, and within 60s of the app running you should get errors in log cat as shown below:

```
2021-05-08 10:53:20.483 10956-11099/com.tracmap.mapboxtestapp E/SQLiteLog: (26) statement aborts at 2: [CREATE TABLE IF NOT EXISTS android_metadata (locale TEXT)] file is not a database
2021-05-08 10:53:20.486 10956-11099/com.tracmap.mapboxtestapp E/SQLiteDatabase: Database corruption detected in open()
    android.database.sqlite.SQLiteDatabaseCorruptException: file is not a database (Sqlite code 26 SQLITE_NOTADB), (OS error - 2:No such file or directory)
        at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
        at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:692)
        at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:475)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:241)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:211)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:559)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:222)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:211)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:947)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:926)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:779)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:389)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:332)
        at org.jetbrains.anko.db.ManagedSQLiteOpenHelper.openDatabase(Database.kt:186)
        at org.jetbrains.anko.db.ManagedSQLiteOpenHelper.use(Database.kt:177)
        at com.tracmap.mapboxtestapp.MainActivity$insertTestDataIntoDatabase$1.invokeSuspend(MainActivity.kt:41)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-05-08 10:53:20.486 10956-11099/com.tracmap.mapboxtestapp E/DefaultDatabaseErrorHandler: Corruption reported by sqlite on database: /data/user/0/com.tracmap.mapboxtestapp/databases/test_database
2021-05-08 10:53:20.501 10956-11099/com.tracmap.mapboxtestapp E/SQLiteDatabase: DB wipe detected: package=com.tracmap.mapboxtestapp reason=corruption file=/data/user/0/com.tracmap.mapboxtestapp/databases/test_database ctime=2021-05-07T22:53:20Z mtime=2021-05-07T22:53:20Z atime=2021-05-07T22:35:24Z checkfile [unable to obtain timestamp]
    java.lang.Throwable: STACKTRACE
        at android.database.sqlite.SQLiteDatabase.wipeDetected(SQLiteDatabase.java:2883)
        at android.database.DefaultDatabaseErrorHandler.onCorruption(DefaultDatabaseErrorHandler.java:60)
        at android.database.sqlite.SQLiteDatabase.onCorruption(SQLiteDatabase.java:420)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:930)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:779)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:389)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:332)
        at org.jetbrains.anko.db.ManagedSQLiteOpenHelper.openDatabase(Database.kt:186)
        at org.jetbrains.anko.db.ManagedSQLiteOpenHelper.use(Database.kt:177)
        at com.tracmap.mapboxtestapp.MainActivity$insertTestDataIntoDatabase$1.invokeSuspend(MainActivity.kt:41)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-05-08 10:53:20.505 10956-11099/com.tracmap.mapboxtestapp E/DefaultDatabaseErrorHandler: deleting the database file: /data/user/0/com.tracmap.mapboxtestapp/databases/test_database
```

@kkaefer I am devloping on Android SDK 30, using Android SDK Build-Tools 31-rc3, Android SDK Platform-Tools 31.0.2, Android Emulator 30.6.5. I do not have the NDK installed (I am not doing any native development).

**Comment by dlmcauslan** [comment]
@kkaefer @kiryldz have you managed to make any progress reproducing the issue in the new version of [https://github.com/tracmap/mapbox_test_app](https://github.com/tracmap/mapbox_test_app) that I created?

**Comment by kiryldz** [comment]
@dlmcauslan I was able to reproduce a crash in your sample app from https://github.com/tracmap/mapbox_test_app. Sometimes it takes more than 60 sec but indeed it happens. 
Could you please run same example of yours but from our public repo here: https://github.com/mapbox/mapbox-maps-android/compare/kdz-corrupt-db-issue?expand=1 (I've basically copied your code there).
I can't get that crash there with same code, it would be very interesting if you will see it there.

cc @kkaefer

**Comment by dlmcauslan** [comment]
@kiryldz that sounds very strange that you cannot reproduce the issue when it is copied into the mapbox public repo. I wouldn't have thought that would make a difference. 
Can you leave the app running for a long time to see if the issue occurs? It doesn't always crash the app, but it should show database corruption errors in Logcat eventually - I suggest setting the Logcat filter to only show ERROR logs.
To make it easier to reproduce you could also try decreasing `DATABASE_INSERT_DELAY_MS` as it should make the issue occur more frequently. Perhaps try 5 ms?

I have tried to check out https://github.com/mapbox/mapbox-maps-android/compare/kdz-corrupt-db-issue?expand=1 and run it locally; however, I can not get the SDK to build. I get thse errors:
```
Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.pom'. Received status code 403 from server: Forbidden
```

I followed the steps in the `DEVELOPING.md` guide in the repo, but it does help. It looks like this is an existing issue (https://github.com/mapbox/mapbox-maps-android/issues/320) so I can't progress much further unless this is resolved, or you can give some advice on how to perform a successful gradle sync on the repo.

**Comment by viktor76525** [comment]
Is there someone available to have another look at this issue?
I have created an `updated` branch on the test app repo https://github.com/tracmap/mapbox_test_app
It is still happening in v10.9.1 and it's quite a serious issue.
It's very fast to reproduce on a Samsung Active Pro with Android 10 (crash.txt).
It happens within the hour running on an Android 10 emulator (crash-android-10-emulator.txt).

The issue seems to always be surrounded by mapbox errors in logs `E/Mapbox: [maps-core]`.
In our real device crash log:

1. The apps own database header is overwritten (as mentioned above) with "14 03 03 00 01 01 17 03 03 00 13". Note that this seems to be related to TLS.
2. E/Mapbox: [maps-core]: {MapboxRenderThr}[Style]: Failed to load tile 13/5535/2974=>13 for source mapbox: **Handshake failed**

I'm not sure how Mapbox is managing to dump TLS data into the apps DB instead of reading it.

Then there's the emulator crash.

1. W/Mapbox: [maps-core]: {TileStoreFileSo}[Database](10): Can't write resource: disk I/O error
2. E/SQLiteDatabase: DB wipe detected: package=com.tracmap.mapboxtestapp reason=corruption file=/data/user/0/com.tracmap.mapboxtestapp/databases/test_database ctime=2022-11-29T02:28:36Z mtime=2022-11-29T02:28:36Z atime=2022-11-29T02:12:26Z checkfile [unable to obtain timestamp]

Strange as well.

[crash.txt](https://github.com/mapbox/mapbox-maps-android/files/10109275/crash.txt)
[crash-android-10-emulator.txt](https://github.com/mapbox/mapbox-maps-android/files/10109276/crash-android-10-emulator.txt)
