### ISSUE TITLE
OutOfMemoryError on instantiating GeoJsonSource with too many features (17000)

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#341]
## Environment

- Android OS version: 11
- Devices affected: Samsung Galaxy S20+
- Maps SDK Version: android-v10.0.0-beta.19

```
W/System.err: java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 25165824 free bytes and 110MB until OOM, target footprint 446596280, growth limit 536870912
W/System.err:     at java.util.Arrays.copyOf(Arrays.java:3257)
W/System.err:     at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
W/System.err:     at java.lang.StringBuffer.append(StringBuffer.java:270)
W/System.err:     at java.io.StringWriter.write(StringWriter.java:112)
        at com.google.gson.stream.JsonWriter.string(JsonWriter.java:590)
        at com.google.gson.stream.JsonWriter.value(JsonWriter.java:418)
W/System.err:     at com.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:746)
        at com.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:760)
        at com.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:698)
        at com.google.gson.internal.bind.TypeAdapters$35$1.write(TypeAdapters.java:890)
W/System.err:     at com.mapbox.geojson.Feature$GsonTypeAdapter.write(Feature.java:568)
        at com.mapbox.geojson.Feature$GsonTypeAdapter.write(Feature.java:497)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
        at com.mapbox.geojson.FeatureCollection$GsonTypeAdapter.write(FeatureCollection.java:328)
        at com.mapbox.geojson.FeatureCollection$GsonTypeAdapter.write(FeatureCollection.java:278)
        at com.google.gson.Gson.toJson(Gson.java:704)
        at com.google.gson.Gson.toJson(Gson.java:683)
        at com.google.gson.Gson.toJson(Gson.java:638)
        at com.google.gson.Gson.toJson(Gson.java:618)
        at com.mapbox.geojson.FeatureCollection.toJson(FeatureCollection.java:223)
        at com.mapbox.maps.extension.style.utils.TypeUtilsKt.toValue(TypeUtils.kt:306)
        at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource$Builder.featureCollection(GeoJsonSource.kt:820)
        at com.nobelsystems.geoviewermobile.util.MapboxUtilKt$addGeoJsonSource$1.invoke(MapboxUtil.kt:395)
        at com.nobelsystems.geoviewermobile.util.MapboxUtilKt$addGeoJsonSource$1.invoke(MapboxUtil.kt:393)
        at com.mapbox.maps.extension.style.sources.generated.GeoJsonSourceKt.geoJsonSource(GeoJsonSource.kt:1122)
        at com.nobelsystems.geoviewermobile.util.MapboxUtilKt.addGeoJsonSource(MapboxUtil.kt:393)
        at com.nobelsystems.geoviewermobile.ui.map.MapFragment$onStyleLoaded$3$invokeSuspend$lambda-3$$inlined$observe$default$1$1.emit(Collect.kt:145)
        at com.nobelsystems.geoviewermobile.ui.map.MapFragment$onStyleLoaded$3$invokeSuspend$lambda-3$$inlined$observe$default$1$1$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by VincentJoshuaET** [comment]
This is because the final string is too large. I tried writing to a file but it says that:  java.lang.RuntimeException: Add source failed: 0 - Invalid value.

**Comment by tobrun** [comment]
>  tried writing to a file but it says that: java.lang.RuntimeException: Add source failed: 0 - Invalid value.

Could you add the code how you are trying to do that? 
To load a file through a geojsonsource your uri should match the following structure:
```
file://path/to/file/foobar.geojson
```

**Comment by VincentJoshuaET** [comment]
> > tried writing to a file but it says that: java.lang.RuntimeException: Add source failed: 0 - Invalid value.
> 
> Could you add the code how you are trying to do that?
> To load a file through a geojsonsource your uri should match the following structure:
> 
> ```
> file://path/to/file/foobar.geojson
> ```

Thanks. It now works for me. But having 17417 features in a geojson file still crashed the app.

Im getting this log:
```
I/scudo:   25 ( 11664): mapped:   1024K popped:     132 pushed:      83 inuse:     49 total:     83 rss:      0K releases:    108 last released:    312K region: 0x6ee7949000 (0x6ee7939000)
      26 ( 14224): mapped:   1280K popped:     205 pushed:     139 inuse:     66 total:     77 rss:      0K releases:     60 last released:    120K region: 0x6ef7941000 (0x6ef7939000)
      27 ( 16400): mapped:   1792K popped:     426 pushed:     328 inuse:     98 total:    111 rss:      0K releases:     60 last released:    156K region: 0x6f07943000 (0x6f07939000)
      28 ( 18448): mapped:   1536K popped:      85 pushed:      23 inuse:     62 total:     79 rss:      0K releases:     59 last released:    264K region: 0x6f17943000 (0x6f17939000)
      29 ( 23056): mapped:   2304K popped:     109 pushed:      29 inuse:     80 total:    102 rss:      0K releases:     61 last released:    456K region: 0x6f27941000 (0x6f27939000)
      30 ( 29456): mapped:   2048K popped:     169 pushed:     102 inuse:     67 total:     70 rss:      0K releases:     30 last released:     48K region: 0x6f37941000 (0x6f37939000)
      31 ( 33296): mapped:   2304K popped:     557 pushed:     493 inuse:     64 total:     70 rss:      0K releases:     55 last released:    192K region: 0x6f47946000 (0x6f47939000)
      32 ( 65552): mapped:   8448K popped:     255 pushed:     137 inuse:    118 total:    131 rss:      0K releases:     66 last released:    728K region: 0x6f5793b000 (0x6f57939000)
      33 ( 98320): mapped:   2560K popped:      38 pushed:      16 inuse:     22 total:     26 rss:      0K releases:      8 last released:    284K region: 0x6f67946000 (0x6f67939000)
      34 (131088): mapped:  65024K popped:     554 pushed:     506 inuse:     48 total:    507 rss:      0K releases:     22 last released:  59360K region: 0x6f77941000 (0x6f77939000)
      35 (163856): mapped:   1536K popped:      10 pushed:       1 inuse:      9 total:      9 rss:      0K releases:      2 last released:    312K region: 0x6f87948000 (0x6f87939000)
      36 (196624): mapped:   4096K popped:      28 pushed:       9 inuse:     19 total:     21 rss:      0K releases:      4 last released:    188K region: 0x6f97942000 (0x6f97939000)
      37 (229392): mapped:   2816K popped:      20 pushed:       8 inuse:     12 total:     12 rss:      0K releases:      3 last released:    448K region: 0x6fa793e000 (0x6fa7939000)
      38 (262160): mapped:   6400K popped:      32 pushed:       8 inuse:     24 total:     24 rss:      0K releases:      2 last released:    252K region: 0x6fb793b000 (0x6fb7939000)
    Scudo OOM: The process has Exhausted 256M for size class 3120.
```

**Comment by tobrun** [comment]
@VincentJoshuaET scale of this amount of data should imo be handled differently. It should be tiled into vector tiles:
 - https://docs.mapbox.com/help/getting-started/uploading-data/

**Comment by VincentJoshuaET** [comment]
> @VincentJoshuaET scale of this amount of data should imo be handled differently. It should be tiled into vector tiles:
> 
> * https://docs.mapbox.com/help/getting-started/uploading-data/

Is there another way to use this data without uploading? I cannot do that for my app.

**Comment by VincentJoshuaET** [comment]
Will this ever be possible? There seems to be no issue doing this on iOS.

**Comment by kiryldz** [comment]
@VincentJoshuaET can you please try loading geojson with a lot of features with latest release? We are now using worker thread to parse data, perhaps now it will not lead to out of memory exception.

**Comment by VincentJoshuaET** [comment]
> @VincentJoshuaET can you please try loading geojson with a lot of features with latest release? We are now using worker thread to parse data, perhaps now it will not lead to out of memory exception.

It still crashes. What seems to be the problem is that Java cannot parse a string very large; see my error in the original post. Maybe Mapbox can do something that does not do that. Even loading from a file has this problem.

**Comment by kiryldz** [comment]
Yep, I see now. 
Well, in that case the only option I see is either handle data differently as @tobrun proposed 👆 or try to split single feature collection in several ones and load as separate sources (and apply same layers to them). That way it should load OK and in the end look as you expect I believe.

**Comment by VincentJoshuaET** [comment]
> Yep, I see now.
> Well, in that case the only option I see is either handle data differently as @tobrun proposed 👆 or try to split single feature collection in several ones and load as separate sources (and apply same layers to them). That way it should load OK and in the end look as you expect I believe.

Using your second solution still crashed my app with no error: `Waiting for a blocking GC Alloc`

I cannot use the first solution because I'm fetching my features from a Couchbase database and I also do not have the authority to upload those data to Mapbox. Maybe is it possible to directly load the file? Currently even loading the file still crashes the app.

**Comment by VincentJoshuaET** [comment]
My current solution is just to show the most recent 2500 layers, which is very few compared to 17K.

**Comment by VincentJoshuaET** [comment]
Closing this. I opted not to include all properties unnecessary and just include the latlng, and about 5 properties.
