### ISSUE TITLE
Setting sync data to geojson may be overwritten by async data

### ISSUE THREAD

**Issue by kiryldz** [mapbox/mapbox-maps-android#481]
## Environment

- Android OS version: any
- Devices affected: any
- Maps SDK Version: v10.0.0-rc.3

## Observed behavior and steps to reproduce

Create and then update geojson source using following code:
```
mapboxMap.loadStyleUri(Style.MAPBOX_STREETS) { style ->
// not exactly empty but for better understanding
val source = geoJsonSource("source") {
featureCollection(FeatureCollection.fromFeatures(emptyList()))
}
style.addSource(source)
val layer = circleLayer("layer", "source") {
// some properties
}
style.addLayer(layer)
// update source in a sync manner with any feature
style.getSourceAs<GeoJsonSource>("source")!!
.featureCollection(
  FeatureCollection.fromFeatures(
    listOf(feature)
  )
)
``` 

`feature` will not be applied. In current example above nothing will be shown on map. This though could be not determined.

## Expected behavior

Setting any feature with sync method of `feature`, `featureCollection`, `geometry` or `data` must apply immediately and not be overwritten with async method already running.

## Notes / preliminary analysis

Root cause for that is that `getSourceAs` actually creates new Java object of existing style and does not take `ignoreParsedGeoJson` of already created object into account.

**Comment by Guardiola31337** [comment]
Noting that while working on integrating `10.0.0-rc.3` `mapboxMapSdk` dependency version on the Navigation SDK https://github.com/mapbox/mapbox-navigation-android/pull/4566 we run into some `GeoJsonSource` failures 👀 

```
java.lang.NullPointerException
	at android.os.Handler.__constructor__(Handler.java:234)
	at android.os.Handler.<init>(Handler.java)
	at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource$workerHandler$2.invoke(GeoJsonSource.kt:35)
	at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource$workerHandler$2.invoke(GeoJsonSource.kt:30)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.getWorkerHandler(GeoJsonSource.kt)
	at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.applyGeoJsonData(GeoJsonSource.kt:613)
	at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.featureCollection(GeoJsonSource.kt:563)
	at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.featureCollection$default(GeoJsonSource.kt:562)
	at com.mapbox.navigation.ui.maps.route.arrow.RouteArrowUtils.initializeLayers(RouteArrowUtils.kt:74)
	at com.mapbox.navigation.ui.maps.route.arrow.RouteArrowUtilsTest.initializeLayers(RouteArrowUtilsTest.kt:232)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

OP may be the root cause of these flaky tests errors.

cc @pengdev @cafesilencio @LukasPaczos

**Comment by Chaoba** [comment]
@Guardiola31337 In tests you will need to init the workerThread in setUp like [this](https://github.com/mapbox/mapbox-maps-android/blob/main/extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt#L49)
Because when a test case is finished, the workerThread will be terminated.
