### ISSUE TITLE
java.lang.Error: vector

### ISSUE THREAD

**Issue by SamuelBrucksch** [mapbox/mapbox-maps-android#675]
## Environment

- Android OS version:
- Devices affected:
- Maps SDK Version: 10 RC8 and 10RC9 and maybe older versions

Hi,

we sometimes get this error:
```
java.lang.Error: vector
        at com.mapbox.maps.StyleManager.setStyleSourceProperty(StyleManager.java:-2)
        at com.mapbox.maps.NativeMapImpl.setStyleSourceProperty(NativeMapImpl.kt:485)
        at com.mapbox.maps.Style$setStyleSourceProperty$1.invoke(Style.kt:596)
        at com.mapbox.maps.Style$setStyleSourceProperty$1.invoke(Style.kt:25)
        at com.mapbox.maps.UtilsKt.call(Utils.kt:9)
        at com.mapbox.maps.Style.setStyleSourceProperty(Style.kt:595)
        at com.mapbox.maps.extension.style.sources.Source.updateProperty(Source.kt:94)
        at com.mapbox.maps.extension.style.sources.Source.setProperty$extension_style_release(Source.kt:84)
        at com.mapbox.maps.extension.style.sources.Source.setProperty$extension_style_release$default(Source.kt:82)
        at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.applyGeoJsonData(GeoJsonSource.kt:364)
        at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.featureCollection(GeoJsonSource.kt:313)
        at com.iternio.abrpapp.auto.renderer.MapRenderer.onCameraChanged(MapRenderer.java:767)
        at com.iternio.abrpapp.auto.renderer.MapRenderer.access$2200(MapRenderer.java:67)
        at com.iternio.abrpapp.auto.renderer.MapRenderer$1.lambda$onSurfaceAvailable$0(MapRenderer.java:186)
        at com.iternio.abrpapp.auto.renderer.-$$Lambda$MapRenderer$1$kkTW2ByreaVDGgn1yUKoyQDNqW8.onCameraChanged(Unknown:2)
        at com.mapbox.maps.NativeObserver.notify(NativeObserver.kt:40)
        at com.mapbox.maps.CameraManager.setCamera(CameraManager.java:-2)
        at com.mapbox.maps.NativeMapImpl.setCamera(NativeMapImpl.kt:35)
        at com.mapbox.maps.MapboxMap$setCamera$1.invoke(MapboxMap.kt:280)
        at com.mapbox.maps.MapboxMap$setCamera$1.invoke(MapboxMap.kt:37)
        at com.mapbox.maps.UtilsKt.call(Utils.kt:9)
        at com.mapbox.maps.MapboxMap.setCamera(MapboxMap.kt:280)
        at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.performMapJump(CameraAnimationsPluginImpl.kt:185)
        at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.access$performMapJump(CameraAnimationsPluginImpl.kt:36)
        at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl$commitChangesRunnable$1.run(CameraAnimationsPluginImpl.kt:62)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

The code that is executed by us is this:
```
private GeoJsonSource altRouteMarkersGeoJsonSource;
[...]
mapboxMap.addOnCameraChangeListener(MapRenderer.this::onCameraChanged);
[...]

private void onCameraChanged() {
[...]
  if (newAltRouteMarkersAvailable) {
    altRouteMarkersGeoJsonSource.featureCollection(altRouteMarkers, null);
  }
}
```

I don't know the exact values that are being passed, but the geoJsonSource is modified on `onCameraChanged` callback of `MapboxMap`. Any idea what the issue here could be? This does not always crash. But there are users where it happens more often.

The logic in the onCameraChanged function calculates if a specific graphic should be anchored top/left/bottom/right and updates the `GeoJsonSource` if the graphics should be drawn differently.

But this also seems to happen on other occurences, where we just call `*.featureCollection(features, null)` with a new set of data. So possibly not related to the camera update listener.

Best
Samuel

**Comment by SamuelBrucksch** [comment]
Another error with the same native error message:
```
java.lang.Error: vector
        at com.mapbox.maps.Map.render(Map.java:-2)
        at com.mapbox.maps.NativeMapImpl.render(NativeMapImpl.kt:31)
        at com.mapbox.maps.renderer.MapboxRenderer.onDrawFrame(MapboxRenderer.kt:99)
        at com.mapbox.maps.renderer.MapboxRenderThread.draw(MapboxRenderThread.kt:170)
        at com.mapbox.maps.renderer.MapboxRenderThread.doFrame(MapboxRenderThread.kt:305)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1521)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1321)
        at android.view.Choreographer.doFrame(Choreographer.java:989)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1508)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:264)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

Unfortunately not more information what happened here before. But according to logs map was just drawing navigation and then suddenly crashed after a while.

**Comment by SamuelBrucksch** [comment]
And here we have a third one. I can supply more information on that one as it contains our code in the stacktrace:
```
java.lang.Error: vector
        at com.mapbox.maps.StyleManager.setStyleLayerProperty(StyleManager.java:-2)
        at com.mapbox.maps.NativeMapImpl.setStyleLayerProperty(NativeMapImpl.kt:192)
        at com.mapbox.maps.Style$setStyleLayerProperty$1.invoke(Style.kt:208)
        at com.mapbox.maps.Style$setStyleLayerProperty$1.invoke(Style.kt:25)
        at com.mapbox.maps.UtilsKt.call(Utils.kt:9)
        at com.mapbox.maps.Style.setStyleLayerProperty(Style.kt:208)
        at com.mapbox.maps.extension.style.layers.Layer.updateProperty(Layer.kt:136)
        at com.mapbox.maps.extension.style.layers.Layer.setProperty$extension_style_release(Layer.kt:131)
        at com.mapbox.maps.extension.style.layers.generated.SymbolLayer.iconRotate(SymbolLayer.kt:673)
        at com.iternio.abrpapp.auto.renderer.MapRenderer.setCarPosition(MapRenderer.java:544)
        at com.iternio.abrpapp.auto.renderer.CarAnimatorListener.onAnimationUpdate(CarAnimatorListener.java:83)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1558)
        at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1349)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1481)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1254)
        at android.view.Choreographer.doCallbacks(Choreographer.java:995)
        at android.view.Choreographer.doFrame(Choreographer.java:883)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1224)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8387)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

setCarPosition calls
```
carMarkerGeoJsonSource.geometry(carPosition, null);
```

So it is most likely related to the first one.

**Comment by kiryldz** [comment]
Hey @SamuelBrucksch, this might be connected with https://github.com/mapbox/mapbox-maps-android/issues/649.
Thanks for providing so much information, we'll do several checks on our end.

It may appear that several stack traces you provided are not exactly connected but let's start with moving parsing geojson off the main thread wherever it's possible in your code, e.g.:

```
// now
private void onCameraChanged() {
[...]
  if (newAltRouteMarkersAvailable) {
    altRouteMarkersGeoJsonSource.featureCollection(altRouteMarkers, null);
  }
}

// change to
// if you have some code to be executed after setting featureCollection - put it in lambda we're adding.
private void onCameraChanged() {
[...]
  if (newAltRouteMarkersAvailable) {
    altRouteMarkersGeoJsonSource.featureCollection(altRouteMarkers, geoJsonSource -> null);
  }
}
```
and
```
// from 
carMarkerGeoJsonSource.geometry(carPosition, null);
// change to
carMarkerGeoJsonSource.geometry(carPosition, geoJsonSource -> null);
```

etc

this will move geojson parsing to another thread and at least in situation above you'll move your code out of callchain with `setCamera` that most likely did throw an exception.

**Comment by SamuelBrucksch** [comment]
Thanks will try that. Right now i just surrounded those calls with try catch. Will check what happens when applying your changes.

**Comment by SamuelBrucksch** [comment]
Ok i tried that and at least I did not get that error the last two days, but then again I didn't have it before (I'm on Pixel 3 with Android 11). So not sure if that is any valuable feedback on the fix.

However that workaround might also only work on the first and last stack trace related error. The other one at com.mapbox.maps.Map.render(Map.java:-2) is either unrelated.

Also we cannot catch that one. We get reports from people that the app crashes during navigation and they los trust in us. Is there anything else we can do? I do not want to publish a release with the workaround without knowing if it really fixes anything. In worst case the errors are still thrown but I can not catch them anymore if they are async.

**Comment by tobrun** [comment]
Closing this for now but please reach out if you hit this issue again
