### ISSUE TITLE
Navigation SDK  throw  MapboxInvalidModuleException

### ISSUE THREAD

**Issue by xiaxiayige** [mapbox/mapbox-maps-android#676]
## Environment

- Android OS version: ，  Android 11 
- Devices affected:     SM-N981U ，moto g play (2021) ， VOG-L09（ROM HUWWEI/EMOTION）
- Maps SDK Version: 
api “com.mapbox.mapboxsdk:mapbox-android-sdk:   : 9.6.2”,
api  “com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9： 0.9.0”,
api("com.mapbox.navigation:core:  : '1.5.1'）{
 exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-telemetry'
}

## Observed behavior and steps to reproduce

code 
‘
     navigationOptions = MapboxNavigation
                .defaultNavigationOptionsBuilder(activity.this, token)
                .build();
        mapboxNavigation = MapboxNavigationProvider.create(navigationOptions);
’

**com.mapbox.common.module.provider.MapboxInvalidModuleException**

NavigationRouter has been excluded from build but a correct alternative was not provided. Make sure that: - Your custom module implements com.mapbox.navigation.base.route.Router. - Your custom module class is annotated with @MapboxModule(a.NavigationRouter). - You've provided a `ModuleProvider` instance to Mapbox_RouterModuleConfiguration#setModuleProvider before initializing the library, unless `enableConfiguration` flag is set to false and your implementation has a public, non-arg constructor or is a Kotlin object.

Caused by:
com.mapbox.common.module.provider.MapboxInvalidModuleException:NavigationRouter has been excluded from build but a correct alternative was not provided.
Make sure that:
- Your custom module implements com.mapbox.navigation.base.route.Router.
- Your custom module class is annotated with @MapboxModule(a.NavigationRouter).
- You've provided a `ModuleProvider` instance to Mapbox_RouterModuleConfiguration#setModuleProvider before initializing the library,
unless `enableConfiguration` flag is set to false and your implementation has a public, non-arg constructor or is a Kotlin object.
com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:88)
com.mapbox.navigation.core.a.<init>(MapboxNavigation.kt:179)
com.mapbox.navigation.core.c.a(MapboxNavigationProvider.kt:23)

**Comment by xiaxiayige** [comment]
more log :

09-26 12:07:05.295 25792 25792 E MapboxModuleProvider: Module loading failed
1009-26 12:07:05.295 25792 25792 E MapboxModuleProvider: java.lang.NoSuchMethodException: com.mapbox.navigation.route.internal.hybrid.MapboxHybridRouter.<init> []
1109-26 12:07:05.295 25792 25792 E MapboxModuleProvider: at java.lang.Class.getConstructor0(Class.java:2332)
1209-26 12:07:05.295 25792 25792 E MapboxModuleProvider: at java.lang.Class.getConstructor(Class.java:1728)
1309-26 12:07:05.295 25792 25792 E MapboxModuleProvider: at com.mapbox.common.module.provider.MapboxModuleProvider$noArgConstructorCreator$1.getInstance(MapboxModuleProvider.kt:107)
1409-26 12:07:05.295 25792 25792 E MapboxModuleProvider: at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:69)
1509-26 12:07:05.295 25792 25792 E MapboxModuleProvider: at com.mapbox.navigation.core.a.<init>(MapboxNavigation.kt:179)
1609-26 12:07:05.295 25792 25792 E MapboxModuleProvider: at com.mapbox.navigation.core.c.a(MapboxNavigationProvider.kt:23)

**Comment by xiaxiayige** [comment]
move to https://github.com/mapbox/mapbox-navigation-android/issues/4907
