### ISSUE TITLE
Android 8 ANR when screen is turned off and on again

### ISSUE THREAD

**Issue by e-hartig** [mapbox/mapbox-maps-android#684]
## Environment

- Android OS version: Versions 8.0 and 8.1
- Devices affected: Motorola XT1650, LG G5, LG G30, Nexus 5X, etc
- Maps SDK Version: Mapbox 10.0.0-rc8

## Observed behavior and steps to reproduce

On Android 8 and 8.1, the application freezes when the device's screen is turned off and then turned back on again when a MapView is in the layout.  This is easily reproducible on an emulator, and I reported this as an issue on the emulator in #431 .  It was assumed then that this was an issue specifically with the emulator, but now we have users on real devices who are seeing the same behavior on 10.0.0-rc5 and 10.0.0-rc6.  I also dug up an old Nexus 5X on Android 8.1 and I can reproduce the issue myself on 10.0.0-rc5.

Steps:
1. On an Android 8 device, turn off the screen while viewing a MapView
2. Turn the screen back on

## Expected behavior

App remains responsive after screen turns back on.

## Notes / preliminary analysis

This occurs due to the mapbox rendering thread awaiting a lock on the main thread which is never signalled.

Stack trace:
wait:-1, Object (java.lang)
parkFor$:2137, Thread (java.lang)
park:358, Unsafe (sun.misc)
park:190, LockSupport (java.util.concurrent.locks)
await:2059, AbstractQueuedSynchronizer$ConditionObject (java.util.concurrent.locks)
onSurfaceCreated:282, MapboxRenderThread (com.mapbox.maps.renderer)
surfaceChanged:24, MapboxSurfaceRenderer (com.mapbox.maps.renderer)
surfaceChanged:16, MapboxSurfaceHolderRenderer (com.mapbox.maps.renderer)
updateSurface:675, SurfaceView (android.view)
windowStopped:220, SurfaceView (android.view)
setWindowStopped:1289, ViewRootImpl (android.view)
setStoppedState:611, WindowManagerGlobal (android.view)
performRestart:7072, Activity (android.app)
handleSleeping:4203, ActivityThread (android.app)
-wrap22:-1, ActivityThread (android.app)
handleMessage:1780, ActivityThread$H (android.app)
dispatchMessage:106, Handler (android.os)
loop:164, Looper (android.os)
main:6494, ActivityThread (android.app)
invoke:-1, Method (java.lang.reflect)
run:438, RuntimeInit$MethodAndArgsCaller (com.android.internal.os)
main:807, ZygoteInit (com.android.internal.os)

**Comment by kiryldz** [comment]
@e-hartig thanks for reporting, will be available in next release coming up next week

**Comment by mercierj** [comment]
Hi,

I still have few of this ANR reported by crashlytics with latest version (10.1.0)

main (waiting): tid=1 systid=2885
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at com.mapbox.maps.renderer.MapboxRenderThread.onSurfaceCreated(MapboxRenderThread.java:282)
       at com.mapbox.maps.renderer.MapboxSurfaceRenderer.surfaceChanged(MapboxSurfaceRenderer.java:24)
       at com.mapbox.maps.renderer.MapboxSurfaceHolderRenderer.surfaceChanged(MapboxSurfaceHolderRenderer.java:17)
       at android.view.SurfaceView.updateSurface(SurfaceView.java:1203)
       at android.view.SurfaceView.setWindowStopped(SurfaceView.java:283)
       at android.view.SurfaceView.surfaceCreated(SurfaceView.java:1686)
       at android.view.ViewRootImpl.notifySurfaceCreated(ViewRootImpl.java:1898)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3001)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2178)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8712)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
       at android.view.Choreographer.doFrame(Choreographer.java:1049)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:245)
       at android.app.ActivityThread.main(ActivityThread.java:8004)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
