### ISSUE TITLE
v10 SDK crashing with "couldn't find DSO to load: libEGL.so" on Android 12 with Places Plugin

### ISSUE THREAD

**Issue by samcrawford** [mapbox/mapbox-maps-android#803]
## Environment

- Android OS version: 12 (simulator)
- Devices affected: See above
- Maps SDK Version: 10.0.0

## Observed behavior and steps to reproduce

I'm in the process of migrating to Mapbox Android SDK v10 and Navigation SDK v2. However, I'm seeing a crash on Android 12 (API 31).

I'm using the Places Plugin from https://github.com/mapbox/mapbox-plugins-android/tree/main/plugin-places

### Code I'm using for the Place Picker:

```
startActivityForResult(
        new PlacePicker.IntentBuilder()
                .accessToken(getString(R.string.mapbox_access_token))
                .placeOptions(PlacePickerOptions.builder()
                        .statingCameraPosition(startPosition)
                        .build())
                .build(getActivity()), requestCode);
```

### Places Plugin with Navigation SDK v2 / Mapbox SDK v10, with Android 12 simulator (x86_64)

As soon as I try to launch the Places Picker activity, I get the following crash in Android 12, if and only if my app also embeds the Navigation SDK (v2):

```
D/SoLoader: init start
D/SoLoader: adding system library source: /vendor/lib
    adding system library source: /system/lib
D/SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/~~FSyGRfK6mW1XVoHgnHxCyw==/com.trailrouter-WsVZ4CmpKZHWmQ1uNt5HLw==/lib/x86_64 flags = 0]
D/SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.trailrouter/lib-main flags = 1]
    Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
    Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/~~FSyGRfK6mW1XVoHgnHxCyw==/com.trailrouter-WsVZ4CmpKZHWmQ1uNt5HLw==/lib/x86_64 flags = 0]
    Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.trailrouter/lib-main flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.trailrouter/lib-main
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
D/ApkSoSource: allowing considering of lib/x86_64/libc++_shared.so: libc++_shared.so not in system lib dir
D/ApkSoSource: allowing considering of lib/x86_64/libmapbox-common.so: libmapbox-common.so not in system lib dir
    allowing considering of lib/x86_64/libmapbox-gl.so: libmapbox-gl.so not in system lib dir
D/ApkSoSource: allowing considering of lib/x86_64/libmapbox-maps.so: libmapbox-maps.so not in system lib dir
    allowing considering of lib/x86_64/libnavigator-android.so: libnavigator-android.so not in system lib dir
D/ApkSoSource: allowing considering of lib/x86_64/libsentry-android.so: libsentry-android.so not in system lib dir
D/ApkSoSource: allowing considering of lib/x86_64/libsentry.so: libsentry.so not in system lib dir
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
I/fb-UnpackingSoSource: extracting DSO libc++_shared.so
I/fb-UnpackingSoSource: extracting DSO libmapbox-common.so
I/fb-UnpackingSoSource: extracting DSO libmapbox-gl.so
I/fb-UnpackingSoSource: extracting DSO libmapbox-maps.so
I/fb-UnpackingSoSource: extracting DSO libnavigator-android.so
I/fb-UnpackingSoSource: extracting DSO libsentry-android.so
I/fb-UnpackingSoSource: extracting DSO libsentry.so
V/fb-UnpackingSoSource: Finished regenerating DSO store com.facebook.soloader.ApkSoSource
    starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.trailrouter/lib-main (from syncer thread)
    not releasing dso store lock for /data/user/0/com.trailrouter/lib-main (syncer thread started)
D/SoLoader: init finish: 4 SO sources prepared
    init exiting
D/SoLoader: About to load: libmapbox-gl.so
D/SoLoader: libmapbox-gl.so found on /data/data/com.trailrouter/lib-main
D/SoLoader: Loading lib dependencies: [libEGL.so, libGLESv2.so, libandroid.so, libjnigraphics.so, liblog.so, libz.so, libm.so, libdl.so, libc.so]
    About to load: libEGL.so
    libEGL.so not found on /data/data/com.trailrouter/lib-main
D/SoLoader: libEGL.so not found on /data/app/~~FSyGRfK6mW1XVoHgnHxCyw==/com.trailrouter-WsVZ4CmpKZHWmQ1uNt5HLw==/lib/x86_64
    libEGL.so not found on /vendor/lib
    libEGL.so not found on /system/lib
E/SoLoader: couldn't find DSO to load: libEGL.so
W/System.err: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libEGL.so
W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:587)
        at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:111)
W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
        at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:731)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
        at com.mapbox.mapboxsdk.module.loader.LibraryLoaderProviderImpl$SoLibraryLoader.load(LibraryLoaderProviderImpl.java:42)
W/System.err:     at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:43)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:13)
W/System.err:     at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:67)
W/System.err:     at com.trailrouter.GeocoderListener.startGeocoder(GeocoderListener.java:76)
        at com.trailrouter.GeocoderListener.onClick(GeocoderListener.java:29)
W/System.err:     at android.view.View.performClick(View.java:7441)
        at android.widget.CompoundButton.performClick(CompoundButton.java:146)
W/System.err:     at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
W/System.err:     at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/SoLoader: couldn't find DSO to load: libmapbox-gl.so caused by: couldn't find DSO to load: libEGL.so
E/Mbgl-LibraryLoader: Failed to load native shared library.
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libmapbox-gl.so caused by: couldn't find DSO to load: libEGL.so
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
        at com.mapbox.mapboxsdk.module.loader.LibraryLoaderProviderImpl$SoLibraryLoader.load(LibraryLoaderProviderImpl.java:42)
        at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:43)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:13)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:67)
        at com.trailrouter.GeocoderListener.startGeocoder(GeocoderListener.java:76)
        at com.trailrouter.GeocoderListener.onClick(GeocoderListener.java:29)
        at android.view.View.performClick(View.java:7441)
        at android.widget.CompoundButton.performClick(CompoundButton.java:146)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/com.trailroute: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.trailrouter, PID: 16784
    java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:67)
        at com.trailrouter.GeocoderListener.startGeocoder(GeocoderListener.java:76)
        at com.trailrouter.GeocoderListener.onClick(GeocoderListener.java:29)
        at android.view.View.performClick(View.java:7441)
        at android.widget.CompoundButton.performClick(CompoundButton.java:146)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/com.trailroute: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.finalize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_finalize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_finalize__)
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.finalize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_finalize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_finalize__)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.finalize(Native Method)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
        at java.lang.Daemons$Daemon.run(Daemons.java:139)
        at java.lang.Thread.run(Thread.java:920)
```

My dependencies in build.gradle are pretty simple for Mapbox:

```
implementation 'com.mapbox.navigation:android:2.0.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v9:0.12.0'
```

Note that I haven't tried it on a real Android 12 phone yet (I don't have access to one currently).

### Places Plugin with Navigation SDK v1.x / Mapbox SDK v9.x, with Android 12 simulator (x86_64)

This combination works fine. My build.gradle dependencies are as follows:

```
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v9:0.12.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0'
implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:6.0.0-alpha.1'
implementation "com.mapbox.navigation:ui:1.6.1"
```

### Places Plugin with Navigation SDK v2 / Mapbox SDK v10, with Android 11 simulator (x86)

Works fine.

## Notes / preliminary analysis

I suspect my issue is arising because I'm mixing mapbox-android-plugin-places (which is based on the Mapbox v9.x SDK) with the Navigation SDK v2 (which is based on the Mapbox v10 SDK). But there's no places plugin for the v10 SDK, as far as I know.

**Comment by kiryldz** [comment]
@samcrawford you're totally right: you could not mix v9 maps with v10 maps and this is also true for the plugins. Search SDK is designed to replace plugin-places if using Maps SDK v10 and Nav SDK v2, you could check out this [example](https://github.com/mapbox/mapbox-search-android-examples/blob/main/app/src/main/java/com/mapbox/search/sample/maps/MapsIntegrationExampleActivity.kt) of some basic search integration with Maps v10.
