### ISSUE TITLE
java.lang.ClassNotFoundException: com.mapbox.module.Mapbox_HttpClientModuleConfiguration

### ISSUE THREAD

**Issue by sanpark** [mapbox/mapbox-maps-android#883]
W/System.err: java.lang.ClassNotFoundException: com.mapbox.module.Mapbox_HttpClientModuleConfiguration
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
W/System.err:     at java.lang.Class.forName(Class.java:379)
        at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:27)
        at com.mapbox.common.core.module.CommonSingletonModuleProvider.createHttpService(CommonSingletonModuleProvider.kt:41)
        at com.mapbox.common.PlatformHttpService.createPlatformHttpService(PlatformHttpService.java:11)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.module.Mapbox_HttpClientModuleConfiguration" on path: DexPathList[[zip file "/data/app/com.sanpark.mapboxtest-DDEO2hbAf7EpEW3jLjsekg==/base.apk"],nativeLibraryDirectories=[/data/app/com.sanpark.mapboxtest-DDEO2hbAf7EpEW3jLjsekg==/lib/arm64, /data/app/com.sanpark.mapboxtest-DDEO2hbAf7EpEW3jLjsekg==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 6 more

**Comment by tyofemi** [comment]
Please provide more information.

**Comment by knov** [comment]
Thank you for your feedback. At this time we cannot ascertain the issue from the provided report and are closing this ticket. If you still encounter this exception, please reopen and provide additional context so that we can explore the issue with you and help to resolve.
