### ISSUE TITLE
Using Style.SATELLITE to draw a heat map will cause a crash

### ISSUE THREAD

**Issue by RocCaiy23** [mapbox/mapbox-maps-android#949]
## Environment

- Android OS version:11
- Devices affected:OPPO A55 5G
- Maps SDK Version:`android-v10.2.0-rc.1`

## Observed behavior and steps to reproduce

Using `Style.SATELLITE` to draw a heat map

## Error stack trace

`2021-12-03 14:58:54.205 29720-29720/com.mapbox.maps.testapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.maps.testapp, PID: 29720
    java.lang.RuntimeException: Add layer failed: Cannot find layer with id: earthquakes-heat
        at com.mapbox.maps.extension.style.layers.Layer.bindTo(Layer.kt:115)
        at com.mapbox.maps.extension.style.layers.LayerUtils.addLayerAbove(LayerExt.kt:74)
        at com.mapbox.maps.testapp.examples.HeatmapLayerActivity.addRuntimeLayers(HeatmapLayerActivity.kt:371)
        at com.mapbox.maps.testapp.examples.HeatmapLayerActivity.access$addRuntimeLayers(HeatmapLayerActivity.kt:66)
        at com.mapbox.maps.testapp.examples.HeatmapLayerActivity$onCreate$$inlined$apply$lambda$1$1.onResponse(HeatmapLayerActivity.kt:278)
        at com.mapbox.maps.testapp.examples.HeatmapLayerActivity$onCreate$$inlined$apply$lambda$1$1.onResponse(HeatmapLayerActivity.kt:262)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:264)
        at android.app.ActivityThread.main(ActivityThread.java:8306)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)`

**Comment by ank27** [comment]
@RocCaiy23, We use `waterway-label` layer in `HeatmapLayerActivity` that is present in `Style.Light`, but  not in `Style.SATELLITE`. That's why you get the crash. As it tries to add heatMapLayer on top of waterway-label.

Thanks for notifying this as well, we will add that in the documentation of the activity :)

**Comment by ank27** [comment]
You can also use `style#styleLayerExists` to check if a layer exists.
probably something like this :
```
private fun addRuntimeLayers(style: Style) {
  style.addSource(createEarthquakeSource())
  if (!style.styleLayerExists("waterway-label")) {
    Log.d("HeatmapLayer", "waterway label not exist with ${style.styleURI}")
    style.addLayer(createHeatmapLayer())
    style.addLayerBelow(createCircleLayer(), HEATMAP_LAYER_ID)
  } else {
    style.addLayerAbove(createHeatmapLayer(), "waterway-label")
    style.addLayerBelow(createCircleLayer(), HEATMAP_LAYER_ID)
  }
}
```

Attaching the result here : 
![heatmap_satellite](https://user-images.githubusercontent.com/11589497/144587032-4d56f99a-75ae-4d92-839a-f76d0740dcbf.jpg)
